'use client';

import { useEffect, useState } from 'react';
import Image from 'next/image';
import { preload } from 'react-dom';
import { ArrowUpRight, ArrowRight, ArrowDown, Check, Users, Sparkles, Mail, Menu, X, CalendarDays, BriefcaseBusiness, ChevronRight, Clock3, FileText, Gift, Target, SlidersHorizontal, Phone, BarChart3, MapPin, Share2, CheckCheck, MessageCircle, Search } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import dynamic from 'next/dynamic';
import { Pains } from '@/components/marketing/Pains';
import { AiPresenter } from '@/components/marketing/AiPresenter';
import { Panels } from '@/components/marketing/Panels';
import { RealScreens } from '@/components/marketing/RealScreens';
import { DemoModal } from '@/components/marketing/DemoModal';
import { TypedH2 } from '@/components/marketing/Typewriter';
// Below-the-fold sections load as separate chunks so the initial bundle parses sooner. SSR stays on for SEO.
const ProductMap = dynamic(() => import('@/components/marketing/ProductMap').then((m) => m.ProductMap));
const Industries = dynamic(() => import('@/components/marketing/Industries').then((m) => m.Industries));
const Automation = dynamic(() => import('@/components/marketing/Automation').then((m) => m.Automation));
const Trust = dynamic(() => import('@/components/marketing/Trust').then((m) => m.Trust));
import { SOLUTIONS, SOLUTION_LABEL, solutionPath } from '@/lib/solutions';
import { blogPath, hubPath, langPrefix } from '@/lib/site-paths';
import { COMPANY } from '@/lib/company';
import { LEGAL, LEGAL_KEYS, LEGAL_PATH } from '@/lib/legal-copy';
import { publicDomains } from '@/lib/product-map';
import { PATHS, jsonLd, pageTitle } from '@/lib/seo';
import { NavigationMenu, NavigationMenuList, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink } from '@/components/ui/navigation-menu';

import type { Lang } from '@/lib/product-map';
// WhatsApp number for the demo CTA (digits only, with country code). Empty → fall back to the demo page.
const WA_NUMBER = '994512060838';
const WA_TEXT = 'Salam! LeadDrive CRM demosuna baxmaq istəyirəm. / Здравствуйте! Хочу посмотреть демо LeadDrive CRM.';
export const DEMO = WA_NUMBER ? `https://wa.me/${WA_NUMBER}?text=${encodeURIComponent(WA_TEXT)}` : 'https://wa.me/994512060838';
export const TEXT = {
  ru: {
    dashGreeting:'Добрый вечер, Лейла!', dashNav:['Звонки','ИИ советник','Аналитика','Полевые агенты','Отчёты','Сделки','Задачи','Соц сети','Входящие','Клиентская поддержка'], dashSub:'Ключевые сигналы бизнеса и следующие шаги — в одной сводке.', dashAsk:'Например: какие сделки требуют внимания?', dashBrief:'Фокус дня', dashBriefTag:'DA VINCI · СВОДКА', dashLines:['Нарушения SLA, требующие реакции: 66.','Сейчас в работе 63 активных лида.','В воронке 28 сделок, конверсия 77%.'], dashActions:['Новый лид','Сделки','Доски','Предложения'], dashDiscuss:'Обсудить сводку с Da Vinci', dashCaption:'Реальный экран LeadDrive: живой фон и сводка Da Vinci',
   
    product:'Продукт', solutions:'Решения', blog:'Блог', ai:'AI и Da Vinci', team:'Для команды', plans:'Условия', about:'О компании', demo:'Запросить демо', login:'Войти', skip:'К содержимому',
    eyebrow:'НА АЗЕРБАЙДЖАНСКОМ. СДЕЛАНО В БАКУ.', hero1:'Клиент в центре.', hero2:'Продажи под контролем.', intro:'Обращения, сделки и история отношений — рядом. AI помогает с ответами и данными, команда продолжает работу с клиентом.', explore:'Заглянуть в CRM',
    example:'Демонстрационные данные', heroNote:'За каждой сделкой — человек.', heroNote2:'Всё важное о нём — в LeadDrive.', clientQuote:'«Давайте обсудим CRM для нашей команды»', newMessage:'Новое сообщение',
    sales:'Сделки', inbox:'Обращения', client:'Клиент', pipeline:'Воронка продаж', stages:['Новый интерес','Обсуждение','Предложение'], dealNames:['Caspian Studio','Northline','Aroma Market'], dealDesc:['CRM для команды','Единая история клиентов','Автоматизация продаж'], next:['Уточнить задачи','Показать сценарии','Обсудить предложение'], owner:'Ответственный', tomorrow:'Завтра, 11:00', nextStep:'Следующий шаг', task:'Демонстрация CRM', all:'Все обращения', conversation:'История общения', received:'Здравствуйте! Нам нужна CRM на 8 сотрудников.', reply:'Здравствуйте, Лейла! Расскажите, как вы сейчас работаете с обращениями.', note:'Клиент выбирает CRM для команды из 8 человек.', contact:'Лейла Мамедова', company:'Компания', need:'Потребность', needText:'Собрать обращения и сделки в одном месте', activity:'Последняя активность', activityText:'Обсудили задачи команды', channel:'Канал обращения',
    coreEyebrow:'ОДНА ИСТОРИЯ. ВСЯ КОМАНДА.', core1:'От первого интереса', core2:'до долгих отношений.', coreIntro:'Продажи, общение и маркетинг работают с одним клиентом. Без потерянного контекста между отделами.',
    modules:[
      {id:'sales',title:'Продажи',subtitle:'Видно, где сделка и что дальше.',description:'Лиды, воронка и предложения рядом с договорённостями. У каждой сделки — свой этап, ответственный и следующий шаг.',tags:['Лиды и квалификация','Воронки продаж','Коммерческие предложения']},
      {id:'clients',title:'Клиенты и общение',subtitle:'Начните с того, что уже знаете.',description:'Компании, контакты, переписка и активности в общей истории. Коллега может продолжить разговор с контекстом.',tags:['Карточка клиента','Общий Inbox','Быстрые ответы']},
      {id:'marketing',title:'Маркетинг',subtitle:'Нужное сообщение своей аудитории.',description:'Объединяйте контакты в сегменты, готовьте кампании и цепочки касаний. Изучайте обратную связь через опросы и NPS.',tags:['Сегменты','Кампании и цепочки','Мероприятия и NPS']},
      {id:'contracts',title:'Договоры',subtitle:'Договорённости обретают форму.',description:'Документы, версии и этапы согласования связаны с клиентом. У команды есть единое место для работы с договором.',tags:['Реестр договоров','История версий','Согласование']},
      {id:'loyalty',title:'Лояльность',subtitle:'Дайте повод вернуться.',description:'Уровни, правила начисления и награды помогают построить программу лояльности. История участника показывает движение баллов.',tags:['Уровни и правила','Награды','История баллов']},
    ],
    teamEyebrow:'ТЕХНОЛОГИИ ПОМОГАЮТ. ЛЮДИ РЕШАЮТ.', team1:'Меньше «перешли мне».', team2:'Больше работы вместе.', teamText:'Менеджеру — договорённости. Руководителю — картина продаж. Маркетингу — история клиента. У каждого своя роль, у команды общий контекст.', teamLink:'Посмотреть возможности', teamCaption:'Хорошая работа начинается с понимания.',
    aiEyebrow:'ДВЕ РОЛИ AI В ВАШЕЙ CRM', ai1:'Помощь там,', ai2:'где она нужна.', aiIntro:'В разговоре с клиентом и в ежедневных решениях команды.', agent:'AI-агент', davinci:'Da Vinci', agentTag:'В ДИАЛОГЕ С КЛИЕНТОМ', davinciTag:'РЯДОМ С СОТРУДНИКОМ', agentTitle:'Отвечает. Уточняет. Передаёт контекст.', davinciTitle:'Замечает. Объясняет. Предлагает.', agentText:'Для каждого канала выбирайте, кто отвечает: человек, AI-черновик или AI-агент. Персона, база знаний и ключевые слова для передачи оператору настраиваются в CRM.', davinciText:'Изучайте сигналы по клиентам и сделкам, смотрите объяснения и выбирайте подходящий следующий шаг.', illustrative:'Иллюстрация сценария', stepLabels:['Сообщение','Контекст','Следующий шаг'], dvStepLabels:['Сигнал','Объяснение','Решение'], play:'Проиграть сценарий', pause:'Приостановить', replay:'Повторить',
    agentCards:[{label:'Клиент',title:'«Нужна CRM на 8 сотрудников»',text:'Новый разговор в общем Inbox.'},{label:'Контекст разговора',title:'Заявки теряются в переписке',text:'Команде нужны общая история и ответственные.'},{label:'Менеджеру',title:'Продолжить разговор с Лейлой',text:'Обсудить сбор обращений и работу со сделками.'}],
    dvCards:[{label:'Сигнал по сделке',title:'Давно не было активности',text:'У сделки нет нового шага в истории.'},{label:'Контекст',title:'Предложение уже обсуждали',text:'Проверьте договорённости перед следующим касанием.'},{label:'Решение сотрудника',title:'Согласовать следующий разговор',text:'Изучите рекомендацию и подтвердите подходящее действие.'}],
    decision:'Решение и контроль остаются у команды.', channelsTitle:'Разговоры встречаются здесь.', channelsText:'Подключайте нужные каналы к общему Inbox. Состав и настройка подключений зависят от вашего процесса.',
    insightEyebrow:'ОБЩАЯ КАРТИНА ПРОДАЖ', insight1:'Знать, где вы сейчас.', insight2:'Понимать, куда двигаться.', insightText:'Смотрите на воронку, активность клиентов и коммуникации. Используйте сигналы Da Vinci, чтобы выбрать, чему уделить внимание.', overview:'Обзор', pipelineLabel:'Сделки по этапам', signals:'Требует внимания', signalText:'Сделки без следующего шага', clientActivity:'Активность клиентов', currentWeek:'Эта неделя',
    startEyebrow:'НАЧНЁМ С ВАШЕГО БИЗНЕСА', startTitle:'Покажем на ваших сценариях.', startText:'Расскажите, как приходят обращения, кто работает с клиентами и что хотите улучшить. На демо разберём подходящий путь в LeadDrive.', steps:[['Ваши задачи','Обсудим процесс от первого обращения до сделки.'],['Ваш сценарий','Покажем нужные действия и связи в CRM.'],['Ваш следующий шаг','Согласуем состав настройки и план запуска.']],
    faqTitle:'Перед началом', questions:[['Чем AI-агент отличается от Da Vinci?','AI-агент работает в диалоге с клиентом по настроенным правилам. Da Vinci помогает сотруднику изучать сигналы, контекст и предложения действий внутри CRM.'],['Какие каналы можно подключить?','В каталоге есть WhatsApp Business, Telegram, email, SMS, Facebook Messenger, Instagram и TikTok через Chatwoot. На демонстрации уточним доступ и настройку нужных вам провайдеров.'],['Можно ли начать с данных в таблицах?','Да, начнём с изучения ваших контактов, компаний и сделок. Состав, качество и условия переноса согласуем по вашим исходным данным.'],['Какое CRM-решение подойдёт бизнесу в Азербайджане?','LeadDrive — CRM-система для компаний в Баку и по всему Азербайджану: интерфейс на азербайджанском, русском и английском, WhatsApp и Instagram в общем Inbox, договоры, счета в AZN и поддержка. Подходит продажам, сервису, полевым командам и отраслевым сценариям.'],['Чем LeadDrive отличается от других CRM-систем?','Это одно рабочее пространство вместо набора отдельных инструментов: продажи, коммуникации, договоры, финансы, поддержка и AI-помощники связаны с одной карточкой клиента. Всё, что описано на этом сайте, проверено на реальных экранах системы.'],['Сколько это стоит?','Фиксированных тарифов нет. Расскажите о команде и задачах в WhatsApp или на демонстрации, и мы предложим состав возможностей и условия под вас.']],
    footerEyebrow:'LEADDRIVE CRM', footer1:'Давайте начнём', footer2:'с вашего клиента.', footerText:'Один разговор — чтобы увидеть, как LeadDrive впишется в работу команды.', footerDemo:'Обсудить мою задачу', copyright:'Сделано для работы с людьми.',
    segment:'Сегмент аудитории', segmentName:'Интерес к новому продукту', contacts:'контактов', campaign:'Кампания', campaignName:'Приглашение на презентацию', chain:['Аудитория','Письмо','Пауза','Следующий шаг'], contract:'Договор с клиентом', version:'Версия', review:'На согласовании', agreement:'Условия сотрудничества', approved:'Проверено', approvalNext:'На рассмотрении', legal:'Юрист', manager:'Руководитель', loyalty:'Программа лояльности', balance:'Баланс участника', points:'баллов', reward:'Награда', rewardTitle:'Подарок за баллы', analytics:'Аналитика', topbar:'Карта возможностей LeadDrive: подтверждённые модули CRM', allFeatures:'Все возможности', chaptersLabel:'Разделы продукта', mapEyebrow:'ВСЁ, ЧТО УЖЕ РАБОТАЕТ В LEADDRIVE', map1:'Карта', map2:'продукта.', mapIntro:'Модули сгруппированы по направлениям. Каждый пункт соответствует реальному разделу CRM.', mapDomains:'Направления', domainsTitle:'Направления', indEyebrow:'ОТРАСЛЕВЫЕ СЦЕНАРИИ', ind1:'Разделы под', ind2:'вашу отрасль.', indIntro:'Кроме общих модулей в LeadDrive есть отраслевые разделы: реестры, статусы и таблицы, которые заполняются под ваш процесс.', indSections:'Разделы', indNote:'Отраслевые разделы дают справочники и статусы под отрасль. Поля, процессы и интеграции настраиваются под клиента при внедрении.'
  },
  az: {
    dashGreeting:'Axşamınız xeyir, Leyla!', dashNav:['Zənglər','AI məsləhətçi','Analitika','Sahə agentləri','Hesabatlar','Sövdələşmələr','Tapşırıqlar','Sosial şəbəkələr','Gələnlər','Müştəri dəstəyi'], dashSub:'Biznesin əsas siqnalları və növbəti addımlar bir iş icmalında.', dashAsk:'Məsələn: hansı sövdələr diqqət tələb edir?', dashBrief:'Bu günün fokusu', dashBriefTag:'DA VINCI · İŞ İCMALI', dashLines:['Reaksiya tələb edən SLA pozuntuları: 66.','Hazırda 63 aktiv lid üzərində iş gedir.','Satış xəttində 28 sövdə var, konversiya 77%.'], dashActions:['Yeni lid','Sövdələşmələr','Lövhələr','Təkliflər'], dashDiscuss:'İcmalı Da Vinci ilə müzakirə et', dashCaption:'LeadDrive-ın real ekranı: canlı fon və Da Vinci iş icmalı',
   
    product:'Məhsul',solutions:'Həllər',blog:'Bloq',ai:'AI və Da Vinci',team:'Komanda üçün',plans:'Şərtlər',about:'Haqqımızda',demo:'Demo sorğusu',login:'Daxil ol',skip:'Məzmuna keç',
    eyebrow:'AZƏRBAYCAN DİLİNDƏ. BAKIDA HAZIRLANIB.',hero1:'Diqqət müştəridə.',hero2:'Satışlar nəzarətdə.',intro:'Müraciətlər, sövdələşmələr və ünsiyyət tarixçəsi bir yerdə. AI cavablara və məlumatlara kömək edir, komanda müştəri ilə işi davam etdirir.',explore:'CRM-ə nəzər salın',example:'Nümunə məlumatlar',heroNote:'Hər sövdələşmənin arxasında bir insan var.',heroNote2:'Onun haqqında vacib məlumatlar LeadDrive-da.',clientQuote:'«Komandamız üçün CRM-i müzakirə edək»',newMessage:'Yeni mesaj',
    sales:'Sövdələşmələr',inbox:'Müraciətlər',client:'Müştəri',pipeline:'Satış boru xətti',stages:['İlk maraq','Müzakirə','Təklif'],dealNames:['Caspian Studio','Northline','Aroma Market'],dealDesc:['Komanda üçün CRM','Vahid müştəri tarixçəsi','Satışların avtomatlaşdırılması'],next:['Ehtiyacı dəqiqləşdir','Ssenariləri göstər','Təklifi müzakirə et'],owner:'Məsul şəxs',tomorrow:'Sabah, 11:00',nextStep:'Növbəti addım',task:'CRM nümayişi',all:'Bütün müraciətlər',conversation:'Ünsiyyət tarixçəsi',received:'Salam! Bizə 8 əməkdaş üçün CRM lazımdır.',reply:'Salam, Leyla! Müraciətlərlə hazırda necə işlədiyinizi danışa bilərsiniz?',note:'Müştəri 8 nəfərlik komanda üçün CRM seçir.',contact:'Leyla Məmmədova',company:'Şirkət',need:'Ehtiyac',needText:'Müraciətləri və sövdələşmələri bir yerdə toplamaq',activity:'Son fəaliyyət',activityText:'Komandanın ehtiyaclarını müzakirə etdik',channel:'Müraciət kanalı',
    coreEyebrow:'VAHİD TARİXÇƏ. BÜTÜN KOMANDA.',core1:'İlk maraqdan',core2:'uzunmüddətli əməkdaşlığa.',coreIntro:'Satış, ünsiyyət və marketinq eyni müştəri ilə işləyir. Şöbələr arasında məlumat itmir.',
    modules:[{id:'sales',title:'Satış',subtitle:'Sövdələşmənin mərhələsi və növbəti addım aydındır.',description:'Lidlər, satış boru xətti və təkliflər razılaşmalarla bir yerdə. Hər sövdələşmənin mərhələsi, məsul şəxsi və növbəti addımı var.',tags:['Lidlər və qiymətləndirmə','Satış boru xətləri','Kommersiya təklifləri']},{id:'clients',title:'Müştərilər və ünsiyyət',subtitle:'Bildiklərinizdən başlayın.',description:'Şirkətlər, kontaktlar, yazışmalar və fəaliyyətlər vahid tarixçədə. Həmkarınız söhbəti məlumatlı şəkildə davam etdirə bilər.',tags:['Müştəri kartı','Ümumi Inbox','Hazır cavablar']},{id:'marketing',title:'Marketinq',subtitle:'Doğru mesaj, uyğun auditoriya.',description:'Kontaktları seqmentlərdə birləşdirin, kampaniyalar və əlaqə ssenariləri hazırlayın. Sorğular və NPS ilə rəyləri öyrənin.',tags:['Seqmentlər','Kampaniyalar və ssenarilər','Tədbirlər və NPS']},{id:'contracts',title:'Müqavilələr',subtitle:'Razılaşmalar sənədə çevrilir.',description:'Sənədlər, versiyalar və təsdiq mərhələləri müştəri ilə əlaqələndirilir. Komanda müqavilə üzərində bir yerdə işləyir.',tags:['Müqavilə reyestri','Versiya tarixçəsi','Təsdiq prosesi']},{id:'loyalty',title:'Loyallıq',subtitle:'Yenidən qayıtmaq üçün səbəb.',description:'Səviyyələr, xal qazanma qaydaları və mükafatlarla loyallıq proqramı qurun. İştirakçının tarixçəsində xal hərəkətlərini izləyin.',tags:['Səviyyələr və qaydalar','Mükafatlar','Xal tarixçəsi']}],
    teamEyebrow:'TEXNOLOGİYA KÖMƏK EDİR. İNSANLAR QƏRAR VERİR.',team1:'Daha az məlumat axtarışı.',team2:'Daha çox birgə iş.',teamText:'Menecerə razılaşmalar, rəhbərə satışların mənzərəsi, marketinqə müştəri tarixçəsi. Hər kəsin öz rolu, komandanın ortaq məlumatı var.',teamLink:'İmkanlara baxın',teamCaption:'Yaxşı iş bir-birini anlamaqdan başlayır.',
    aiEyebrow:'CRM-İNİZDƏ AI-NİN İKİ ROLU',ai1:'Lazım olan yerdə',ai2:'lazım olan kömək.',aiIntro:'Müştəri ilə söhbətdə və komandanın gündəlik qərarlarında.',agent:'AI agent',davinci:'Da Vinci',agentTag:'MÜŞTƏRİ İLƏ SÖHBƏTDƏ',davinciTag:'ƏMƏKDAŞIN YANINDA',agentTitle:'Cavab verir. Dəqiqləşdirir. Məlumatı ötürür.',davinciTitle:'Görür. İzah edir. Təklif edir.',agentText:'Hər kanal üçün kimin cavab verdiyini seçin: insan, AI qaralaması və ya AI agent. Persona, bilik bazası və operatora ötürmə üçün açar sözlər CRM-də tənzimlənir.',davinciText:'Müştərilər və sövdələşmələr üzrə siqnalları araşdırın, izahları görün və uyğun növbəti addımı seçin.',illustrative:'Ssenari nümunəsi',stepLabels:['Mesaj','Məlumat','Növbəti addım'],dvStepLabels:['Siqnal','İzah','Qərar'],play:'Ssenarini göstər',pause:'Dayandır',replay:'Yenidən göstər',agentCards:[{label:'Müştəri',title:'«Bizə 8 əməkdaş üçün CRM lazımdır»',text:'Ümumi Inbox-da yeni söhbət.'},{label:'Söhbətin məzmunu',title:'Müraciətlər yazışmalarda itir',text:'Komandaya vahid tarixçə və məsul şəxslər lazımdır.'},{label:'Menecerə',title:'Leyla ilə söhbəti davam etdirin',text:'Müraciətlərin toplanmasını və satış prosesini müzakirə edin.'}],dvCards:[{label:'Sövdələşmə üzrə siqnal',title:'Uzun müddətdir fəaliyyət yoxdur',text:'Tarixçədə yeni addım görünmür.'},{label:'Məlumat',title:'Təklif artıq müzakirə edilib',text:'Yenidən əlaqə saxlamazdan əvvəl razılaşmaları yoxlayın.'},{label:'Əməkdaşın qərarı',title:'Növbəti söhbəti razılaşdırın',text:'Tövsiyəni araşdırın və uyğun hərəkəti təsdiqləyin.'}],decision:'Qərar və nəzarət komandada qalır.',channelsTitle:'Söhbətlər burada birləşir.',channelsText:'Lazım olan kanalları ümumi Inbox-a qoşun. Bağlantıların tərkibi və qurulması iş prosesinizə uyğun seçilir.',
    insightEyebrow:'SATIŞLARIN ÜMUMİ MƏNZƏRƏSİ',insight1:'Harada olduğunuzu bilin.',insight2:'Növbəti addımı görün.',insightText:'Satış boru xəttini, müştəri aktivliyini və ünsiyyəti izləyin. Nəyə diqqət ayıracağınızı seçmək üçün Da Vinci siqnallarından istifadə edin.',overview:'İcmal',pipelineLabel:'Mərhələlər üzrə sövdələşmələr',signals:'Diqqət tələb edir',signalText:'Növbəti addımı olmayan sövdələşmələr',clientActivity:'Müştəri aktivliyi',currentWeek:'Bu həftə',
    startEyebrow:'BİZNESİNİZDƏN BAŞLAYAQ',startTitle:'Sizin ssenarilərinizlə göstərək.',startText:'Müraciətlərin haradan gəldiyini, müştərilərlə kimin işlədiyini və nəyi yaxşılaşdırmaq istədiyinizi danışın. Demoda LeadDrive-da uyğun prosesi göstərək.',steps:[['Ehtiyaclarınız','İlk müraciətdən satışa qədər prosesi müzakirə edək.'],['Ssenariniz','CRM-də lazım olan hərəkətləri və əlaqələri göstərək.'],['Növbəti addımınız','Qurulacaq imkanları və işə başlama planını razılaşdıraq.']],faqTitle:'Başlamazdan əvvəl',questions:[['AI agent Da Vinci-dən nə ilə fərqlənir?','AI agent müştəri ilə dialoqda müəyyən edilmiş qaydalara uyğun işləyir. Da Vinci isə əməkdaşa CRM daxilində siqnalları, məlumatları və hərəkət təkliflərini araşdırmağa kömək edir.'],['Hansı kanalları qoşmaq olar?','Kataloqda WhatsApp Business, Telegram, email, SMS, Facebook Messenger, Instagram və Chatwoot vasitəsilə TikTok var. Demoda sizə lazım olan provayderlərin giriş və quraşdırma şərtlərini dəqiqləşdirək.'],['Məlumatlar cədvəldədirsə, başlaya bilərik?','Bəli, əvvəlcə kontaktlarınızı, şirkətləri və sövdələşmələri nəzərdən keçirək. Köçürüləcək məlumatların tərkibini, keyfiyyətini və şərtlərini mövcud fayllarınıza əsasən razılaşdıraq.'],['Azərbaycanda biznes üçün hansı CRM həlli uyğundur?','LeadDrive — Bakı və bütün Azərbaycan üzrə şirkətlər üçün CRM sistemi: Azərbaycan, rus və ingilis dilində interfeys, WhatsApp və Instagram ümumi Inbox-da, müqavilələr, AZN ilə fakturalar və dəstək. Satış, servis, sahə komandaları və sahə ssenariləri üçün uyğundur.'],['LeadDrive digər CRM sistemlərindən nə ilə fərqlənir?','Ayrı-ayrı alətlər toplusu əvəzinə bir iş məkanı: satış, ünsiyyət, müqavilələr, maliyyə, dəstək və AI köməkçiləri bir müştəri kartına bağlıdır. Bu saytda təsvir olunan hər şey sistemin real ekranlarında yoxlanılıb.'],['Bu nə qədərdir?','Sabit tariflər yoxdur. Komandanız və tapşırıqlarınız barədə WhatsApp-da və ya demoda danışın, sizə uyğun imkanlar tərkibini və şərtləri təklif edək.']],
    footerEyebrow:'LEADDRIVE CRM',footer1:'Sizin müştərinizdən',footer2:'başlayaq.',footerText:'Bir söhbətlə LeadDrive-ın komandanızın işinə necə uyğunlaşdığını görün.',footerDemo:'Ehtiyacımı müzakirə edək',copyright:'İnsanlarla işləmək üçün yaradılıb.',segment:'Auditoriya seqmenti',segmentName:'Yeni məhsula maraq',contacts:'kontakt',campaign:'Kampaniya',campaignName:'Təqdimata dəvət',chain:['Auditoriya','Məktub','Fasilə','Növbəti addım'],contract:'Müştəri müqaviləsi',version:'Versiya',review:'Təsdiq prosesində',agreement:'Əməkdaşlıq şərtləri',approved:'Yoxlanılıb',approvalNext:'Baxılır',legal:'Hüquqşünas',manager:'Rəhbər',loyalty:'Loyallıq proqramı',balance:'İştirakçının balansı',points:'xal',reward:'Mükafat',rewardTitle:'Xallarla hədiyyə',analytics:'Analitika', topbar:'LeadDrive imkanlar xəritəsi: təsdiqlənmiş CRM modulları', allFeatures:'Bütün imkanlar', chaptersLabel:'Məhsul bölmələri', mapEyebrow:'LEADDRIVE-DA ARTIQ İŞLƏYƏNLƏR', map1:'Məhsul', map2:'xəritəsi.', mapIntro:'Modullar istiqamətlər üzrə qruplaşdırılıb. Hər bənd CRM-in real bölməsinə uyğundur.', mapDomains:'İstiqamətlər', domainsTitle:'İstiqamətlər', indEyebrow:'SAHƏ SSENARİLƏRİ', ind1:'Sahənizə uyğun', ind2:'bölmələr.', indIntro:'Ümumi modullardan əlavə LeadDrive-da sahə bölmələri var: prosesinizə uyğun doldurulan reyestrlər, statuslar və cədvəllər.', indSections:'Bölmələr', indNote:'Sahə bölmələri sahəyə uyğun soraqçalar və statuslar verir. Sahələr, proseslər və inteqrasiyalar tətbiq zamanı müştəriyə uyğunlaşdırılır.'
  },
  en: {
    dashGreeting:'Good evening, Leyla!', dashNav:['Calls','AI advisor','Analytics','Field agents','Reports','Deals','Tasks','Social','Inbox','Customer support'], dashSub:'The key business signals and the next steps in a single brief.', dashAsk:'For example: which deals need attention?', dashBrief:'Focus of the day', dashBriefTag:'DA VINCI · BRIEF', dashLines:['SLA breaches that need a response: 66.','63 active leads are in progress right now.','28 deals in the pipeline, 77% conversion.'], dashActions:['New lead','Deals','Boards','Quotes'], dashDiscuss:'Discuss the brief with Da Vinci', dashCaption:'A real LeadDrive screen: live wallpaper and the Da Vinci brief',
   
    product:'Product', solutions:'Solutions', blog:'Blog', ai:'AI and Da Vinci', team:'For teams', plans:'Terms', about:'About', demo:'Request a demo', login:'Sign in', skip:'Skip to content',
    eyebrow:'IN AZERBAIJANI. MADE IN BAKU.', hero1:'The customer at the centre.', hero2:'Sales under control.', intro:'Requests, deals and relationship history side by side. AI helps with replies and data while the team keeps working with the customer.', explore:'Look inside the CRM',
    example:'Demo data', heroNote:'Behind every deal is a person.', heroNote2:'Everything that matters about them is in LeadDrive.', clientQuote:'“Let’s discuss a CRM for our team”', newMessage:'New message',
    sales:'Deals', inbox:'Requests', client:'Customer', pipeline:'Sales pipeline', stages:['New interest','Discussion','Proposal'], dealNames:['Caspian Studio','Northline','Aroma Market'], dealDesc:['CRM for the team','One customer history','Sales automation'], next:['Clarify tasks','Show scenarios','Discuss the proposal'], owner:'Owner', tomorrow:'Tomorrow, 11:00', nextStep:'Next step', task:'CRM demo', all:'All requests', conversation:'Conversation history', received:'Hello! We need a CRM for 8 people.', reply:'Hello, Leyla! Tell me how you handle requests today.', note:'The customer is choosing a CRM for a team of 8.', contact:'Leyla Mammadova', company:'Company', need:'Need', needText:'Bring requests and deals into one place', activity:'Last activity', activityText:'Discussed the team’s tasks', channel:'Channel',
    coreEyebrow:'ONE HISTORY. THE WHOLE TEAM.', core1:'From the first interest', core2:'to a long relationship.', coreIntro:'Sales, communication and marketing work with the same customer. No context lost between departments.',
    modules:[
      {id:'sales',title:'Sales',subtitle:'See where the deal is and what comes next.',description:'Leads, pipeline and quotes next to the agreements. Every deal has its stage, owner and next step.',tags:['Leads and qualification','Sales pipelines','Quotes']},
      {id:'clients',title:'Customers and communication',subtitle:'Start with what you already know.',description:'Companies, contacts, conversations and activities in one shared history. A colleague can continue the conversation with context.',tags:['Customer card','Shared inbox','Quick replies']},
      {id:'marketing',title:'Marketing',subtitle:'The right message for your audience.',description:'Group contacts into segments, prepare campaigns and touch sequences. Learn from feedback through surveys and NPS.',tags:['Segments','Campaigns and journeys','Events and NPS']},
      {id:'contracts',title:'Contracts',subtitle:'Agreements take shape.',description:'Documents, versions and approval stages are linked to the customer. The team has one place to work on a contract.',tags:['Contract registry','Version history','Approval']},
      {id:'loyalty',title:'Loyalty',subtitle:'Give them a reason to come back.',description:'Tiers, earning rules and rewards help build a loyalty programme. A member’s history shows how points move.',tags:['Tiers and rules','Rewards','Point history']},
    ],
    teamEyebrow:'TECHNOLOGY HELPS. PEOPLE DECIDE.', team1:'Less “forward it to me”.', team2:'More working together.', teamText:'Agreements for the manager. The sales picture for the leader. Customer history for marketing. Everyone has a role, the team has shared context.', teamLink:'See what it can do', teamCaption:'Good work starts with understanding.',
    aiEyebrow:'TWO ROLES OF AI IN YOUR CRM', ai1:'Help where', ai2:'it is needed.', aiIntro:'In the conversation with the customer and in the team’s daily decisions.', agent:'AI agent', davinci:'Da Vinci', agentTag:'IN THE CUSTOMER DIALOGUE', davinciTag:'NEXT TO THE EMPLOYEE', agentTitle:'Replies. Clarifies. Passes on context.', davinciTitle:'Notices. Explains. Suggests.', agentText:'For each channel choose who replies: a person, an AI draft or an AI agent. The persona, knowledge base and hand-off keywords are configured in the CRM.', davinciText:'Study signals on customers and deals, read the explanations and pick the right next step.', illustrative:'Illustrative scenario', stepLabels:['Message','Context','Next step'], dvStepLabels:['Signal','Explanation','Decision'], play:'Play the scenario', pause:'Pause', replay:'Replay',
    agentCards:[{label:'Customer',title:'“We need a CRM for 8 people”',text:'A new conversation in the shared inbox.'},{label:'Conversation context',title:'Requests get lost in chats',text:'The team needs a shared history and owners.'},{label:'For the manager',title:'Continue the conversation with Leyla',text:'Discuss collecting requests and working with deals.'}],
    dvCards:[{label:'Deal signal',title:'No activity for a while',text:'The deal has no new step in its history.'},{label:'Context',title:'The proposal was already discussed',text:'Check the agreements before the next touch.'},{label:'Employee decision',title:'Agree the next conversation',text:'Review the recommendation and confirm the right action.'}],
    decision:'Decisions and control stay with the team.', channelsTitle:'Conversations meet here.', channelsText:'Connect the channels you need to the shared inbox. Which ones and how depends on your process.',
    insightEyebrow:'THE BIG PICTURE OF SALES', insight1:'Know where you are.', insight2:'See where to go.', insightText:'Look at the pipeline, customer activity and communications. Use Da Vinci signals to decide what deserves attention.', overview:'Overview', pipelineLabel:'Deals by stage', signals:'Needs attention', signalText:'Deals without a next step', clientActivity:'Customer activity', currentWeek:'This week',
    startEyebrow:'LET’S START WITH YOUR BUSINESS', startTitle:'We’ll show it on your scenarios.', startText:'Tell us how requests come in, who works with customers and what you want to improve. On the demo we’ll map the right path in LeadDrive.', steps:[['Your tasks','We discuss the process from the first request to the deal.'],['Your scenario','We show the actions and links you need in the CRM.'],['Your next step','We agree the setup scope and the launch plan.']],
    faqTitle:'Before you start', questions:[['How is the AI agent different from Da Vinci?','The AI agent talks to the customer by the rules you set. Da Vinci helps the employee read signals, context and suggested actions inside the CRM.'],['Which channels can be connected?','The catalogue includes WhatsApp Business, Telegram, email, SMS, Facebook Messenger, Instagram and TikTok via Chatwoot. On the demo we confirm access and setup for the providers you need.'],['Can we start from data in spreadsheets?','Yes. We start by reviewing your contacts, companies and deals. Scope, quality and migration terms are agreed on your source data.'],['Which CRM solution fits a business in Azerbaijan?','LeadDrive is a CRM system for companies in Baku and across Azerbaijan: interface in Azerbaijani, Russian and English, WhatsApp and Instagram in a shared inbox, contracts, invoices in AZN and support. It suits sales, service, field teams and industry scenarios.'],['How is LeadDrive different from other CRM systems?','One workspace instead of a set of separate tools: sales, communications, contracts, finance, support and AI assistants are linked to a single customer card. Everything described on this site was verified on real screens of the system.'],['How much does it cost?','There is no fixed price list. Tell us about your team and tasks on WhatsApp or at the demo, and we will propose a feature set and terms for you.']],
    footerEyebrow:'LEADDRIVE CRM', footer1:'Let’s start', footer2:'with your customer.', footerText:'One conversation to see how LeadDrive fits into your team’s work.', footerDemo:'Discuss my task', copyright:'Built for working with people.',
    segment:'Audience segment', segmentName:'Interest in the new product', contacts:'contacts', campaign:'Campaign', campaignName:'Invitation to the presentation', chain:['Audience','Email','Pause','Next step'], contract:'Customer contract', version:'Version', review:'In approval', agreement:'Terms of cooperation', approved:'Reviewed', approvalNext:'Under review', legal:'Legal', manager:'Head', loyalty:'Loyalty programme', balance:'Member balance', points:'points', reward:'Reward', rewardTitle:'Gift for points', analytics:'Analytics', topbar:'LeadDrive capability map: confirmed CRM modules', allFeatures:'All capabilities', chaptersLabel:'Product sections', mapEyebrow:'EVERYTHING ALREADY WORKING IN LEADDRIVE', map1:'Product', map2:'map.', mapIntro:'Modules are grouped by area. Every item matches a real section of the CRM.', mapDomains:'Areas', domainsTitle:'Areas', indEyebrow:'INDUSTRY SCENARIOS', ind1:'Sections for', ind2:'your industry.', indIntro:'Besides the shared modules, LeadDrive has industry sections: registries, statuses and tables filled in for your process.', indSections:'Sections', indNote:'Industry sections provide reference data and statuses for the industry. Fields, processes and integrations are configured for the customer during implementation.'
  }
};
export type Copy = typeof TEXT.ru;
const ICONS = [BriefcaseBusiness, Users, Target, FileText, Gift];
const DASH_ICONS=[Phone,Sparkles,BarChart3,MapPin,FileText,BriefcaseBusiness,CheckCheck,Share2,Mail,MessageCircle]
function DashboardShot({t}:{t:Copy}) { return <div className="dash-shot"><video className="dash-video" autoPlay muted loop playsInline preload="metadata" aria-hidden="true" tabIndex={-1}><source src="/wallpapers/alpine-v4.mp4" type="video/mp4"/></video><aside className="dash-side"><div className="dash-brand"><Brand/></div><div className="dash-search"><Search size={13}/><span/></div><nav>{t.dashNav.map((label,i)=>{const Icon=DASH_ICONS[i];return <span key={label} className={i===5?'is-active':undefined}><Icon size={15}/>{label}</span>})}</nav></aside><div className="dash-main"><div className="dash-top"><span className="dash-pill"><Search size={12}/></span><span className="dash-pill dash-pill-apps">{t.explore}</span><span className="dash-avatar">L</span></div><div className="dash-body"><div className="dash-greeting"><h3>{t.dashGreeting}</h3><p>{t.dashSub}</p><div className="dash-ask"><Sparkles size={15}/><span>{t.dashAsk}</span><i className="dash-caret"/><b><ArrowUpRight size={14}/></b></div><div className="dash-actions">{t.dashActions.map((a,i)=><span key={a} className={i===0?'is-primary':undefined}>{a}</span>)}</div></div><div className="dash-brief"><span className="dash-brief-tag">{t.dashBriefTag}</span><strong>{t.dashBrief}</strong><ul>{t.dashLines.map((line,i)=><li key={line} style={{animationDelay:`${.5+i*.7}s`}}><em>{String(i+1).padStart(2,'0')}</em>{line}</li>)}</ul><span className="dash-brief-link">{t.dashDiscuss}<ArrowRight size={13}/></span></div></div></div></div> }
function ProductScene({t}:{t:Copy}) { return <div className="product-scene" id="product"><DashboardShot t={t}/><div className="product-caption"><span>{t.dashCaption}</span><a href="#possibilities">{t.product}<ArrowDown size={17}/></a></div></div> }
function Brand({light=false}:{light?:boolean}) { return <span className={`brand ${light?'brand-light':''}`}><Image unoptimized src="/favicon.svg" width="32" height="32" alt=""/><b>LeadDrive</b></span> }
export function Cta({children,light=false}:{children:React.ReactNode,light?:boolean}) { return <a href={DEMO} target="_blank" rel="noopener" className={`cta ${light?'cta-light':''}`}>{children}<span><ArrowUpRight size={19}/></span></a> }
function Avatar({name='ЛМ',tone='peach'}:{name?:string,tone?:string}) { return <span className={`avatar ${tone}`}>{name}</span> }
export function Header({t,lang,setLang,onModuleSelect,base='',langHref}:{t:Copy,lang:Lang,setLang:(l:Lang)=>void,onModuleSelect:(id:string)=>void,base?:string,langHref?:(l:Lang)=>string}) {
 const[mobile,setMobile]=useState(false);const[nav,setNav]=useState<string|null>(null);
 return <><a className="topbar" href={`${base}#product-map`}><span>{t.topbar}</span><ArrowRight size={15}/></a><header className="header"><a href={`${base}#top`} aria-label="LeadDrive"><Brand/></a><nav className="desktop-nav" aria-label={t.product}><NavigationMenu value={nav} onValueChange={value=>setNav(value as string|null)}><NavigationMenuList><NavigationMenuItem value="product"><NavigationMenuTrigger className="nav-trigger">{t.product}</NavigationMenuTrigger><NavigationMenuContent className="mega"><div className="mega-intro"><span>LeadDrive CRM</span><strong>{t.hero1}<br/>{t.hero2}</strong><NavigationMenuLink href={`${base}#product`} onClick={()=>setNav(null)}>{t.explore}<ArrowRight/></NavigationMenuLink></div><div className="mega-links">{t.modules.map((m,i)=>{const Icon=ICONS[i];return <NavigationMenuLink href={`${base}#possibilities`} onClick={()=>{onModuleSelect(m.id);setNav(null)}} key={m.id}><Icon size={21}/><span>{m.title}</span><ArrowUpRight size={17}/></NavigationMenuLink>})}<NavigationMenuLink href={`${base}#product-map`} className="mega-all" onClick={()=>setNav(null)}><span>{t.allFeatures}</span><ArrowRight size={17}/></NavigationMenuLink></div></NavigationMenuContent></NavigationMenuItem></NavigationMenuList></NavigationMenu><a href={hubPath(lang)}>{t.solutions}</a><a href={blogPath(lang)}>{t.blog}</a><a href={`${base}#ai-agent`}>{t.ai}</a><a href={`${base}#team`}>{t.team}</a><a href={`${langPrefix(lang)}/terms`}>{t.plans}</a></nav><div className="header-right"><nav className="language" aria-label="Language">{(['az','ru','en'] as Lang[]).map(l=><a key={l} href={langHref?langHref(l):PATHS[l]} hrefLang={l} className={l===lang?'active':''} onClick={langHref?undefined:e=>{e.preventDefault();setLang(l)}}>{l.toUpperCase()}</a>)}</nav><a className="login" href="https://app.leaddrivecrm.org/">{t.login}</a><a className="header-demo" href={DEMO}>{t.demo}<ArrowUpRight size={16}/></a><button className="menu-toggle" aria-label={mobile?(lang==='ru'?'Закрыть меню':'Menyunu bağla'):(lang==='ru'?'Открыть меню':'Menyunu aç')} aria-expanded={mobile} aria-controls="mobile-nav" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></div>{mobile&&<nav className="mobile-nav" id="mobile-nav"><a onClick={()=>setMobile(false)} href={`${base}#product`}>{t.product}</a><a onClick={()=>setMobile(false)} href={`${base}#product-map`}>{t.allFeatures}</a><a onClick={()=>setMobile(false)} href={hubPath(lang)}>{t.solutions}</a><a onClick={()=>setMobile(false)} href={blogPath(lang)}>{t.blog}</a><a onClick={()=>setMobile(false)} href={`${base}#ai-agent`}>{t.ai}</a><a onClick={()=>setMobile(false)} href={`${base}#team`}>{t.team}</a><a onClick={()=>setMobile(false)} href={`${langPrefix(lang)}/terms`}>{t.plans}</a><a onClick={()=>setMobile(false)} href={DEMO}>{t.demo}<ArrowUpRight/></a></nav>}</header></>
}
function SalesBoard({t,compact=false}:{t:Copy,compact?:boolean}) { return <div className={`sales-board ${compact?'compact':''}`}><div className="board-top"><div><span className="ui-overline">Caspian Studio</span><h3>{t.pipeline}</h3></div><span className="board-filter"><SlidersHorizontal size={15}/>{t.overview}</span></div><div className="deal-columns">{t.stages.map((stage,i)=><div className="deal-column" key={stage}><div className="column-heading"><i/><span>{stage}</span><small>{[2,2,1][i]}</small></div><article className="deal-card"><Avatar name={['CS','N','AM'][i]} tone={['peach','blue','mint'][i]}/><h4>{t.dealNames[i]}</h4><p>{t.dealDesc[i]}</p><div className="deal-divider"/><span className="deal-action"><Clock3 size={13}/>{t.next[i]}</span><div className="deal-owner"><span>{t.owner}</span><Avatar name={i===1?'KA':'AY'} tone="lilac"/></div></article>{i!==2&&<div className="secondary-deal"><span className="small-dot"/><span>{i===0?'Atlas Design':'Greenline'}</span><ChevronRight size={14}/></div>}</div>)}</div><div className="board-next"><CalendarDays size={19}/><div><small>{t.nextStep}</small><strong>{t.task}</strong></div><span>{t.tomorrow}</span><ArrowUpRight size={18}/></div></div> }
function ClientDemo({t}:{t:Copy}) { return <div className="client-demo"><div className="client-profile"><Avatar name="LM"/><span><h3>{t.contact}</h3><p>Caspian Studio</p></span><span className="profile-label">CRM</span></div><dl><div><dt>{t.company}</dt><dd>Caspian Studio</dd></div><div><dt>{t.channel}</dt><dd>WhatsApp</dd></div><div><dt>{t.owner}</dt><dd>Aysel</dd></div><div><dt>{t.need}</dt><dd>{t.needText}</dd></div></dl><div className="client-timeline"><span><Check size={16}/></span><div><small>{t.activity}</small><strong>{t.activityText}</strong><p>{t.note}</p></div></div></div> }
function MarketingDemo({t}:{t:Copy}) { return <div className="marketing-demo"><div className="segment-card"><span className="round-icon"><Target/></span><div><small>{t.segment}</small><h3>{t.segmentName}</h3></div><strong>128<small>{t.contacts}</small></strong></div><div className="journey-line" aria-hidden="true"/><div className="campaign-card"><span className="ui-overline">{t.campaign}</span><h3>{t.campaignName}</h3><div className="campaign-art"><Mail size={36}/><span>LeadDrive</span><strong>{t.newMessage}</strong></div><div className="journey-steps">{t.chain.map((s,i)=><span key={s}><i>{i+1}</i>{s}</span>)}</div></div></div> }
function ContractDemo({t}:{t:Copy}) { return <div className="contract-demo"><div className="document-paper"><div><FileText size={23}/><span>{t.version} 3</span></div><small>{t.contract}</small><h3>Caspian Studio</h3><h4>{t.agreement}</h4><div className="document-lines" aria-hidden="true"><i/><i/><i/><i/></div><span className="document-state"><Clock3 size={15}/>{t.review}</span></div><div className="approval-list"><div><span className="approval-check"><Check size={16}/></span><span>{t.legal}<small>{t.approved}</small></span><Avatar name="NR"/></div><div><span className="approval-clock"><Clock3 size={16}/></span><span>{t.manager}<small>{t.approvalNext}</small></span><Avatar name="EK" tone="mint"/></div></div></div> }
function LoyaltyDemo({t}:{t:Copy}) { return <div className="loyalty-demo"><div className="membership"><span>{t.loyalty}<span>Silver</span></span><div className="membership-brand">LeadDrive<span>loyalty</span></div><small>{t.balance}</small><strong>1 250 <small>{t.points}</small></strong><div className="member-bottom"><span>{t.contact}</span><Gift size={26}/></div></div><div className="reward-card"><span><Gift size={25}/></span><div><small>{t.reward}</small><strong>{t.rewardTitle}</strong></div><b>500<small>{t.points}</small></b></div></div> }
function Core({t,active,setActive}:{t:Copy,active:string,setActive:(id:string)=>void}) {return <section className="core-section wrap" id="possibilities"><div className="section-heading"><div><span className="eyebrow">{t.coreEyebrow}</span><TypedH2 a={t.core1} b={t.core2}/></div><p>{t.coreIntro}</p></div><Tabs value={active} onValueChange={v=>setActive(String(v))} className="feature-tabs"><TabsList aria-label={t.product}>{t.modules.map((m,i)=>{const Icon=ICONS[i];return <TabsTrigger value={m.id} key={m.id}><Icon size={19}/>{m.title}</TabsTrigger>})}</TabsList>{t.modules.map((m,i)=><TabsContent value={m.id} key={m.id} id={m.id==='sales'?'sales-details':m.id}><div className="feature-copy"><span className="section-number">{m.title}</span><h3>{m.subtitle}</h3><p>{m.description}</p><ul>{m.tags.map(tag=><li key={tag}><Check size={17}/>{tag}</li>)}</ul><a href={DEMO} className="text-link">{t.demo}<ArrowUpRight size={19}/></a></div><div className={`feature-visual visual-${m.id}`}><span className="example-label">{t.example}</span>{i===0?<SalesBoard t={t} compact/>:i===1?<ClientDemo t={t}/>:i===2?<MarketingDemo t={t}/>:i===3?<ContractDemo t={t}/>:<LoyaltyDemo t={t}/>}</div></TabsContent>)}</Tabs></section>}
function Team({t}:{t:Copy}) {return <section className="team-section" id="team"><div className="team-copy"><span className="eyebrow">{t.teamEyebrow}</span><TypedH2 a={t.team1} b={t.team2}/><p>{t.teamText}</p><a className="text-link" href="#possibilities">{t.teamLink}<ArrowUpRight size={20}/></a></div><div className="team-image"><Image unoptimized src="/team-work.webp" width="1400" height="933" alt={t.teamCaption} loading="lazy"/><span className="team-image-caption">{t.teamCaption}</span></div></section>}
function Insights({t}:{t:Copy}) {return <section className="insights wrap"><div className="insight-copy"><span className="eyebrow">{t.insightEyebrow}</span><TypedH2 a={t.insight1} b={t.insight2}/><p>{t.insightText}</p><a href="#ai-agent" className="text-link">{t.davinci}<ArrowUpRight size={20}/></a></div><div className="insight-dashboard"><div className="insight-top"><strong>{t.overview}</strong><span>{t.example}</span></div><div className="funnel"><h3>{t.pipelineLabel}</h3>{t.stages.map((s,i)=><div key={s}><span>{s}</span><div><i style={{width:`${[100,66,33][i]}%`}}/><b>{[12,8,4][i]}</b></div></div>)}</div><div className="insight-bottom"><div className="signal-mini"><span><Sparkles size={16}/>{t.signals}</span><b>3</b><p>{t.signalText}</p></div><div className="activity-mini"><span>{t.clientActivity}</span><div className="bar-chart" role="img" aria-label={t.currentWeek}>{[25,52,38,70,46,89,67].map((n,i)=><i key={i} style={{height:`${n}%`}}/>)}</div><small>{t.currentWeek}</small></div></div></div></section>}
function Start({t}:{t:Copy}){return <section className="start wrap" id="start"><div className="section-heading"><div><span className="eyebrow">{t.startEyebrow}</span><TypedH2 a={t.startTitle}/></div><Cta>{t.demo}</Cta></div><p className="start-description">{t.startText}</p><div className="start-steps">{t.steps.map(([title,description],i)=><article key={title}><span>{i+1}</span><div><h3>{title}</h3><p>{description}</p></div></article>)}</div></section>}
function Faq({t}:{t:Copy}) {return <section className="faq wrap"><TypedH2 a={t.faqTitle}/><Accordion className="faq-list" multiple={false}>{t.questions.map(([q,a],i)=><AccordionItem value={i} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>}
export function Footer({t,lang,base=''}:{t:Copy,lang:Lang,base?:string}) {return <footer><div className="footer-main wrap"><div><span className="eyebrow">{t.footerEyebrow}</span><TypedH2 a={t.footer1} b={t.footer2}/></div><div><p>{t.footerText}</p><Cta light>{t.footerDemo}</Cta></div></div><div className="footer-domains wrap"><span>{t.domainsTitle}</span><nav>{publicDomains().map(d=><a key={d.id} href={`${base}#map-${d.id}`}>{d.title[lang]}</a>)}</nav></div><div className="footer-domains footer-solutions wrap" id="solutions"><span>{SOLUTION_LABEL[lang]}</span><nav>{SOLUTIONS.map(s=><a key={s.slug} href={solutionPath(lang,s.slug)}>{s.copy[lang].h1.replace(/[:：]\s*$/,'')}</a>)}</nav></div><div className="footer-bottom wrap"><a href={`${base}#top`}><Brand light/></a><nav><a href={`${base}#product`}>{t.product}</a><a href={hubPath(lang)}>{t.solutions}</a><a href={blogPath(lang)}>{t.blog}</a><a href={`${base}#ai-agent`}>{t.ai}</a><a href={`${langPrefix(lang)}/terms`}>{t.plans}</a><a href={`${base}#team`}>{t.about}</a></nav><span>© LeadDrive 2026</span></div><div className="footer-legal wrap"><nav>{LEGAL_KEYS.map(k=><a key={k} href={`${langPrefix(lang)}${LEGAL_PATH[k]}`}>{LEGAL[k][lang].label}</a>)}</nav><p>{[COMPANY.legalName,COMPANY.brand,COMPANY.taxId&&`VÖEN ${COMPANY.taxId}`,COMPANY.address,COMPANY.city[lang]].filter(Boolean).join(' · ')} · <a href={`mailto:${COMPANY.email}`}>{COMPANY.email}</a> · <a href={COMPANY.phoneHref}>{COMPANY.phone}</a></p></div><div className="footer-wordmark" aria-hidden="true">LeadDrive<span>↗</span></div></footer>}
type ProductTool = {name:string;title:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>Promise<{area:string}>};
function useProductNavigationTool(select:(id:string)=>void){
 useEffect(()=>{
  const context=(document as Document & {modelContext?:{registerTool:(tool:ProductTool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const tool:ProductTool={name:'show_product_area',title:'Explore a LeadDrive product area',description:'Navigate to a product area in this illustrative marketing page. Does not access or change CRM data.',inputSchema:{type:'object',properties:{area:{type:'string',enum:['sales','clients','marketing','contracts','loyalty']}},required:['area'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){
   if(!input||typeof input!=='object'||Object.keys(input).length!==1||!('area' in input)||typeof input.area!=='string'||!['sales','clients','marketing','contracts','loyalty'].includes(input.area))throw new Error('Choose a supported product area.');
   const area=input.area;select(area);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));document.getElementById('possibilities')?.scrollIntoView({block:'start'});return{area};
  }};
  try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional browser capability. */}
  return()=>lifecycle.abort();
 },[select]);
}

export function Home({initialLang}:{initialLang:Lang}){preload('/screens/home.webp',{as:'image',fetchPriority:'low'});const[lang,setLangState]=useState<Lang>(initialLang);const setLang=(l:Lang)=>{setLangState(l);if(typeof history!=='undefined')history.replaceState(null,'',PATHS[l]+location.hash)};const[area,setArea]=useState('sales');useProductNavigationTool(setArea);const t=TEXT[lang];useEffect(()=>{document.documentElement.lang=lang;document.title=pageTitle(lang)},[lang]);return <><a href="#main" className="skip-link">{t.skip}</a><Header t={t} lang={lang} setLang={setLang} onModuleSelect={setArea}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd(lang,t.questions))}}/><main id="main"><section className="hero" id="top"><div className="hero-heading wrap"><div><span className="eyebrow"><span className="brand-dot"/>{t.eyebrow}</span><h1>{t.hero1}<br/><em>{t.hero2}</em></h1></div><div className="hero-intro"><p>{t.intro}</p><Cta>{t.demo}</Cta></div></div><ProductScene t={t}/></section><Pains lang={lang}/><AiPresenter lang={lang} demoHref={DEMO}/><Core t={t} active={area} setActive={setArea}/><Panels lang={lang}/><RealScreens lang={lang}/><Automation lang={lang}/><ProductMap lang={lang} demoHref={DEMO} copy={{eyebrow:t.mapEyebrow,title1:t.map1,title2:t.map2,intro:t.mapIntro,domainsLabel:t.mapDomains,demo:t.demo}}/><Industries lang={lang} copy={{eyebrow:t.indEyebrow,title1:t.ind1,title2:t.ind2,intro:t.indIntro,sectionsLabel:t.indSections,note:t.indNote}}/><Team t={t}/><Insights t={t}/><Trust lang={lang}/><Start t={t}/><Faq t={t}/></main><Footer t={t} lang={lang}/><DemoModal lang={lang}/></>}
