import type { Article } from './articles';

export const ARTICLES_B: Article[] = [
  {
    slug: 'crm-implementation-steps', date: '2026-09-07', solutions: ['sales-crm', 'ai-crm'],
    copy: {
      az: { title: 'CRM tətbiqi: 6 addım və komandanın sistemdən istifadə etməməsinin səbəbləri', description: 'CRM-in şirkətdə tətbiqi addım-addım: proses təsviri, pilot şöbə, məlumat köçürmə, təlim, qaydalar və nəzarət. Tətbiqin uğursuz olmasının beş səbəbi.', keywords: ['CRM tətbiqi', 'CRM keçid', 'CRM təlim', 'CRM qurulması', 'CRM layihəsi'], h1: 'CRM tətbiqi: 6 addım', intro: 'CRM alınır bir gündə, tətbiq olunur aylarla. Fərq — sistemi kimin və necə istifadə edəcəyi əvvəlcədən müəyyən olunubmu. Aşağıdakı ardıcıllıq kiçik və orta şirkətlərdə işləyir.', sections: [
        { h2: '1. Prosesi kağızda təsvir edin', p: ['Müraciət haradan gəlir, kim qəbul edir, nə vaxt lid sövdələşməyə çevrilir, kim faktura kəsir. Bir səhifə kifayətdir. Bu səhifə olmadan CRM parametrləri «gözəyarı» qurulur.'] },
        { h2: '2. Bir şöbə ilə pilot', p: ['Satış və ya dəstək — hansı daha çox ağrıyırsa. 2–4 həftə, 3–5 istifadəçi. Pilotun məqsədi — mərhələləri, sahələri və qaydaları real işdə yoxlamaq.'] },
        { h2: '3. Məlumatları köçürün', p: ['Excel-dən və köhnə sistemdən idxal, dublikatların birləşdirilməsi. Köhnə tarixçəni yükləyin — boş CRM-ə heç kim inanmır.'] },
        { h2: '4. Kanalları qoşun', p: ['WhatsApp, Instagram, telefoniya, e-poçt. Kanal qoşulmayana qədər əməkdaşlar yazışmanı telefonda davam etdirəcək.'] },
        { h2: '5. Üç qayda təyin edin', list: ['Hər lidin məsul şəxsi və növbəti addımı var.', 'Müştəri ilə hər əlaqə CRM-də qeyd olunur (kanal qoşulubsa, avtomatik).', 'CRM-də olmayan iş — olmayıb.'] },
        { h2: '6. Həftəlik nəzarət', p: ['Rəhbər həftədə bir dəfə pipeline-ı, cavab müddətini və «ilişmiş» sövdələşmələri baxır. Sonra avtomatlaşdırma və AI ssenariləri qoşulur — əvvəlcə «yoxla» rejimində.'] },
        { h2: 'Tətbiq niyə uğursuz olur', list: ['Rəhbər özü CRM-ə girmir.', 'Sistem prosesə deyil, proses sistemə uyğunlaşdırılır — çox mürəkkəb formalar.', 'Kanallar qoşulmayıb, məlumat əl ilə daxil edilir.', 'Təlim bir dəfə keçirilib, yeni əməkdaşlara heç kim göstərmir.', 'Nəticə ölçülmür, ona görə də «faydası» görünmür.'] },
      ] },
      ru: { title: 'Внедрение CRM: 6 шагов и почему команда не пользуется системой', description: 'Внедрение CRM в компании по шагам: описание процесса, пилотный отдел, перенос данных, обучение, правила и контроль. Пять причин, по которым внедрение проваливается.', keywords: ['внедрение CRM', 'переход на CRM', 'обучение CRM', 'настройка CRM', 'проект CRM'], h1: 'Внедрение CRM: 6 шагов', intro: 'CRM покупается за день, а внедряется месяцами. Разница в том, определено ли заранее, кто и как будет пользоваться системой. Последовательность ниже работает в малых и средних компаниях.', sections: [
        { h2: '1. Опишите процесс на бумаге', p: ['Откуда приходит обращение, кто принимает, когда лид становится сделкой, кто выставляет счёт. Достаточно одной страницы. Без неё настройки CRM делаются «на глаз».'] },
        { h2: '2. Пилот в одном отделе', p: ['Продажи или поддержка — где больнее. 2–4 недели, 3–5 пользователей. Цель пилота — проверить стадии, поля и правила на реальной работе.'] },
        { h2: '3. Перенесите данные', p: ['Импорт из Excel и старой системы, объединение дубликатов. Загрузите старую историю — пустой CRM никто не доверяет.'] },
        { h2: '4. Подключите каналы', p: ['WhatsApp, Instagram, телефония, почта. Пока канал не подключён, сотрудники продолжат переписку в телефоне.'] },
        { h2: '5. Установите три правила', list: ['У каждого лида есть ответственный и следующий шаг.', 'Каждый контакт с клиентом фиксируется в CRM (автоматически, если канал подключён).', 'Работы, которой нет в CRM, не было.'] },
        { h2: '6. Еженедельный контроль', p: ['Руководитель раз в неделю смотрит воронку, время ответа и «застрявшие» сделки. Затем подключаются автоматизация и AI-сценарии — сначала в режиме «проверка».'] },
        { h2: 'Почему внедрение проваливается', list: ['Руководитель сам не заходит в CRM.', 'Процесс подгоняют под систему, а не систему под процесс — слишком сложные формы.', 'Каналы не подключены, данные вносятся вручную.', 'Обучение провели один раз, новым сотрудникам никто не показывает.', 'Результат не измеряется, поэтому «пользы» не видно.'] },
      ] },
      en: { title: 'CRM implementation: 6 steps and why teams stop using the system', description: 'Implementing a CRM in a company step by step: process description, a pilot department, data migration, training, rules and control. Five reasons implementations fail.', keywords: ['CRM implementation', 'moving to a CRM', 'CRM training', 'CRM setup', 'CRM project'], h1: 'CRM implementation: 6 steps', intro: 'A CRM is bought in a day and implemented over months. The difference is whether it was decided in advance who will use the system and how. The sequence below works in small and medium companies.', sections: [
        { h2: '1. Describe the process on paper', p: ['Where a request comes from, who takes it, when a lead becomes a deal, who issues the invoice. One page is enough. Without it the CRM is configured “by eye”.'] },
        { h2: '2. Pilot in one department', p: ['Sales or support, whichever hurts more. 2–4 weeks, 3–5 users. The goal of the pilot is to test stages, fields and rules on real work.'] },
        { h2: '3. Migrate the data', p: ['Import from Excel and the old system, merge duplicates. Load the old history; nobody trusts an empty CRM.'] },
        { h2: '4. Connect the channels', p: ['WhatsApp, Instagram, telephony, email. Until a channel is connected, employees will keep chatting on their phones.'] },
        { h2: '5. Set three rules', list: ['Every lead has an owner and a next step.', 'Every contact with a customer is recorded in the CRM (automatically if the channel is connected).', 'Work that is not in the CRM did not happen.'] },
        { h2: '6. Weekly control', p: ['Once a week the manager looks at the funnel, response time and “stuck” deals. Then automation and AI scenarios are switched on, first in review mode.'] },
        { h2: 'Why implementations fail', list: ['The owner never opens the CRM.', 'The process is bent to the system instead of the system to the process; forms are too complex.', 'Channels are not connected; data is typed by hand.', 'Training was done once; nobody shows new employees.', 'Results are not measured, so the “benefit” is invisible.'] },
      ] },
    },
  },
  {
    slug: 'ai-in-crm', date: '2026-09-07', solutions: ['ai-crm', 'whatsapp-crm'],
    copy: {
      az: { title: 'CRM-də AI: 2026-da real işləyən nədir və nə hələ reklamdır', description: 'CRM-də süni intellektin real tətbiqləri: cavab qaralamaları, zəng xülasəsi, lid eskalasiyası, tiket təsnifatı, ödəniş xatırlatmaları. Həvalə səviyyələri və risklər.', keywords: ['AI CRM', 'süni intellekt satış', 'AI agent', 'AI çatbot biznes', 'CRM avtomatlaşdırma'], h1: 'CRM-də AI: real işləyən nədir', intro: 'Hər CRM indi «AI» deyir. Faydalı sual budur: AI hansı konkret hərəkəti kimin əvəzinə edir və səhv edəndə nə olur. Aşağıda — LeadDrive-da real mövcud olan tətbiqlər və onları necə təhlükəsiz qoşmaq.', sections: [
        { h2: 'Üç həvalə səviyyəsi', p: ['Təhlil: AI oxuyur və izah edir, heç nə etmir. Təklif: AI hərəkət hazırlayır, əməkdaş bir kliklə təsdiqləyir. Avtopilot: AI özü edir, seçilmiş ssenarilər üzrə və gündəlik büdcə çərçivəsində. Düzgün yol — həmişə birincidən başlamaq.'] },
        { h2: 'Real işləyən tətbiqlər', list: ['Messencerdə cavab qaralaması: AI bilik bazasından cavab yazır, əməkdaş göndərir.', 'Zəng xülasəsi: zəngdən sonra mövzular, müştəri əhval-ruhiyyəsi və tapşırıqlar.', 'Qaynar lid eskalasiyası: müştəri tələsirsə, rəhbərə siqnal.', 'Neqativ ton eskalasiyası: dialoq insana keçir.', 'Tiket avtotəsnifatı: kateqoriya və prioritet.', 'Ödəniş və uzadılma xatırlatmaları.'] },
        { h2: 'Hələ ehtiyatla', p: ['Müştəri ilə tam avtonom satış dialoqu. Qiymət və şərtlər haqqında cavablar — yalnız bilik bazasından və limitlə. AI-nin nəyi bilmədiyi bəlli olmalıdır, ona görə də açar sözlərlə operatora ötürmə mütləqdir.'] },
        { h2: 'Xərc və nəzarət', p: ['Gündəlik AI büdcəsi, dialoq və kontakt üzrə cavab limitləri parametrlərdə təyin olunur. Limit aşıldıqda dialoq insana keçir. Hər AI hərəkəti tarixçədə görünür. Ətraflı — «AI CRM» həlli səhifəsində.'] },
      ] },
      ru: { title: 'AI в CRM: что реально работает в 2026, а что пока реклама', description: 'Реальные применения искусственного интеллекта в CRM: черновики ответов, резюме звонков, эскалация лидов, классификация тикетов, напоминания об оплате. Уровни делегирования и риски.', keywords: ['AI CRM', 'искусственный интеллект продажи', 'AI агент', 'AI чат-бот бизнес', 'автоматизация CRM'], h1: 'AI в CRM: что реально работает', intro: 'Каждая CRM теперь говорит «AI». Полезный вопрос другой: какое конкретное действие AI делает вместо кого и что происходит, когда он ошибается. Ниже применения, которые реально есть в LeadDrive, и как подключать их безопасно.', sections: [
        { h2: 'Три уровня делегирования', p: ['Анализ: AI читает и объясняет, ничего не делает. Предложение: AI готовит действие, сотрудник подтверждает одним кликом. Автопилот: AI делает сам, по выбранным сценариям и в пределах дневного бюджета. Правильный путь — всегда начинать с первого.'] },
        { h2: 'Что реально работает', list: ['Черновик ответа в мессенджере: AI пишет из базы знаний, сотрудник отправляет.', 'Резюме звонка: после разговора темы, настроение клиента и задачи.', 'Эскалация горячего лида: если клиент торопится, сигнал руководителю.', 'Эскалация негативного тона: диалог передаётся человеку.', 'Автоклассификация тикетов: категория и приоритет.', 'Напоминания об оплате и продлении.'] },
        { h2: 'Пока с осторожностью', p: ['Полностью автономный диалог продажи с клиентом. Ответы о ценах и условиях — только из базы знаний и с лимитом. Должно быть ясно, чего AI не знает, поэтому передача оператору по ключевым словам обязательна.'] },
        { h2: 'Расходы и контроль', p: ['Дневной бюджет AI, лимиты ответов на диалог и на контакт задаются в настройках. При превышении диалог переходит к человеку. Каждое действие AI видно в истории. Подробнее на странице решения «AI в CRM».'] },
      ] },
      en: { title: 'AI in a CRM: what really works in 2026 and what is still marketing', description: 'Real uses of artificial intelligence in a CRM: reply drafts, call summaries, lead escalation, ticket classification, payment reminders. Delegation levels and risks.', keywords: ['AI CRM', 'artificial intelligence sales', 'AI agent', 'AI chatbot business', 'CRM automation'], h1: 'AI in a CRM: what really works', intro: 'Every CRM now says “AI”. The useful question is different: which specific action does the AI take instead of whom, and what happens when it is wrong. Below are the uses that really exist in LeadDrive and how to switch them on safely.', sections: [
        { h2: 'Three delegation levels', p: ['Analyse: the AI reads and explains, does nothing. Suggest: the AI prepares an action, an employee confirms with one click. Autopilot: the AI acts on its own, for selected scenarios and within a daily budget. The right path always starts with the first.'] },
        { h2: 'What really works', list: ['A reply draft in a messenger: the AI writes from the knowledge base, an employee sends.', 'A call summary: topics, customer mood and tasks after the conversation.', 'Hot lead escalation: if the customer is in a hurry, a signal to the manager.', 'Negative tone escalation: the conversation goes to a person.', 'Automatic ticket classification: category and priority.', 'Payment and renewal reminders.'] },
        { h2: 'Still with caution', p: ['A fully autonomous sales conversation with a customer. Answers about prices and terms only from the knowledge base and with a limit. It must be clear what the AI does not know, so keyword handover to an operator is mandatory.'] },
        { h2: 'Cost and control', p: ['A daily AI budget and reply limits per conversation and per contact are set in the settings. When exceeded, the conversation goes to a person. Every AI action is visible in the history. More on the “AI CRM” solution page.'] },
      ] },
    },
  },
  {
    slug: 'why-leads-get-lost', date: '2026-09-07', solutions: ['whatsapp-crm', 'sales-crm'],
    copy: {
      az: { title: 'Müraciətlər niyə itir: 6 səbəb və itkini necə ölçməli', description: 'Lidlərin itməsinin əsas səbəbləri: gec cavab, məsul şəxsin olmaması, kanalların dağınıqlığı, follow-up-un yoxluğu. İtkini hesablamaq üçün sadə düstur və CRM-də nəzarət.', keywords: ['lidlər itir', 'müraciətlərin itməsi', 'cavab müddəti', 'lid idarəetməsi', 'satış itkisi'], h1: 'Müraciətlər niyə itir və itkini necə ölçməli', intro: 'Reklama pul xərclənir, müraciətlər gəlir, satış isə artmır. Adətən səbəb reklamda deyil: müraciətlərin bir hissəsi cavab almadan itir. Bu itkini görmək və hesablamaq olar.', sections: [
        { h2: 'Altı səbəb', list: ['Gec cavab: 1 saatdan sonra müştəri artıq rəqibə yazıb.', 'Məsul şəxs yoxdur: hamı görür, heç kim cavab vermir.', 'Kanallar dağınıqdır: WhatsApp bir telefonda, Instagram başqasında.', 'Follow-up yoxdur: müştəri «düşünürəm» dedi, heç kim geri qayıtmadı.', 'Qeyri-iş vaxtı: axşam və həftə sonu müraciətlər cavabsız.', 'Əməkdaş dəyişib: tarixçə onunla getdi.'] },
        { h2: 'İtkini hesablayın', p: ['Bir həftə ərzində bütün kanallardan gələn müraciətləri sayın. Sonra neçəsinin CRM-də lid kimi qeydə alındığını sayın. Fərq — birinci itki. Sonra lidlərdən neçəsinə 1 saat ərzində cavab verilib — ikinci itki. Nümunə: 120 müraciət, 80 lid, 45-i bir saat ərzində cavablanıb. Deməli, 75 müraciət ya itib, ya soyuyub.'] },
        { h2: 'Nə etməli', p: ['Bütün kanalları bir Inbox-a yığın, hər söhbətə məsul şəxs təyin edin, cavab müddətini ölçün, qeyri-iş vaxtı üçün avtomatik cavab qoyun və «düşünürəm» üçün 2 gün sonra tapşırıq yaradın. LeadDrive-da bunlar Inbox, iş saatları və avtomatlaşdırma qaydaları ilə həll olunur.'] },
      ] },
      ru: { title: 'Почему теряются заявки: 6 причин и как измерить потери', description: 'Основные причины потери лидов: поздний ответ, отсутствие ответственного, разрозненные каналы, нет follow-up. Простая формула расчёта потерь и контроль в CRM.', keywords: ['теряются лиды', 'потеря заявок', 'время ответа', 'управление лидами', 'потери продаж'], h1: 'Почему теряются заявки и как измерить потери', intro: 'Деньги тратятся на рекламу, заявки приходят, а продажи не растут. Обычно причина не в рекламе: часть заявок теряется, не получив ответа. Эту потерю можно увидеть и посчитать.', sections: [
        { h2: 'Шесть причин', list: ['Поздний ответ: через час клиент уже написал конкуренту.', 'Нет ответственного: видят все, не отвечает никто.', 'Каналы разрознены: WhatsApp на одном телефоне, Instagram на другом.', 'Нет follow-up: клиент сказал «подумаю», никто не вернулся.', 'Нерабочее время: вечером и в выходные заявки без ответа.', 'Сменился сотрудник: история ушла с ним.'] },
        { h2: 'Посчитайте потери', p: ['За одну неделю посчитайте все обращения из всех каналов. Затем — сколько из них зафиксировано в CRM как лид. Разница — первая потеря. Затем — скольким лидам ответили в течение часа — вторая потеря. Пример: 120 обращений, 80 лидов, 45 отвечены за час. Значит, 75 обращений либо потеряны, либо остыли.'] },
        { h2: 'Что делать', p: ['Собрать все каналы в один Inbox, назначить ответственного на каждую беседу, измерять время ответа, поставить автоответ на нерабочее время и создавать задачу через 2 дня после «подумаю». В LeadDrive это решается Inbox, рабочими часами и правилами автоматизации.'] },
      ] },
      en: { title: 'Why leads get lost: 6 reasons and how to measure the loss', description: 'The main reasons leads are lost: late replies, no owner, scattered channels, no follow-up. A simple formula to calculate the loss and control it in a CRM.', keywords: ['lost leads', 'losing requests', 'response time', 'lead management', 'lost sales'], h1: 'Why leads get lost and how to measure the loss', intro: 'Money goes into advertising, requests come in, but sales do not grow. Usually the problem is not the advertising: some requests are lost before they get a reply. That loss can be seen and counted.', sections: [
        { h2: 'Six reasons', list: ['Late reply: an hour later the customer has already written to a competitor.', 'No owner: everyone sees it, nobody replies.', 'Scattered channels: WhatsApp on one phone, Instagram on another.', 'No follow-up: the customer said “I will think about it” and nobody came back.', 'Out of hours: evening and weekend requests go unanswered.', 'The employee changed: the history left with them.'] },
        { h2: 'Calculate the loss', p: ['Over one week count every request from every channel. Then count how many were recorded in the CRM as leads. The difference is the first loss. Then count how many leads got a reply within an hour: the second loss. Example: 120 requests, 80 leads, 45 answered within an hour. So 75 requests were either lost or went cold.'] },
        { h2: 'What to do', p: ['Gather all channels into one inbox, assign an owner to every conversation, measure response time, set an auto-reply for out-of-hours and create a task two days after “I will think about it”. In LeadDrive this is handled by the inbox, business hours and automation rules.'] },
      ] },
    },
  },
  {
    slug: 'contract-approval-speed', date: '2026-09-07', solutions: ['contract-management', 'crm-for-public-sector'],
    copy: {
      az: { title: 'Müqavilə təsdiqini həftələrdən günlərə necə endirməli', description: 'Müqavilələr niyə həftələrlə təsdiqdə gəzir: e-poçt zənciri, versiyalar, şablonsuz mətn. Şablonlar, təsdiq marşrutu, versiya müqayisəsi və elektron imza ilə həll.', keywords: ['müqavilə təsdiqi', 'müqavilə idarəetməsi', 'elektron imza', 'sənəd dövriyyəsi', 'müqavilə şablonu'], h1: 'Müqavilə təsdiqini həftələrdən günlərə necə endirməli', intro: 'Tipik mənzərə: menecer müqaviləni hüquqşünasa göndərir, o düzəliş edir, maliyyə başqa versiyaya baxır, direktor imzalayır — hansı versiyanı, heç kim dəqiq bilmir. Nəticə: iki həftə və risk.', sections: [
        { h2: 'Gecikmənin dörd səbəbi', list: ['Hər müqavilə sıfırdan yazılır — hüquqşünas hər dəfə hamısını oxuyur.', 'Təsdiq e-poçtda gedir — kimdə qaldığı görünmür.', 'Versiyalar faylların adındadır: «final», «final2», «final_yeni».', 'İmza kağızda — çap, skan, kuryer.'] },
        { h2: 'Həll: dörd element', p: ['Bəndli şablonlar: standart mətn hazırdır, hüquqşünas yalnız sapmaları yoxlayır. Təsdiq marşrutu: kim, hansı ardıcıllıqla, neçə gün; gecikmə xatırlatma verir, nümayəndəlik məzuniyyəti örtür. Versiyalar: hər dəyişiklik saxlanılır və müqayisə olunur. Elektron imza: daxili və ya DocuSign, zərf statusu kartda.'] },
        { h2: 'Nəyi ölçməli', p: ['Tələbdən imzaya qədər orta müddət, hər mərhələdə orta gözləmə, şablondan sapma ilə müqavilələrin payı. LeadDrive-da müqavilə analitikası bu üç göstəricini verir; ətraflı «Müqavilələr» həlli səhifəsində.'] },
      ] },
      ru: { title: 'Как сократить согласование договоров с недель до дней', description: 'Почему договоры неделями ходят по согласованиям: цепочки писем, версии, текст без шаблона. Решение через шаблоны, маршрут согласования, сравнение версий и электронную подпись.', keywords: ['согласование договоров', 'управление договорами', 'электронная подпись', 'документооборот', 'шаблон договора'], h1: 'Как сократить согласование договоров с недель до дней', intro: 'Типичная картина: менеджер отправляет договор юристу, тот правит, финансы смотрят другую версию, директор подписывает — какую именно, никто точно не знает. Итог: две недели и риск.', sections: [
        { h2: 'Четыре причины задержки', list: ['Каждый договор пишется с нуля — юрист каждый раз читает всё.', 'Согласование идёт по почте — не видно, у кого застряло.', 'Версии живут в названиях файлов: «final», «final2», «final_new».', 'Подпись на бумаге — печать, скан, курьер.'] },
        { h2: 'Решение: четыре элемента', p: ['Шаблоны с пунктами: стандартный текст готов, юрист проверяет только отклонения. Маршрут согласования: кто, в каком порядке, сколько дней; задержка даёт напоминание, делегирование закрывает отпуск. Версии: каждое изменение сохраняется и сравнивается. Электронная подпись: встроенная или DocuSign, статус конверта в карточке.'] },
        { h2: 'Что измерять', p: ['Среднее время от запроса до подписи, среднее ожидание на каждом этапе, доля договоров с отклонением от шаблона. В LeadDrive аналитика договоров даёт эти три показателя; подробнее на странице решения «Договоры».'] },
      ] },
      en: { title: 'How to cut contract approval from weeks to days', description: 'Why contracts circulate for weeks: email chains, versions, text without a template. The fix through templates, an approval route, version comparison and e-signature.', keywords: ['contract approval', 'contract management', 'e-signature', 'document workflow', 'contract template'], h1: 'How to cut contract approval from weeks to days', intro: 'The typical picture: a manager sends the contract to legal, legal edits it, finance reviews a different version, the director signs, and nobody knows exactly which one. Result: two weeks and risk.', sections: [
        { h2: 'Four causes of delay', list: ['Every contract is written from scratch; legal reads everything every time.', 'Approval goes by email; nobody sees where it is stuck.', 'Versions live in file names: “final”, “final2”, “final_new”.', 'Signature on paper: print, scan, courier.'] },
        { h2: 'The fix: four elements', p: ['Templates with clauses: the standard text is ready, legal checks only deviations. An approval route: who, in what order, how many days; a delay triggers a reminder, delegation covers holidays. Versions: every change is saved and compared. E-signature: built-in or DocuSign, envelope status on the card.'] },
        { h2: 'What to measure', p: ['Average time from request to signature, average wait at each stage, share of contracts deviating from the template. In LeadDrive contract analytics gives these three metrics; more on the “Contracts” solution page.'] },
      ] },
    },
  },
  {
    slug: 'receivables-reminders', date: '2026-09-07', solutions: ['invoicing-finance', 'crm-for-utilities'],
    copy: {
      az: { title: 'Debitor borcu: ödəniş xatırlatmalarını necə avtomatlaşdırmalı', description: 'Gecikmiş fakturalar üzrə xatırlatma zənciri: vaxt, kanal, ton. Faktura statusları, qismən ödənişlər və borcluların hesabatı CRM-də.', keywords: ['debitor borcu', 'ödəniş xatırlatması', 'gecikmiş faktura', 'faktura nəzarəti', 'borc yığımı'], h1: 'Debitor borcu: ödəniş xatırlatmalarını necə avtomatlaşdırmalı', intro: 'Faktura kəsmək asandır, ödənişi almaq çətindir. Şirkətlərin çoxunda xatırlatma mühasibin yaddaşına və menecerin cəsarətinə bağlıdır. Zəncir bunu sistemli edir və münasibəti korlamır.', sections: [
        { h2: 'Xatırlatma zənciri', list: ['Müddətdən 3 gün əvvəl: nəzakətli xatırlatma, faktura PDF əlavə.', 'Müddət günü: qısa mesaj, ödəniş rekvizitləri.', 'Müddətdən 3 gün sonra: gecikmə barədə bildiriş, məsul menecerə tapşırıq.', 'Müddətdən 10 gün sonra: zəng, təkrar faktura.', '30 gün sonra: rəhbərə eskalasiya, xidmətin dayandırılması barədə qərar.'] },
        { h2: 'Kanal və ton', p: ['E-poçt rəsmi xatırlatma üçün, WhatsApp tez cavab üçün. Ton hər addımda bir az sərtləşir, amma ilk üç mesaj həmişə nəzakətlidir — müştərilərin çoxu sadəcə unudur.'] },
        { h2: 'CRM-də nə lazımdır', p: ['Faktura statusları (qaralama, göndərilib, ödənilib, gecikmiş), qismən ödənişlər və qalıq, müştəri üzrə borc hesabatı, avtomatik xatırlatma və menecerə tapşırıq. LeadDrive-da bunlar maliyyə modulunda və AI «ödəniş xatırlatması» ssenarisindədir; ətraflı «Fakturalar və maliyyə» səhifəsində.'] },
      ] },
      ru: { title: 'Дебиторка: как автоматизировать напоминания об оплате', description: 'Цепочка напоминаний по просроченным счетам: сроки, каналы, тон. Статусы счетов, частичные оплаты и отчёт по должникам в CRM.', keywords: ['дебиторская задолженность', 'напоминание об оплате', 'просроченный счёт', 'контроль счетов', 'взыскание долгов'], h1: 'Дебиторка: как автоматизировать напоминания об оплате', intro: 'Выставить счёт легко, получить оплату сложно. В большинстве компаний напоминание зависит от памяти бухгалтера и смелости менеджера. Цепочка делает это системным и не портит отношения.', sections: [
        { h2: 'Цепочка напоминаний', list: ['За 3 дня до срока: вежливое напоминание, PDF счёта во вложении.', 'В день срока: короткое сообщение, реквизиты для оплаты.', 'Через 3 дня после срока: уведомление о просрочке, задача ответственному менеджеру.', 'Через 10 дней: звонок, повторный счёт.', 'Через 30 дней: эскалация руководителю, решение о приостановке услуги.'] },
        { h2: 'Канал и тон', p: ['Почта для официального напоминания, WhatsApp для быстрого ответа. Тон с каждым шагом чуть строже, но первые три сообщения всегда вежливые — большинство клиентов просто забывают.'] },
        { h2: 'Что нужно в CRM', p: ['Статусы счетов (черновик, отправлен, оплачен, просрочен), частичные оплаты и остаток, отчёт по долгам по клиентам, автоматическое напоминание и задача менеджеру. В LeadDrive это в финансовом модуле и AI-сценарии «напоминание об оплате»; подробнее на странице «Счета и финансы».'] },
      ] },
      en: { title: 'Receivables: how to automate payment reminders', description: 'A reminder chain for overdue invoices: timing, channels, tone. Invoice statuses, partial payments and a debtor report in the CRM.', keywords: ['accounts receivable', 'payment reminder', 'overdue invoice', 'invoice control', 'debt collection'], h1: 'Receivables: how to automate payment reminders', intro: 'Issuing an invoice is easy; getting paid is hard. In most companies the reminder depends on the accountant’s memory and the manager’s courage. A chain makes it systematic without hurting the relationship.', sections: [
        { h2: 'The reminder chain', list: ['3 days before the due date: a polite reminder with the invoice PDF attached.', 'On the due date: a short message with payment details.', '3 days after: an overdue notice and a task for the owning manager.', '10 days after: a call and a re-issued invoice.', '30 days after: escalation to management and a decision on suspending the service.'] },
        { h2: 'Channel and tone', p: ['Email for the formal reminder, WhatsApp for a quick answer. The tone gets slightly firmer at each step, but the first three messages are always polite; most customers simply forget.'] },
        { h2: 'What you need in the CRM', p: ['Invoice statuses (draft, sent, paid, overdue), partial payments and balance, a debt report per customer, an automatic reminder and a task for the manager. In LeadDrive this lives in the finance module and the “payment reminder” AI scenario; more on the “Invoices and finance” page.'] },
      ] },
    },
  },
  {
    slug: 'nps-customer-feedback', date: '2026-09-07', solutions: ['marketing-automation', 'crm-for-clinics'],
    copy: {
      az: { title: 'NPS nədir və müştəri rəyini CRM vasitəsilə necə toplamalı', description: 'NPS (Net Promoter Score) sadə dillə: sual, hesablama düsturu, nə vaxt göndərməli, cavabları CRM-də necə istifadə etməli. Klinikalar, xidmət və B2B üçün nümunələr.', keywords: ['NPS nədir', 'müştəri rəyi', 'NPS sorğusu', 'müştəri məmnuniyyəti', 'sorğu CRM'], h1: 'NPS nədir və müştəri rəyini CRM vasitəsilə necə toplamalı', intro: 'NPS bir sualdır: «Bizi dostunuza tövsiyə edərdinizmi, 0-dan 10-a?» Sadəliyinə görə işləyir: cavab vermək 5 saniyə çəkir, nəticəni isə aylar üzrə müqayisə etmək olur.', sections: [
        { h2: 'Düstur', p: ['9–10 verənlər — promouterlər, 7–8 — neytrallar, 0–6 — tənqidçilər. NPS = promouterlərin % − tənqidçilərin %. Nümunə: 100 cavab, 55 promouter, 25 neytral, 20 tənqidçi → NPS 35. Rəqəmin özü yox, dinamikası və tənqidçilərin şərhləri vacibdir.'] },
        { h2: 'Nə vaxt göndərməli', list: ['Klinika: ziyarətdən 1 gün sonra.', 'Xidmət: tiket bağlanandan sonra (bu artıq CSAT-a yaxındır).', 'B2B: müqavilənin uzadılmasından 2 ay əvvəl — hələ nəyisə düzəltmək olar.'] },
        { h2: 'Cavabları CRM-də necə istifadə etməli', p: ['Cavab müştəri kartına düşməlidir. Tənqidçi (0–6) → məsul menecerə tapşırıq 24 saat ərzində. Promouter (9–10) → rəy və tövsiyə xahişi. Şərhlər seqmentlərə görə təhlil olunur: filial, məhsul, menecer. LeadDrive-da sorğular və NPS marketinq modulundadır, cavablar kartda görünür.'] },
      ] },
      ru: { title: 'Что такое NPS и как собирать обратную связь клиентов через CRM', description: 'NPS (Net Promoter Score) простыми словами: вопрос, формула расчёта, когда отправлять, как использовать ответы в CRM. Примеры для клиник, сервиса и B2B.', keywords: ['что такое NPS', 'обратная связь клиентов', 'опрос NPS', 'удовлетворённость клиентов', 'опросы CRM'], h1: 'Что такое NPS и как собирать обратную связь через CRM', intro: 'NPS — это один вопрос: «Порекомендуете ли вы нас другу, от 0 до 10?» Он работает благодаря простоте: ответ занимает 5 секунд, а результат можно сравнивать по месяцам.', sections: [
        { h2: 'Формула', p: ['Поставившие 9–10 — промоутеры, 7–8 — нейтралы, 0–6 — критики. NPS = % промоутеров − % критиков. Пример: 100 ответов, 55 промоутеров, 25 нейтралов, 20 критиков → NPS 35. Важна не сама цифра, а динамика и комментарии критиков.'] },
        { h2: 'Когда отправлять', list: ['Клиника: через 1 день после визита.', 'Сервис: после закрытия тикета (это уже ближе к CSAT).', 'B2B: за 2 месяца до продления договора — ещё можно что-то исправить.'] },
        { h2: 'Как использовать ответы в CRM', p: ['Ответ должен попадать в карточку клиента. Критик (0–6) → задача ответственному менеджеру в течение 24 часов. Промоутер (9–10) → просьба об отзыве и рекомендации. Комментарии анализируются по сегментам: филиал, продукт, менеджер. В LeadDrive опросы и NPS находятся в маркетинговом модуле, ответы видны в карточке.'] },
      ] },
      en: { title: 'What is NPS and how to collect customer feedback through a CRM', description: 'NPS (Net Promoter Score) in plain words: the question, the formula, when to send it, how to use answers in a CRM. Examples for clinics, service and B2B.', keywords: ['what is NPS', 'customer feedback', 'NPS survey', 'customer satisfaction', 'CRM surveys'], h1: 'What is NPS and how to collect customer feedback through a CRM', intro: 'NPS is one question: “Would you recommend us to a friend, from 0 to 10?” It works because it is simple: answering takes five seconds and the result can be compared month over month.', sections: [
        { h2: 'The formula', p: ['Those who give 9–10 are promoters, 7–8 are passives, 0–6 are detractors. NPS = % promoters − % detractors. Example: 100 answers, 55 promoters, 25 passives, 20 detractors → NPS 35. What matters is not the number itself but the trend and the detractors’ comments.'] },
        { h2: 'When to send it', list: ['Clinic: one day after the visit.', 'Service: after the ticket is closed (closer to CSAT).', 'B2B: two months before the contract renewal, while something can still be fixed.'] },
        { h2: 'How to use the answers in a CRM', p: ['The answer must land on the customer card. A detractor (0–6) → a task for the owning manager within 24 hours. A promoter (9–10) → a request for a review and a referral. Comments are analysed by segment: branch, product, manager. In LeadDrive surveys and NPS live in the marketing module and answers show on the card.'] },
      ] },
    },
  },
];
