import type { Article } from './articles';

export const ARTICLES_A: Article[] = [
  {
    slug: 'what-is-crm', date: '2026-09-07', solutions: ['sales-crm', 'whatsapp-crm'],
    copy: {
      az: { title: 'CRM nədir və biznesə nə üçün lazımdır — sadə dillə', description: 'CRM nədir, hansı məlumatları saxlayır, kiçik və orta biznesə nə verir və hansı əlamətlər göstərir ki, cədvəllər artıq kifayət etmir. Azərbaycan şirkətləri üçün izahat.', keywords: ['CRM nədir', 'CRM sistemi nədir', 'CRM proqramı', 'müştəri bazası', 'CRM Azərbaycan'], h1: 'CRM nədir və biznesə nə üçün lazımdır', intro: 'CRM (Customer Relationship Management) — müştərilərlə bütün əlaqələri bir yerdə saxlayan sistemdir: kim yazıb, kim zəng edib, nə vəd olunub, sövdələşmə hansı mərhələdədir. Bu məqalədə terminsiz izah edirik ki, CRM real olaraq nə edir və nə vaxt ona keçmək vaxtıdır.', sections: [
        { h2: 'CRM hansı məlumatları saxlayır', p: ['Əsas dörd obyekt: kontakt (insan), şirkət, lid (hələ müştəri olmayan müraciət) və sövdələşmə (konkret satış). Hər obyektin kartı var, kartda isə tarixçə: zənglər, yazışmalar, tapşırıqlar, sənədlər və qeydlər.', 'Müasir CRM-də bura messencerlər də daxildir. WhatsApp və ya Instagram-dan gələn mesaj kontaktın kartına düşür, ona görə də əməkdaş dəyişəndə tarixçə itmir.'] },
        { h2: 'CRM olmadan nə itir', p: ['Kiçik komandada hər şey yaddaşda və telefonda saxlanılır. Bu, ayda 30–50 müraciətə qədər işləyir. Sonra tipik itkilər başlayır:'], list: ['Menecer geri zəng edəcəyini vəd edir və unudur — lid rəqibə gedir.', 'Müştəri iki kanaldan yazır və iki fərqli cavab alır.', 'Rəhbər ayın sonunda nə qədər gəlir gələcəyini görmür.', 'Əməkdaş işdən çıxanda müştərilər onunla birlikdə gedir.'] },
        { h2: 'CRM nə verir', p: ['Birincisi, hər lidin məsul şəxsi və növbəti addımı olur — heç nə «havada» qalmır. İkincisi, satış hunisi görünür: neçə müraciət gəlib, neçəsi təklifə keçib, neçəsi bağlanıb. Üçüncüsü, kommunikasiya kanalları bir Inbox-a yığılır və cavab müddəti ölçülür.', 'Bunun üstündə avtomatlaşdırma qurulur: xatırlatmalar, faktura üzrə ödəniş nəzarəti, müqavilə təsdiqi, AI cavab qaralamaları. LeadDrive-da bu funksiyalar ayrı modullardır və mərhələ-mərhələ qoşulur.'] },
        { h2: 'CRM-ə keçmək vaxtıdır — əlamətlər', list: ['Müraciətlər əməkdaşların şəxsi telefonlarında qalır.', '«Kim bu müştəri ilə işləyir?» sualına cavab tapmaq 10 dəqiqə çəkir.', 'Excel-də sövdələşmə cədvəli var, amma onu heç kim yeniləmir.', 'Fakturalar kəsilir, borclar isə yalnız mühasibin yaddaşındadır.', 'Reklamdan neçə müştəri gəldiyini hesablamaq mümkün deyil.'] },
        { h2: 'Azərbaycanda CRM seçərkən nəyə baxmalı', p: ['Üç praktik meyar: WhatsApp və Instagram qoşulması (bizdə müraciətlərin əksəriyyəti oradan gəlir), Azərbaycan dilində interfeys və dəstək, həmçinin faktura və müqavilə modulunun olması ki, satış ayrı, mühasibatlıq ayrı yaşamasın. Seçim haqqında ətraflı: «Azərbaycanda CRM necə seçməli» məqaləsi.'] },
      ] },
      ru: { title: 'Что такое CRM и зачем она бизнесу — простыми словами', description: 'Что такое CRM-система, какие данные она хранит, что даёт малому и среднему бизнесу и по каким признакам понять, что таблиц уже не хватает. Объяснение для компаний в Азербайджане.', keywords: ['что такое CRM', 'CRM система это', 'CRM программа', 'клиентская база', 'CRM Азербайджан'], h1: 'Что такое CRM и зачем она бизнесу', intro: 'CRM (Customer Relationship Management) — система, где хранятся все отношения с клиентами: кто писал, кто звонил, что обещали, на какой стадии сделка. В этой статье без терминов объясняем, что CRM делает на самом деле и когда пора на неё переходить.', sections: [
        { h2: 'Какие данные хранит CRM', p: ['Четыре базовых объекта: контакт (человек), компания, лид (обращение, которое ещё не стало клиентом) и сделка (конкретная продажа). У каждого объекта есть карточка, а в карточке история: звонки, переписка, задачи, документы и заметки.', 'В современной CRM сюда входят и мессенджеры. Сообщение из WhatsApp или Instagram попадает в карточку контакта, поэтому при смене сотрудника история не теряется.'] },
        { h2: 'Что теряется без CRM', p: ['В маленькой команде всё держится на памяти и телефоне. Это работает примерно до 30–50 обращений в месяц. Дальше начинаются типичные потери:'], list: ['Менеджер обещал перезвонить и забыл — лид ушёл к конкуренту.', 'Клиент написал в два канала и получил два разных ответа.', 'Руководитель не видит, сколько денег придёт в конце месяца.', 'Сотрудник уволился, и клиенты ушли вместе с ним.'] },
        { h2: 'Что даёт CRM', p: ['Во-первых, у каждого лида появляется ответственный и следующий шаг — ничего не висит «в воздухе». Во-вторых, видна воронка продаж: сколько обращений пришло, сколько дошло до предложения, сколько закрылось. В-третьих, каналы общения собираются в один Inbox, и время ответа измеряется.', 'Поверх этого строится автоматизация: напоминания, контроль оплат по счетам, согласование договоров, AI-черновики ответов. В LeadDrive это отдельные модули, которые подключаются поэтапно.'] },
        { h2: 'Признаки, что пора переходить на CRM', list: ['Обращения остаются в личных телефонах сотрудников.', 'Ответ на вопрос «кто ведёт этого клиента?» занимает 10 минут.', 'В Excel есть таблица сделок, но её никто не обновляет.', 'Счета выставлены, а долги только в памяти бухгалтера.', 'Невозможно посчитать, сколько клиентов пришло из рекламы.'] },
        { h2: 'На что смотреть при выборе CRM в Азербайджане', p: ['Три практических критерия: подключение WhatsApp и Instagram (у нас оттуда приходит большинство обращений), интерфейс и поддержка на азербайджанском языке, а также наличие модулей счетов и договоров, чтобы продажи и бухгалтерия не жили отдельно. Подробнее о выборе: статья «Как выбрать CRM в Азербайджане».'] },
      ] },
      en: { title: 'What is a CRM and why does a business need one — in plain words', description: 'What a CRM system is, what data it stores, what it gives small and medium businesses and which signs show that spreadsheets are no longer enough. An explanation for companies in Azerbaijan.', keywords: ['what is a CRM', 'CRM system meaning', 'CRM software', 'customer database', 'CRM Azerbaijan'], h1: 'What is a CRM and why does a business need one', intro: 'A CRM (Customer Relationship Management) system keeps every customer relationship in one place: who wrote, who called, what was promised, which stage the deal is at. This article explains without jargon what a CRM really does and when it is time to move to one.', sections: [
        { h2: 'What data a CRM stores', p: ['Four basic objects: a contact (a person), a company, a lead (a request that is not yet a customer) and a deal (a specific sale). Each has a card, and the card holds the history: calls, messages, tasks, documents and notes.', 'In a modern CRM this includes messengers. A message from WhatsApp or Instagram lands on the contact card, so the history survives a change of employee.'] },
        { h2: 'What gets lost without a CRM', p: ['In a small team everything lives in memory and on phones. That works up to roughly 30–50 requests a month. Then the typical losses begin:'], list: ['A manager promised to call back and forgot; the lead went to a competitor.', 'A customer wrote on two channels and got two different answers.', 'The owner cannot see how much money will arrive by month end.', 'An employee left and the customers left with them.'] },
        { h2: 'What a CRM gives you', p: ['First, every lead gets an owner and a next step; nothing hangs in the air. Second, the sales funnel becomes visible: how many requests came in, how many reached a quote, how many closed. Third, communication channels gather in one inbox and response time is measured.', 'On top of that comes automation: reminders, payment control on invoices, contract approval, AI reply drafts. In LeadDrive these are separate modules that are switched on step by step.'] },
        { h2: 'Signs it is time to move to a CRM', list: ['Requests stay on employees’ personal phones.', 'Answering “who handles this customer?” takes ten minutes.', 'There is a deals spreadsheet in Excel, but nobody updates it.', 'Invoices are issued, but debts live only in the accountant’s memory.', 'It is impossible to count how many customers came from advertising.'] },
        { h2: 'What to look at when choosing a CRM in Azerbaijan', p: ['Three practical criteria: WhatsApp and Instagram integration (most requests here come from there), an interface and support in Azerbaijani, and invoice and contract modules so that sales and accounting do not live apart. More on choosing: the article “How to choose a CRM in Azerbaijan”.'] },
      ] },
    },
  },
  {
    slug: 'how-to-choose-crm-azerbaijan', date: '2026-09-07', solutions: ['sales-crm', 'whatsapp-crm', 'invoicing-finance'],
    copy: {
      az: { title: 'Azərbaycanda CRM necə seçməli: 7 meyar və tipik səhvlər', description: 'Azərbaycan bazarı üçün CRM seçimi: WhatsApp və Instagram, dil, fakturalar, telefoniya, hüquqlar, miqrasiya və qiymət modeli. Yoxlama siyahısı və demo üçün suallar.', keywords: ['CRM seçimi', 'CRM necə seçməli', 'CRM Azərbaycan', 'CRM Bakı', 'ən yaxşı CRM'], h1: 'Azərbaycanda CRM necə seçməli', intro: 'CRM seçimi adətən qiymət müqayisəsindən başlayır və yarım il sonra «heç kim istifadə etmir» ilə bitir. Səbəb — sistem şirkətin real prosesinə yox, təqdimata görə seçilib. Aşağıda yerli bazar üçün yeddi meyar var.', sections: [
        { h2: '1. Müraciətlər haradan gəlir', p: ['Azərbaycanda müraciətlərin böyük hissəsi WhatsApp və Instagram-dan gəlir. CRM bu kanalları «inteqrasiya» kimi yox, əsas Inbox kimi dəstəkləməlidir: növbələr, məsul şəxslər, cavab müddəti, iş saatları. Demoda soruşun: WhatsApp Business rəsmi API vasitəsilə qoşulur, yoxsa qeyri-rəsmi yolla?'] },
        { h2: '2. Dil və dəstək', p: ['İnterfeys Azərbaycan dilində olmalıdır — əks halda satış komandası sistemə girməyəcək. Dəstəyin cavab verdiyi dili və saatları da yoxlayın.'] },
        { h2: '3. Satışdan sonra nə olur', p: ['Sövdələşmə bağlanandan sonra faktura, müqavilə və ödəniş nəzarəti gəlir. Əgər bunlar CRM-dən kənardadırsa, «vahid müştəri kartı» haqqında danışmaq olmaz. LeadDrive-da faktura reyestri, müqavilə şablonları və xatırlatma zənciri satışla eyni kartda yaşayır.'] },
        { h2: '4. Telefoniya və zənglər', p: ['Zəng növbələri, zəng qeydləri və zəngdən sonra tapşırıq yaratma. Yerli operatorlarla və SIP ilə işləmə imkanı soruşun.'] },
        { h2: '5. Hüquqlar və təhlükəsizlik', p: ['Kim nəyi görür: modul × rol matrisi, sahə səviyyəsində hüquqlar, ikifaktorlu giriş, audit jurnalı. Bu, xüsusilə sığorta, tibb və dövlət sektoru üçün vacibdir.'] },
        { h2: '6. Miqrasiya', p: ['Excel-dən və köhnə sistemdən idxal, dublikatların birləşdirilməsi, sahələrin uyğunlaşdırılması. Demoda öz faylınızı yükləməyi xahiş edin.'] },
        { h2: '7. Qiymət modeli', p: ['İstifadəçi üzrə abunə, modul üzrə ödəniş və ya şirkət üçün fərdi şərtlər. Gizli xərcləri soruşun: kanal qoşulması, saxlama, API, tətbiq.'] },
        { h2: 'Tipik səhvlər', list: ['Ən böyük funksiya siyahısını seçmək — komanda 10%-dən istifadə edir.', 'Pilotsuz bütün şirkəti keçirmək — bir şöbədən başlayın.', 'Prosesi təsvir etmədən tətbiq etmək — CRM xaosu avtomatlaşdırmır, onu görünən edir.', 'Rəhbərin sistemdən istifadə etməməsi — komanda da istifadə etməyəcək.'] },
      ] },
      ru: { title: 'Как выбрать CRM в Азербайджане: 7 критериев и типичные ошибки', description: 'Выбор CRM для азербайджанского рынка: WhatsApp и Instagram, язык, счета, телефония, права доступа, миграция и модель оплаты. Чек-лист и вопросы для демо.', keywords: ['выбор CRM', 'как выбрать CRM', 'CRM Азербайджан', 'CRM Баку', 'лучшая CRM'], h1: 'Как выбрать CRM в Азербайджане', intro: 'Выбор CRM обычно начинается со сравнения цен и через полгода заканчивается фразой «никто не пользуется». Причина в том, что систему выбрали по презентации, а не под реальный процесс компании. Ниже семь критериев для местного рынка.', sections: [
        { h2: '1. Откуда приходят обращения', p: ['В Азербайджане большая часть обращений приходит из WhatsApp и Instagram. CRM должна поддерживать эти каналы не как «интеграцию», а как основной Inbox: очереди, ответственные, время ответа, рабочие часы. Спросите на демо: WhatsApp Business подключается через официальный API или неофициальным способом?'] },
        { h2: '2. Язык и поддержка', p: ['Интерфейс должен быть на азербайджанском, иначе отдел продаж в систему не зайдёт. Проверьте, на каком языке и в какие часы отвечает поддержка.'] },
        { h2: '3. Что происходит после продажи', p: ['После закрытия сделки идут счёт, договор и контроль оплаты. Если они вне CRM, о «единой карточке клиента» говорить нельзя. В LeadDrive реестр счетов, шаблоны договоров и цепочка напоминаний живут в той же карточке, что и продажи.'] },
        { h2: '4. Телефония и звонки', p: ['Очереди звонков, записи разговоров и создание задачи после звонка. Спросите про работу с местными операторами и SIP.'] },
        { h2: '5. Права и безопасность', p: ['Кто что видит: матрица модуль × роль, права на уровне полей, двухфакторный вход, журнал аудита. Особенно важно для страхования, медицины и госсектора.'] },
        { h2: '6. Миграция', p: ['Импорт из Excel и старой системы, объединение дубликатов, сопоставление полей. Попросите загрузить на демо ваш собственный файл.'] },
        { h2: '7. Модель оплаты', p: ['Подписка за пользователя, оплата по модулям или индивидуальные условия для компании. Спросите про скрытые расходы: подключение каналов, хранение, API, внедрение.'] },
        { h2: 'Типичные ошибки', list: ['Выбрать самый длинный список функций — команда использует 10%.', 'Переводить всю компанию без пилота — начните с одного отдела.', 'Внедрять без описания процесса — CRM не автоматизирует хаос, а делает его видимым.', 'Руководитель не пользуется системой — команда тоже не будет.'] },
      ] },
      en: { title: 'How to choose a CRM in Azerbaijan: 7 criteria and common mistakes', description: 'Choosing a CRM for the Azerbaijani market: WhatsApp and Instagram, language, invoices, telephony, access rights, migration and pricing model. A checklist and questions for the demo.', keywords: ['choosing a CRM', 'how to choose a CRM', 'CRM Azerbaijan', 'CRM Baku', 'best CRM'], h1: 'How to choose a CRM in Azerbaijan', intro: 'Choosing a CRM usually starts with comparing prices and ends six months later with “nobody uses it”. The reason: the system was chosen by the presentation, not by the company’s real process. Below are seven criteria for the local market.', sections: [
        { h2: '1. Where requests come from', p: ['In Azerbaijan most requests come from WhatsApp and Instagram. The CRM must support these channels not as an “integration” but as the main inbox: queues, owners, response time, business hours. Ask on the demo: is WhatsApp Business connected through the official API or an unofficial route?'] },
        { h2: '2. Language and support', p: ['The interface must be in Azerbaijani, otherwise the sales team will not log in. Check which language and hours the support team works in.'] },
        { h2: '3. What happens after the sale', p: ['After the deal closes come the invoice, the contract and payment control. If these live outside the CRM, there is no “single customer card”. In LeadDrive the invoice registry, contract templates and reminder chain live on the same card as sales.'] },
        { h2: '4. Telephony and calls', p: ['Call queues, call recordings and task creation after a call. Ask about local operators and SIP.'] },
        { h2: '5. Rights and security', p: ['Who sees what: a module × role matrix, field-level rights, two-factor login, an audit log. Especially important for insurance, healthcare and the public sector.'] },
        { h2: '6. Migration', p: ['Import from Excel and the old system, duplicate merging, field mapping. Ask them to load your own file on the demo.'] },
        { h2: '7. Pricing model', p: ['Per-user subscription, per-module payment or individual terms for the company. Ask about hidden costs: channel connection, storage, API, implementation.'] },
        { h2: 'Common mistakes', list: ['Picking the longest feature list; the team uses 10% of it.', 'Moving the whole company without a pilot; start with one department.', 'Implementing without describing the process; a CRM does not automate chaos, it makes it visible.', 'The owner does not use the system; neither will the team.'] },
      ] },
    },
  },
  {
    slug: 'whatsapp-business-api-crm', date: '2026-09-07', solutions: ['whatsapp-crm', 'support-helpdesk-crm'],
    copy: {
      az: { title: 'WhatsApp Business API və adi WhatsApp: CRM üçün fərq nədədir', description: 'WhatsApp, WhatsApp Business tətbiqi və WhatsApp Business API arasındakı fərq; biznes üçün hansı variant CRM-ə qoşulur, məhdudiyyətlər, şablonlar və 24 saat qaydası.', keywords: ['WhatsApp Business API', 'WhatsApp CRM inteqrasiyası', 'WhatsApp Business Azərbaycan', 'WhatsApp satış', 'WhatsApp avtomatlaşdırma'], h1: 'WhatsApp Business API və adi WhatsApp: CRM üçün fərq', intro: 'Şirkətlərin çoxu satışı adi WhatsApp-dan aparır: bir nömrə, bir telefon, bir əməkdaş. Bu, komanda böyüyənə qədər işləyir. Sonra üç variant arasında seçim etməli olursunuz.', sections: [
        { h2: 'Üç variant', list: ['Adi WhatsApp — şəxsi hesab, bir cihaz, CRM-ə rəsmi qoşulma yoxdur.', 'WhatsApp Business tətbiqi — biznes profili, kataloq, sürətli cavablar; yenə də bir nömrə və bir telefon.', 'WhatsApp Business API (Cloud API) — hesab Meta tərəfindən idarə olunur, mesajlar CRM-ə API ilə gəlir, bir nömrədə bir neçə əməkdaş işləyir.'] },
        { h2: 'API nə verir', p: ['Bütün söhbətlər CRM Inbox-da: növbə, məsul şəxs, cavab müddəti, müştəri kartına bağlanma. Şablon mesajlar (xatırlatma, sifariş statusu) müştəri yazmasa belə göndərilə bilər. Bir nömrədən bütün komanda cavab verir, telefon lazım deyil.'] },
        { h2: 'Məhdudiyyətlər', p: ['24 saat qaydası: müştərinin son mesajından 24 saat keçəndən sonra yalnız təsdiqlənmiş şablonla yazmaq olar. Şablonlar Meta tərəfindən yoxlanılır. Marketinq mesajları ödənişlidir və ölkəyə görə tariflənir. Qeyri-rəsmi «qoşulmalar» hesabın bloklanmasına gətirə bilər.'] },
        { h2: 'LeadDrive-da necə qoşulur', p: ['Kanal kataloqunda WhatsApp Business üçün addım-addım təlimat var. Sonra kanal üçün rejim seçilir: insan, AI qaralaması və ya AI agent; iş saatları və qeyri-iş vaxtı mesajı tənzimlənir. Söhbətlər lidə və ya kontakta bağlanır. Ətraflı — «WhatsApp CRM» həlli səhifəsində.'] },
      ] },
      ru: { title: 'WhatsApp Business API и обычный WhatsApp: в чём разница для CRM', description: 'Разница между WhatsApp, приложением WhatsApp Business и WhatsApp Business API; какой вариант подключается к CRM, ограничения, шаблоны и правило 24 часов.', keywords: ['WhatsApp Business API', 'интеграция WhatsApp CRM', 'WhatsApp Business Азербайджан', 'продажи в WhatsApp', 'автоматизация WhatsApp'], h1: 'WhatsApp Business API и обычный WhatsApp: разница для CRM', intro: 'Большинство компаний ведут продажи из обычного WhatsApp: один номер, один телефон, один сотрудник. Это работает, пока команда не растёт. Дальше приходится выбирать из трёх вариантов.', sections: [
        { h2: 'Три варианта', list: ['Обычный WhatsApp — личный аккаунт, одно устройство, официального подключения к CRM нет.', 'Приложение WhatsApp Business — профиль компании, каталог, быстрые ответы; по-прежнему один номер и один телефон.', 'WhatsApp Business API (Cloud API) — аккаунт управляется Meta, сообщения приходят в CRM по API, на одном номере работают несколько сотрудников.'] },
        { h2: 'Что даёт API', p: ['Все беседы в Inbox CRM: очередь, ответственный, время ответа, привязка к карточке клиента. Шаблонные сообщения (напоминание, статус заказа) можно отправлять, даже если клиент не писал. С одного номера отвечает вся команда, телефон не нужен.'] },
        { h2: 'Ограничения', p: ['Правило 24 часов: через 24 часа после последнего сообщения клиента писать можно только утверждённым шаблоном. Шаблоны проверяет Meta. Маркетинговые сообщения платные и тарифицируются по стране. Неофициальные «подключения» могут привести к блокировке аккаунта.'] },
        { h2: 'Как подключается в LeadDrive', p: ['В каталоге каналов есть пошаговая инструкция для WhatsApp Business. Затем для канала выбирается режим: человек, AI-черновик или AI-агент; настраиваются рабочие часы и сообщение для нерабочего времени. Беседы привязываются к лиду или контакту. Подробнее на странице решения «WhatsApp CRM».'] },
      ] },
      en: { title: 'WhatsApp Business API vs regular WhatsApp: the difference for a CRM', description: 'The difference between WhatsApp, the WhatsApp Business app and the WhatsApp Business API; which option connects to a CRM, limits, templates and the 24-hour rule.', keywords: ['WhatsApp Business API', 'WhatsApp CRM integration', 'WhatsApp Business Azerbaijan', 'selling on WhatsApp', 'WhatsApp automation'], h1: 'WhatsApp Business API vs regular WhatsApp: the difference for a CRM', intro: 'Most companies sell from regular WhatsApp: one number, one phone, one employee. That works until the team grows. Then you have to choose between three options.', sections: [
        { h2: 'Three options', list: ['Regular WhatsApp: a personal account, one device, no official CRM connection.', 'The WhatsApp Business app: a business profile, catalogue, quick replies; still one number and one phone.', 'WhatsApp Business API (Cloud API): the account is managed by Meta, messages reach the CRM through the API, several employees work on one number.'] },
        { h2: 'What the API gives', p: ['Every conversation in the CRM inbox: queue, owner, response time, link to the customer card. Template messages (reminder, order status) can be sent even if the customer has not written. The whole team replies from one number; no phone needed.'] },
        { h2: 'Limits', p: ['The 24-hour rule: 24 hours after the customer’s last message you can only write with an approved template. Templates are reviewed by Meta. Marketing messages are paid and priced by country. Unofficial “connections” can get the account blocked.'] },
        { h2: 'How it connects in LeadDrive', p: ['The channel catalogue has step-by-step setup for WhatsApp Business. Then a mode is chosen for the channel: a person, an AI draft or an AI agent; business hours and an out-of-hours message are configured. Conversations are linked to a lead or contact. More on the “WhatsApp CRM” solution page.'] },
      ] },
    },
  },
  {
    slug: 'what-is-sla', date: '2026-09-07', solutions: ['support-helpdesk-crm', 'crm-for-utilities'],
    copy: {
      az: { title: 'SLA nədir və biznesə nə üçün lazımdır: cavab müddətləri, eskalasiya, nümunələr', description: 'SLA (Service Level Agreement) sadə dillə: cavab və həll müddəti, prioritetlər, eskalasiya L1–L3, dəstək şərtləri. Tiket sistemində SLA-nı necə qurmalı.', keywords: ['SLA nədir', 'SLA müqaviləsi', 'cavab müddəti', 'tiket sistemi', 'müştəri dəstəyi'], h1: 'SLA nədir və biznesə nə üçün lazımdır', intro: 'SLA — müştəri müraciətinə nə qədər vaxta cavab veriləcəyi və problemin nə qədər vaxta həll olunacağı barədə vəddir. Vəd yazılı olanda onu ölçmək olur; ölçülən şey isə idarə olunur.', sections: [
        { h2: 'SLA-nın iki müddəti', p: ['Cavab müddəti (first response) — müraciətdən ilk cavaba qədər. Həll müddəti (resolution) — müraciətdən bağlanmaya qədər. Adətən prioritetə görə fərqlənir: kritik problem — 1 saat cavab, 4 saat həll; adi sual — 8 saat cavab, 3 iş günü həll.'] },
        { h2: 'Prioritetlər və eskalasiya', p: ['Prioritet müraciətin təsirinə görə təyin olunur: neçə müştəriyə toxunur, pul itkisi varmı. Eskalasiya — müddət keçəndə tiketin növbəti səviyyəyə (L1 → L2 → L3) və ya rəhbərə ötürülməsi. Eskalasiyasız SLA sadəcə rəqəmdir.'] },
        { h2: 'Şirkətlər üçün fərqli şərtlər', p: ['B2B-də hər müştərinin öz dəstək şərtləri ola bilər: «Premium» — 30 dəqiqə cavab, «Standart» — 4 saat. Tiket sistemində bu, şirkət kartına bağlanan şablonlarla təyin olunur.'] },
        { h2: 'Tiket sistemində SLA necə qurulur', list: ['Prioritet cədvəli: cavab və həll müddətləri hər səviyyə üçün.', 'Eskalasiya qaydaları: müddətin 80%-də xəbərdarlıq, 100%-də ötürmə.', 'İş saatları: SLA yalnız iş vaxtında hesablanırmı.', 'Hesabat: SLA-ya uyğunluq faizi agent və növbə üzrə.'], p: ['LeadDrive-da bunlar Service Desk parametrlərində tənzimlənir; ətraflı «Dəstək və tiketlər» həlli səhifəsindədir.'] },
      ] },
      ru: { title: 'Что такое SLA и зачем он бизнесу: сроки ответа, эскалация, примеры', description: 'SLA (Service Level Agreement) простыми словами: время ответа и решения, приоритеты, эскалация L1–L3, условия поддержки. Как настроить SLA в системе тикетов.', keywords: ['что такое SLA', 'соглашение SLA', 'время ответа', 'система тикетов', 'поддержка клиентов'], h1: 'Что такое SLA и зачем он бизнесу', intro: 'SLA — это обещание, за сколько времени клиент получит ответ на обращение и за сколько проблема будет решена. Когда обещание записано, его можно измерять, а что измеряется, тем можно управлять.', sections: [
        { h2: 'Два срока SLA', p: ['Время ответа (first response) — от обращения до первого ответа. Время решения (resolution) — от обращения до закрытия. Обычно различаются по приоритету: критичная проблема — 1 час на ответ, 4 часа на решение; обычный вопрос — 8 часов на ответ, 3 рабочих дня на решение.'] },
        { h2: 'Приоритеты и эскалация', p: ['Приоритет назначается по влиянию обращения: сколько клиентов затронуто, есть ли потеря денег. Эскалация — передача тикета на следующий уровень (L1 → L2 → L3) или руководителю при нарушении срока. SLA без эскалации остаётся просто цифрой.'] },
        { h2: 'Разные условия для компаний', p: ['В B2B у каждого клиента могут быть свои условия поддержки: «Премиум» — 30 минут на ответ, «Стандарт» — 4 часа. В системе тикетов это задаётся шаблонами, привязанными к карточке компании.'] },
        { h2: 'Как настроить SLA в системе тикетов', list: ['Таблица приоритетов: сроки ответа и решения для каждого уровня.', 'Правила эскалации: предупреждение на 80% срока, передача на 100%.', 'Рабочие часы: считается ли SLA только в рабочее время.', 'Отчёт: процент соблюдения SLA по агентам и очередям.'], p: ['В LeadDrive это настраивается в параметрах Service Desk; подробнее на странице решения «Поддержка и тикеты».'] },
      ] },
      en: { title: 'What is an SLA and why does a business need one: response times, escalation, examples', description: 'SLA (Service Level Agreement) in plain words: response and resolution time, priorities, L1–L3 escalation, support entitlements. How to set up SLA in a ticketing system.', keywords: ['what is an SLA', 'SLA agreement', 'response time', 'ticketing system', 'customer support'], h1: 'What is an SLA and why does a business need one', intro: 'An SLA is a promise of how quickly a customer gets a reply to a request and how quickly the problem is solved. Once the promise is written down it can be measured, and what is measured can be managed.', sections: [
        { h2: 'The two SLA times', p: ['Response time (first response): from the request to the first reply. Resolution time: from the request to closure. They usually differ by priority: a critical problem gets a 1-hour response and 4-hour resolution; a routine question gets 8 hours and 3 working days.'] },
        { h2: 'Priorities and escalation', p: ['Priority is set by the impact of the request: how many customers are affected, whether money is being lost. Escalation hands the ticket to the next level (L1 → L2 → L3) or to a manager when the deadline is breached. An SLA without escalation is just a number.'] },
        { h2: 'Different entitlements per company', p: ['In B2B every customer can have its own support entitlement: “Premium” gets a 30-minute response, “Standard” gets 4 hours. In a ticketing system this is set with templates linked to the company card.'] },
        { h2: 'How to set up SLA in a ticketing system', list: ['A priority table: response and resolution times per level.', 'Escalation rules: a warning at 80% of the deadline, a handover at 100%.', 'Business hours: whether the SLA clock runs only during working time.', 'A report: SLA compliance percentage by agent and queue.'], p: ['In LeadDrive this is configured in the Service Desk settings; more on the “Support and tickets” solution page.'] },
      ] },
    },
  },
  {
    slug: 'sales-funnel-conversion', date: '2026-09-07', solutions: ['sales-crm', 'marketing-automation'],
    copy: {
      az: { title: 'Satış hunisinin konversiyasını necə hesablamalı və harada pul itir', description: 'Satış hunisi mərhələləri, mərhələlər arası konversiya, tipik itki nöqtələri və CRM-də hunini necə oxumalı. Kiçik və orta biznes üçün nümunələrlə.', keywords: ['satış hunisi', 'konversiya hesablama', 'satış analitikası', 'CRM hesabat', 'satış artırmaq'], h1: 'Satış hunisinin konversiyasını necə hesablamalı', intro: 'Huni — müraciətdən ödənişə qədər mərhələlərin siyahısı və hər mərhələdə neçə sövdələşmənin qaldığıdır. Konversiya bir mərhələdən növbətiyə keçənlərin faizidir. Bu rəqəmlər olmadan «satış zəifdir» ifadəsi heç nə demir.', sections: [
        { h2: 'Mərhələləri düzgün təyin edin', p: ['Mərhələ — müştərinin hərəkəti ilə təsdiqlənən vəziyyətdir, menecerin hissi deyil. Yaxşı nümunə: Müraciət → Ehtiyac aydınlaşdı → Təklif göndərildi → Razılaşma → Ödəniş. «Maraqlanır» kimi mərhələ yararsızdır, çünki onu yoxlamaq olmur.'] },
        { h2: 'Konversiyanı hesablayın', p: ['Mərhələ konversiyası = növbəti mərhələyə keçən sövdələşmələr / bu mərhələyə daxil olan sövdələşmələr. Ümumi konversiya = ödənişlər / müraciətlər. Nümunə: 100 müraciət, 60 ehtiyac aydınlaşdı, 30 təklif, 12 razılaşma, 10 ödəniş. Ümumi konversiya 10%; ən böyük itki «ehtiyac → təklif» (50%).'] },
        { h2: 'Harada pul itir', list: ['Müraciət → ehtiyac: cavab gecikir, lid soyuyur. Cavab müddətini ölçün.', 'Ehtiyac → təklif: təklif əl ilə hazırlanır və günlər çəkir. Kataloqdan şablon lazımdır.', 'Təklif → razılaşma: follow-up yoxdur. Tapşırıq və xatırlatma.', 'Razılaşma → ödəniş: faktura gec kəsilir və ya nəzarətsizdir.'] },
        { h2: 'CRM-də hunini necə oxumalı', p: ['Hər həftə üç rəqəmə baxın: mərhələlər üzrə konversiya, mərhələdə orta qalma müddəti və «ilişmiş» sövdələşmələr (14 gündən çox hərəkət yoxdur). LeadDrive-da huni şəlaləsi və proqnoz görüntüləri bu suallara cavab verir; ətraflı «Satış üçün CRM» səhifəsində.'] },
      ] },
      ru: { title: 'Как считать конверсию воронки продаж и где теряются деньги', description: 'Стадии воронки продаж, конверсия между стадиями, типичные точки потерь и как читать воронку в CRM. С примерами для малого и среднего бизнеса.', keywords: ['воронка продаж', 'расчёт конверсии', 'аналитика продаж', 'отчёт CRM', 'увеличить продажи'], h1: 'Как считать конверсию воронки продаж', intro: 'Воронка — это список стадий от обращения до оплаты и количество сделок на каждой из них. Конверсия — процент перешедших с одной стадии на следующую. Без этих цифр фраза «продажи слабые» ничего не значит.', sections: [
        { h2: 'Правильно определите стадии', p: ['Стадия — это состояние, подтверждённое действием клиента, а не ощущением менеджера. Хороший пример: Обращение → Потребность ясна → Предложение отправлено → Согласие → Оплата. Стадия «Интересуется» бесполезна, потому что её нельзя проверить.'] },
        { h2: 'Посчитайте конверсию', p: ['Конверсия стадии = сделки, перешедшие на следующую стадию / сделки, вошедшие в эту стадию. Общая конверсия = оплаты / обращения. Пример: 100 обращений, 60 с ясной потребностью, 30 предложений, 12 согласий, 10 оплат. Общая конверсия 10%; самая большая потеря — «потребность → предложение» (50%).'] },
        { h2: 'Где теряются деньги', list: ['Обращение → потребность: ответ задерживается, лид остывает. Измеряйте время ответа.', 'Потребность → предложение: предложение готовится вручную и занимает дни. Нужен шаблон из каталога.', 'Предложение → согласие: нет follow-up. Задача и напоминание.', 'Согласие → оплата: счёт выставляется поздно или не контролируется.'] },
        { h2: 'Как читать воронку в CRM', p: ['Каждую неделю смотрите три числа: конверсия по стадиям, среднее время на стадии и «застрявшие» сделки (без движения больше 14 дней). В LeadDrive на эти вопросы отвечают водопад воронки и снимки прогноза; подробнее на странице «CRM для продаж».'] },
      ] },
      en: { title: 'How to calculate sales funnel conversion and where the money leaks', description: 'Sales funnel stages, stage-to-stage conversion, typical leak points and how to read the funnel in a CRM. With examples for small and medium businesses.', keywords: ['sales funnel', 'conversion calculation', 'sales analytics', 'CRM report', 'increase sales'], h1: 'How to calculate sales funnel conversion', intro: 'A funnel is a list of stages from request to payment and the number of deals at each one. Conversion is the percentage moving from one stage to the next. Without these numbers the phrase “sales are weak” means nothing.', sections: [
        { h2: 'Define the stages correctly', p: ['A stage is a state confirmed by a customer action, not a manager’s feeling. A good example: Request → Need clarified → Quote sent → Agreement → Payment. A stage called “Interested” is useless because it cannot be verified.'] },
        { h2: 'Calculate the conversion', p: ['Stage conversion = deals that moved to the next stage / deals that entered this stage. Overall conversion = payments / requests. Example: 100 requests, 60 with a clear need, 30 quotes, 12 agreements, 10 payments. Overall conversion is 10%; the biggest loss is “need → quote” (50%).'] },
        { h2: 'Where the money leaks', list: ['Request → need: the reply is late and the lead cools. Measure response time.', 'Need → quote: the quote is built by hand and takes days. You need a catalogue template.', 'Quote → agreement: no follow-up. A task and a reminder.', 'Agreement → payment: the invoice is issued late or not tracked.'] },
        { h2: 'How to read the funnel in a CRM', p: ['Every week look at three numbers: conversion by stage, average time in stage and “stuck” deals (no movement for more than 14 days). In LeadDrive the funnel waterfall and forecast snapshots answer these questions; more on the “Sales CRM” page.'] },
      ] },
    },
  },
  {
    slug: 'field-sales-control', date: '2026-09-07', solutions: ['field-sales-crm', 'crm-for-utilities'],
    copy: {
      az: { title: 'Sahə agentlərinə mikromenecmentsiz necə nəzarət etməli: GPS, foto, KPI', description: 'Sahə komandalarının nəzarəti: marşrut planı, GPS təsdiqli vizitlər, fotohesabatların moderasiyası, KPI reytinqi. Nə işləyir, nə isə komandanı qıcıqlandırır.', keywords: ['sahə satışları', 'agent nəzarəti', 'GPS vizit', 'merçendayzer nəzarəti', 'tibbi nümayəndə'], h1: 'Sahə agentlərinə mikromenecmentsiz necə nəzarət etməli', intro: 'Sahə komandasında iki ekstremal var: tam etibar (və ayın sonunda sürpriz) və ya hər 15 dəqiqədən bir zəng. Üçüncü yol — nəticəni yox, prosesin sübutunu ölçmək: vizit oldu, foto var, tapşırıq bağlandı.', sections: [
        { h2: 'Marşrut günün planıdır', p: ['Agent səhər telefonda günün marşrutunu görür: nöqtələr, ardıcıllıq, hər nöqtədə tapşırıqlar. Rəhbər isə axşam plan/fakt görür. Marşrutsuz nəzarət mümkün deyil, çünki müqayisə ediləcək şey yoxdur.'] },
        { h2: 'GPS və geozona — nəzarət deyil, sübut', p: ['Vizit nöqtədə qeyd olunur; sistem agentin geozonada olduğunu yoxlayır. Bu, agenti «izləmək» üçün deyil, onun işini sübut etmək üçündür — mübahisə olanda agent də qorunur.'] },
        { h2: 'Fotohesabatlar və moderasiya', p: ['Rəf fotosu, promo materialı, quraşdırma — foto tapşırığa bağlanır və moderasiya növbəsinə düşür. Rəhbər təsdiqləyir və ya rədd edir, rədd səbəbi agentə gedir. WhatsApp-a atılan fotolar bir həftədən sonra tapılmır.'] },
        { h2: 'KPI: çəkilər və şəffaflıq', list: ['Tapşırıq icrası — 40%', 'Foto təsdiqi — 30%', 'Marşrut icrası — 30%'], p: ['Çəkilər şirkətə görə dəyişir, əsas odur ki, agent öz reytinqini və hesablama qaydasını görsün. LeadDrive-da KPI Arena bunu göstərir; ətraflı «Sahə satışları» həlli səhifəsində.'] },
      ] },
      ru: { title: 'Как контролировать полевых агентов без микроменеджмента: GPS, фото, KPI', description: 'Контроль полевых команд: план маршрута, визиты с GPS-подтверждением, модерация фотоотчётов, рейтинг KPI. Что работает, а что раздражает команду.', keywords: ['полевые продажи', 'контроль агентов', 'GPS визиты', 'контроль мерчендайзеров', 'медицинский представитель'], h1: 'Как контролировать полевых агентов без микроменеджмента', intro: 'В полевой команде есть две крайности: полное доверие (и сюрприз в конце месяца) или звонок каждые 15 минут. Третий путь — измерять не ощущения, а доказательства процесса: визит был, фото есть, задача закрыта.', sections: [
        { h2: 'Маршрут — это план дня', p: ['Утром агент видит в телефоне маршрут: точки, порядок, задачи на каждой точке. Вечером руководитель видит план/факт. Без маршрута контроль невозможен, потому что не с чем сравнивать.'] },
        { h2: 'GPS и геозона — не слежка, а доказательство', p: ['Визит регистрируется на точке; система проверяет, что агент внутри геозоны. Это нужно не чтобы «следить», а чтобы подтвердить работу — при споре агент тоже защищён.'] },
        { h2: 'Фотоотчёты и модерация', p: ['Фото полки, промо-материала, установки — фото привязывается к задаче и попадает в очередь модерации. Руководитель подтверждает или отклоняет, причина отклонения уходит агенту. Фото, брошенные в WhatsApp, через неделю не найти.'] },
        { h2: 'KPI: веса и прозрачность', list: ['Исполнение задач — 40%', 'Подтверждение фото — 30%', 'Исполнение маршрута — 30%'], p: ['Веса зависят от компании, главное, чтобы агент видел свой рейтинг и правило расчёта. В LeadDrive это показывает KPI Arena; подробнее на странице решения «Полевые продажи».'] },
      ] },
      en: { title: 'How to control field agents without micromanagement: GPS, photos, KPI', description: 'Controlling field teams: route plan, GPS-confirmed visits, photo report moderation, KPI ranking. What works and what annoys the team.', keywords: ['field sales', 'agent control', 'GPS visits', 'merchandiser control', 'medical representative'], h1: 'How to control field agents without micromanagement', intro: 'A field team has two extremes: full trust (and a surprise at month end) or a call every 15 minutes. The third way is to measure evidence of the process rather than feelings: the visit happened, the photo exists, the task is closed.', sections: [
        { h2: 'The route is the plan for the day', p: ['In the morning the agent sees the route on the phone: points, order, tasks at each point. In the evening the manager sees plan versus fact. Without a route there is no control, because there is nothing to compare against.'] },
        { h2: 'GPS and geofence: proof, not surveillance', p: ['A visit is checked in at the point; the system verifies the agent is inside the geofence. This is not about “tracking” but about proving the work; in a dispute the agent is protected too.'] },
        { h2: 'Photo reports and moderation', p: ['A shelf photo, promo material, an installation: the photo is attached to the task and goes to the moderation queue. The manager approves or rejects; the rejection reason goes to the agent. Photos dumped into WhatsApp cannot be found a week later.'] },
        { h2: 'KPI: weights and transparency', list: ['Task execution: 40%', 'Photo approval: 30%', 'Route execution: 30%'], p: ['Weights depend on the company; what matters is that the agent sees their ranking and the calculation rule. In LeadDrive the KPI Arena shows it; more on the “Field sales” solution page.'] },
      ] },
    },
  },
];
