import type { Lang } from './product-map';

export type CompareRow = { feature: string; leaddrive: string; other: string };
export type CompareCopy = { title: string; description: string; keywords: string[]; h1: string; h2: string; intro: string; otherName: string; rows: CompareRow[]; when: string[]; whenOther: string[]; faq: [string, string][]; note: string };
export type Comparison = { slug: string; solutions: string[]; copy: Record<Lang, CompareCopy> };

export const COMPARE_COPY: Record<Lang, { label: string; home: string; feature: string; whenTitle: string; whenOtherTitle: string; faq: string; demo: string; others: string; solutions: string }> = {
  ru: { label: 'Сравнения', home: 'Главная', feature: 'Критерий', whenTitle: 'Когда подойдёт LeadDrive', whenOtherTitle: 'Когда стоит смотреть на', faq: 'Частые вопросы', demo: 'Сравнить на демо', others: 'Другие сравнения', solutions: 'Решения' },
  az: { label: 'Müqayisələr', home: 'Ana səhifə', feature: 'Meyar', whenTitle: 'LeadDrive nə vaxt uyğundur', whenOtherTitle: 'Nə vaxt baxmağa dəyər:', faq: 'Tez-tez verilən suallar', demo: 'Demoda müqayisə edək', others: 'Digər müqayisələr', solutions: 'Həllər' },
  en: { label: 'Comparisons', home: 'Home', feature: 'Criterion', whenTitle: 'When LeadDrive fits', whenOtherTitle: 'When to look at', faq: 'Frequent questions', demo: 'Compare on a demo', others: 'Other comparisons', solutions: 'Solutions' },
};

const NOTE = {
  ru: 'Сведения о другой системе взяты из её публичной документации и сайта на момент публикации и могут меняться. Сведения о LeadDrive соответствуют экранам, проверенным в ходе аудита продукта. Если вы заметили неточность, напишите нам в WhatsApp, и мы исправим.',
  az: 'Digər sistem haqqında məlumatlar dərc tarixinə onun açıq sənədlərindən və saytından götürülüb və dəyişə bilər. LeadDrive haqqında məlumatlar məhsul auditində yoxlanılmış ekranlara uyğundur. Qeyri-dəqiqlik görsəniz, WhatsApp-a yazın, düzəldərik.',
  en: 'Information about the other system is taken from its public documentation and website at the time of publication and may change. Information about LeadDrive matches screens verified during the product audit. If you spot an inaccuracy, write to us on WhatsApp and we will fix it.',
};

export const COMPARISONS: Comparison[] = [
  {
    slug: 'leaddrive-vs-bitrix24', solutions: ['whatsapp-crm', 'sales-crm', 'invoicing-finance'],
    copy: {
      az: { title: 'LeadDrive və Bitrix24: Azərbaycan biznesi üçün CRM müqayisəsi', description: 'LeadDrive CRM ilə Bitrix24-ün dürüst müqayisəsi: WhatsApp və Instagram, Azərbaycan dili, fakturalar və müqavilələr, sahə satışları, AI, tətbiq və dəstək. Hansı hallarda hansı sistem uyğundur.', keywords: ['Bitrix24 alternativ', 'Bitrix24 Azərbaycan', 'LeadDrive vs Bitrix24', 'Bitrix24 müqayisə', 'CRM müqayisə'], h1: 'LeadDrive və Bitrix24:', h2: 'hansı CRM sizin komandaya uyğundur.', intro: 'Bitrix24 — geniş korporativ portal: CRM, tapşırıqlar, sənədlər, çat, sayt qurucu. LeadDrive — müştəri ilə işə fokuslanmış CRM: müraciətdən fakturaya və dəstəyə qədər, Azərbaycan bazarı üçün. Aşağıdakı cədvəl fərqləri konkret meyarlar üzrə göstərir.', otherName: 'Bitrix24', rows: [
        { feature: 'Fokus', leaddrive: 'Müştəri ilə iş: satış, ünsiyyət, dəstək, müqavilələr, fakturalar, sahə', other: 'Korporativ portal: CRM + tapşırıqlar, sənədlər, çat, sayt qurucu' },
        { feature: 'Azərbaycan dili', leaddrive: 'İnterfeys və dəstək Azərbaycan dilində, yerli komanda', other: 'Çoxdilli interfeys; Azərbaycan dili və yerli dəstək partnyorlar vasitəsilə' },
        { feature: 'WhatsApp, Instagram, Telegram', leaddrive: 'Vahid Inbox, kanal kataloqunda addım-addım qoşulma, AI rejimi hər kanal üçün', other: 'Açıq xətlər (Open Channels) və konnektorlar vasitəsilə, bəzi kanallar bazar tətbiqləri ilə' },
        { feature: 'Fakturalar və müqavilələr', leaddrive: 'Faktura reyestri, xatırlatma zənciri, müqavilə şablonları, təsdiq marşrutu, e-imza — CRM-in içində', other: 'Faktura və sənəd funksiyaları var; müqavilə dövriyyəsi əlavə konfiqurasiya və ya tətbiqlərlə' },
        { feature: 'Sahə satışları', leaddrive: 'Marşrutlar, GPS vizitlər, fotohesabat moderasiyası, KPI Arena', other: 'Standart modul kimi yoxdur; bazar tətbiqləri ilə' },
        { feature: 'AI', leaddrive: 'AI agent kanallarda, Da Vinci məsləhətçi, 14 avtopilot ssenarisi, üç həvalə səviyyəsi, gündəlik büdcə', other: 'CoPilot köməkçi: mətn, zəng transkripti, tapşırıq — tarif planına görə' },
        { feature: 'Sahə bölmələri', leaddrive: 'Səhiyyə, sığorta, dövlət sektoru, media, enerji — hazır reyestrlər', other: 'Universal CRM; sahə həlləri partnyorlar tərəfindən' },
        { feature: 'Tətbiq', leaddrive: 'Şirkətlə birbaşa, prosesin təsviri və pilot şöbə ilə', other: 'Özbaşına və ya sertifikatlı partnyorla' },
        { feature: 'Qiymət', leaddrive: 'Şirkət üçün fərdi şərtlər, WhatsApp-da müzakirə', other: 'Pulsuz plan və istifadəçi/plan üzrə tariflər' },
      ], when: ['Müraciətlərin əksəriyyəti WhatsApp və Instagram-dan gəlir.', 'Satış, faktura və müqavilə eyni müştəri kartında olmalıdır.', 'Sahə komandası və ya sahə bölməsi (klinika, sığorta, dövlət) var.', 'Azərbaycan dilində dəstək və tətbiq lazımdır.'], whenOther: ['Şirkətə CRM-dən çox korporativ portal (tapşırıqlar, sənədlər, daxili çat) lazımdır.', 'Komanda artıq Bitrix24 ekosistemində işləyir.', 'Pulsuz plan ilə başlamaq istəyirsiniz.'], faq: [['Bitrix24-dən LeadDrive-a keçmək olar?', 'Bəli. Kontaktlar, şirkətlər və sövdələşmələr Excel/CSV vasitəsilə idxal olunur, dublikatlar birləşdirilir. Demoda öz faylınızla yoxlaya bilərsiniz.'], ['LeadDrive-da tapşırıqlar və layihələr var?', 'Bəli, CRM əsasında tapşırıqlar və layihələr var, amma LeadDrive korporativ portal deyil: daxili sosial şəbəkə və sayt qurucu yoxdur.'], ['Hansı sistem daha ucuzdur?', 'Bu, istifadəçi sayından və lazım olan modullardan asılıdır. LeadDrive sabit tarif dərc etmir, şərtlər şirkətə görə müzakirə olunur.']], note: NOTE.az },
      ru: { title: 'LeadDrive и Bitrix24: сравнение CRM для бизнеса в Азербайджане', description: 'Честное сравнение LeadDrive CRM и Битрикс24: WhatsApp и Instagram, азербайджанский язык, счета и договоры, полевые продажи, AI, внедрение и поддержка. В каких случаях какая система подходит.', keywords: ['альтернатива Битрикс24', 'Битрикс24 Азербайджан', 'LeadDrive vs Bitrix24', 'сравнение Битрикс24', 'сравнение CRM'], h1: 'LeadDrive и Bitrix24:', h2: 'какая CRM подходит вашей команде.', intro: 'Bitrix24 — широкий корпоративный портал: CRM, задачи, документы, чат, конструктор сайтов. LeadDrive — CRM, сфокусированная на работе с клиентом: от обращения до счёта и поддержки, для рынка Азербайджана. Таблица ниже показывает различия по конкретным критериям.', otherName: 'Bitrix24', rows: [
        { feature: 'Фокус', leaddrive: 'Работа с клиентом: продажи, коммуникации, поддержка, договоры, счета, поле', other: 'Корпоративный портал: CRM + задачи, документы, чат, конструктор сайтов' },
        { feature: 'Азербайджанский язык', leaddrive: 'Интерфейс и поддержка на азербайджанском, локальная команда', other: 'Многоязычный интерфейс; азербайджанский и локальная поддержка через партнёров' },
        { feature: 'WhatsApp, Instagram, Telegram', leaddrive: 'Единый Inbox, пошаговое подключение в каталоге каналов, режим AI для каждого канала', other: 'Через открытые линии и коннекторы, часть каналов через приложения маркетплейса' },
        { feature: 'Счета и договоры', leaddrive: 'Реестр счетов, цепочка напоминаний, шаблоны договоров, маршрут согласования, e-подпись — внутри CRM', other: 'Есть счета и документы; договорной документооборот через дополнительную настройку или приложения' },
        { feature: 'Полевые продажи', leaddrive: 'Маршруты, GPS-визиты, модерация фотоотчётов, KPI Arena', other: 'Нет в стандартном модуле; через приложения маркетплейса' },
        { feature: 'AI', leaddrive: 'AI-агент в каналах, советник Da Vinci, 14 сценариев автопилота, три уровня делегирования, дневной бюджет', other: 'Помощник CoPilot: тексты, транскрипты звонков, задачи — в зависимости от тарифа' },
        { feature: 'Отраслевые разделы', leaddrive: 'Медицина, страхование, госсектор, медиа, энергетика — готовые реестры', other: 'Универсальная CRM; отраслевые решения от партнёров' },
        { feature: 'Внедрение', leaddrive: 'Напрямую с компанией, с описанием процесса и пилотным отделом', other: 'Самостоятельно или с сертифицированным партнёром' },
        { feature: 'Цена', leaddrive: 'Индивидуальные условия для компании, обсуждаются в WhatsApp', other: 'Бесплатный план и тарифы по пользователям/плану' },
      ], when: ['Большинство обращений приходит из WhatsApp и Instagram.', 'Продажи, счета и договоры должны быть в одной карточке клиента.', 'Есть полевая команда или отраслевой раздел (клиника, страхование, госсектор).', 'Нужны поддержка и внедрение на азербайджанском языке.'], whenOther: ['Компании нужен корпоративный портал больше, чем CRM (задачи, документы, внутренний чат).', 'Команда уже работает в экосистеме Bitrix24.', 'Хочется начать с бесплатного плана.'], faq: [['Можно ли перейти с Bitrix24 на LeadDrive?', 'Да. Контакты, компании и сделки импортируются через Excel/CSV, дубликаты объединяются. На демо можно проверить на вашем файле.'], ['Есть ли в LeadDrive задачи и проекты?', 'Да, в основе CRM есть задачи и проекты, но LeadDrive не корпоративный портал: внутренней соцсети и конструктора сайтов нет.'], ['Какая система дешевле?', 'Зависит от числа пользователей и нужных модулей. LeadDrive не публикует фиксированные тарифы, условия обсуждаются под компанию.']], note: NOTE.ru },
      en: { title: 'LeadDrive vs Bitrix24: CRM comparison for business in Azerbaijan', description: 'An honest comparison of LeadDrive CRM and Bitrix24: WhatsApp and Instagram, Azerbaijani language, invoices and contracts, field sales, AI, implementation and support. Which system fits which case.', keywords: ['Bitrix24 alternative', 'Bitrix24 Azerbaijan', 'LeadDrive vs Bitrix24', 'Bitrix24 comparison', 'CRM comparison'], h1: 'LeadDrive vs Bitrix24:', h2: 'which CRM fits your team.', intro: 'Bitrix24 is a broad corporate portal: CRM, tasks, documents, chat, a website builder. LeadDrive is a CRM focused on customer work: from request to invoice and support, for the Azerbaijani market. The table below shows the differences by concrete criteria.', otherName: 'Bitrix24', rows: [
        { feature: 'Focus', leaddrive: 'Customer work: sales, communication, support, contracts, invoices, field', other: 'Corporate portal: CRM plus tasks, documents, chat, website builder' },
        { feature: 'Azerbaijani language', leaddrive: 'Interface and support in Azerbaijani, a local team', other: 'Multilingual interface; Azerbaijani and local support through partners' },
        { feature: 'WhatsApp, Instagram, Telegram', leaddrive: 'One inbox, step-by-step setup in the channel catalogue, an AI mode per channel', other: 'Through Open Channels and connectors; some channels via marketplace apps' },
        { feature: 'Invoices and contracts', leaddrive: 'Invoice registry, reminder chain, contract templates, approval route, e-signature inside the CRM', other: 'Invoices and documents exist; contract workflow needs extra configuration or apps' },
        { feature: 'Field sales', leaddrive: 'Routes, GPS visits, photo report moderation, KPI Arena', other: 'Not a standard module; via marketplace apps' },
        { feature: 'AI', leaddrive: 'AI agent in channels, Da Vinci advisor, 14 autopilot scenarios, three delegation levels, daily budget', other: 'CoPilot assistant: texts, call transcripts, tasks, depending on the plan' },
        { feature: 'Industry sections', leaddrive: 'Healthcare, insurance, public sector, media, energy: ready registries', other: 'A universal CRM; industry solutions from partners' },
        { feature: 'Implementation', leaddrive: 'Directly with the company, with a process description and a pilot department', other: 'Self-service or with a certified partner' },
        { feature: 'Price', leaddrive: 'Individual terms per company, discussed on WhatsApp', other: 'A free plan and per-user/plan tiers' },
      ], when: ['Most requests come from WhatsApp and Instagram.', 'Sales, invoices and contracts must live on one customer card.', 'You have a field team or an industry section (clinic, insurance, public sector).', 'You need support and implementation in Azerbaijani.'], whenOther: ['The company needs a corporate portal more than a CRM (tasks, documents, internal chat).', 'The team already works in the Bitrix24 ecosystem.', 'You want to start on a free plan.'], faq: [['Can we move from Bitrix24 to LeadDrive?', 'Yes. Contacts, companies and deals are imported through Excel/CSV and duplicates are merged. You can test it with your own file on the demo.'], ['Does LeadDrive have tasks and projects?', 'Yes, the CRM core has tasks and projects, but LeadDrive is not a corporate portal: there is no internal social network or website builder.'], ['Which system is cheaper?', 'It depends on the number of users and the modules you need. LeadDrive does not publish fixed tiers; terms are discussed per company.']], note: NOTE.en },
    },
  },
  {
    slug: 'leaddrive-vs-amocrm', solutions: ['whatsapp-crm', 'sales-crm', 'support-helpdesk-crm'],
    copy: {
      az: { title: 'LeadDrive və amoCRM: messencer satışları üçün CRM müqayisəsi', description: 'LeadDrive CRM ilə amoCRM-in müqayisəsi: WhatsApp və Instagram satışları, satışdan sonrakı proseslər, dəstək və tiketlər, fakturalar, sahə komandaları, AI, Azərbaycan dili.', keywords: ['amoCRM alternativ', 'amoCRM Azərbaycan', 'LeadDrive vs amoCRM', 'amoCRM müqayisə', 'messencer CRM'], h1: 'LeadDrive və amoCRM:', h2: 'messencerdən sonra nə olur.', intro: 'amoCRM messencerlərdə satış üçün güclü sistemdir: boru xətti, çatlar, botlar. LeadDrive eyni Inbox-u verir, amma satışdan sonra davam edir: tiketlər və SLA, fakturalar, müqavilələr, sahə komandaları. Fərq — şirkətin prosesinin harada bitdiyində.', otherName: 'amoCRM', rows: [
        { feature: 'Fokus', leaddrive: 'Tam müştəri dövrü: satış, dəstək, müqavilə, faktura, sahə', other: 'Satış boru xətti və messencerlərdə ünsiyyət' },
        { feature: 'Messencerlər', leaddrive: 'WhatsApp, Instagram, Telegram, Messenger, VK, TikTok, sayt çatı, SMS — vahid Inbox', other: 'Geniş messencer dəstəyi, «Salesbot» botlar' },
        { feature: 'Dəstək və tiketlər', leaddrive: 'Service Desk: SLA, eskalasiya L1–L3, bacarıq üzrə növbələr, bilik bazası, müştəri portalı', other: 'Ayrı tiket modulu yoxdur; dəstək satış boru xətti və çatlarla' },
        { feature: 'Fakturalar və müqavilələr', leaddrive: 'Faktura reyestri, xatırlatma zənciri, müqavilə şablonları, təsdiq, e-imza', other: 'Əsas fakturalar; müqavilə dövriyyəsi inteqrasiyalarla' },
        { feature: 'Sahə satışları', leaddrive: 'Marşrutlar, GPS vizitlər, fotohesabatlar, KPI Arena', other: 'Yoxdur' },
        { feature: 'AI', leaddrive: 'AI agent, Da Vinci məsləhətçi, 14 avtopilot ssenarisi, həvalə səviyyələri', other: 'AI funksiyaları çatlarda və botlarda' },
        { feature: 'Azərbaycan dili və dəstək', leaddrive: 'Interfeys və yerli dəstək Azərbaycan dilində', other: 'Rus və ingilis interfeys; yerli dəstək partnyorlarla' },
        { feature: 'Hüquqlar və audit', leaddrive: 'Modul × rol matrisi, sahə səviyyəsində hüquqlar, 2FA, audit jurnalı', other: 'Rollar və hüquqlar; audit imkanları plana görə' },
        { feature: 'Qiymət', leaddrive: 'Şirkət üçün fərdi şərtlər', other: 'İstifadəçi üzrə aylıq tariflər' },
      ], when: ['Satışdan sonra dəstək, faktura və müqavilə eyni sistemdə olmalıdır.', 'Sahə komandası və ya sahə bölməsi var.', 'SLA ilə tiketlər lazımdır.', 'Azərbaycan dilində dəstək vacibdir.'], whenOther: ['Prosesin hamısı messencerdə satışdır və satışdan sonra CRM-də heç nə lazım deyil.', 'Komanda amoCRM botlarına və inteqrasiyalarına öyrəşib.'], faq: [['LeadDrive-da messencer botları var?', 'AI agent və avtomatlaşdırma qaydaları var: kanal üzrə rejim, açar sözlərlə ötürmə, iş saatları mesajı, avtopilot ssenariləri. Klassik «düymə» bot konstruktoru fərqli yanaşmadır.'], ['amoCRM-dən köçürmək olar?', 'Bəli, kontaktlar, şirkətlər və sövdələşmələr CSV ilə idxal olunur; boru xətti mərhələləri tətbiq zamanı uyğunlaşdırılır.'], ['Yalnız satış üçün LeadDrive çox böyükdür?', 'Modullar mərhələ-mərhələ qoşulur: satış və Inbox ilə başlamaq, sonra dəstək və maliyyəni əlavə etmək olar.']], note: NOTE.az },
      ru: { title: 'LeadDrive и amoCRM: сравнение CRM для продаж в мессенджерах', description: 'Сравнение LeadDrive CRM и amoCRM: продажи в WhatsApp и Instagram, процессы после продажи, поддержка и тикеты, счета, полевые команды, AI, азербайджанский язык.', keywords: ['альтернатива amoCRM', 'amoCRM Азербайджан', 'LeadDrive vs amoCRM', 'сравнение amoCRM', 'CRM для мессенджеров'], h1: 'LeadDrive и amoCRM:', h2: 'что происходит после мессенджера.', intro: 'amoCRM — сильная система для продаж в мессенджерах: воронка, чаты, боты. LeadDrive даёт такой же Inbox, но продолжает после продажи: тикеты и SLA, счета, договоры, полевые команды. Разница в том, где заканчивается процесс вашей компании.', otherName: 'amoCRM', rows: [
        { feature: 'Фокус', leaddrive: 'Полный цикл клиента: продажи, поддержка, договор, счёт, поле', other: 'Воронка продаж и общение в мессенджерах' },
        { feature: 'Мессенджеры', leaddrive: 'WhatsApp, Instagram, Telegram, Messenger, VK, TikTok, чат на сайте, SMS — единый Inbox', other: 'Широкая поддержка мессенджеров, боты Salesbot' },
        { feature: 'Поддержка и тикеты', leaddrive: 'Service Desk: SLA, эскалация L1–L3, очереди по навыкам, база знаний, клиентский портал', other: 'Отдельного модуля тикетов нет; поддержка через воронку и чаты' },
        { feature: 'Счета и договоры', leaddrive: 'Реестр счетов, цепочка напоминаний, шаблоны договоров, согласование, e-подпись', other: 'Базовые счета; договорной документооборот через интеграции' },
        { feature: 'Полевые продажи', leaddrive: 'Маршруты, GPS-визиты, фотоотчёты, KPI Arena', other: 'Нет' },
        { feature: 'AI', leaddrive: 'AI-агент, советник Da Vinci, 14 сценариев автопилота, уровни делегирования', other: 'AI-функции в чатах и ботах' },
        { feature: 'Азербайджанский язык и поддержка', leaddrive: 'Интерфейс и локальная поддержка на азербайджанском', other: 'Русский и английский интерфейс; локальная поддержка через партнёров' },
        { feature: 'Права и аудит', leaddrive: 'Матрица модуль × роль, права на уровне полей, 2FA, журнал аудита', other: 'Роли и права; возможности аудита зависят от плана' },
        { feature: 'Цена', leaddrive: 'Индивидуальные условия для компании', other: 'Месячные тарифы за пользователя' },
      ], when: ['После продажи поддержка, счёт и договор должны быть в той же системе.', 'Есть полевая команда или отраслевой раздел.', 'Нужны тикеты с SLA.', 'Важна поддержка на азербайджанском.'], whenOther: ['Весь процесс — это продажа в мессенджере, и после продажи в CRM ничего не нужно.', 'Команда привыкла к ботам и интеграциям amoCRM.'], faq: [['Есть ли в LeadDrive боты для мессенджеров?', 'Есть AI-агент и правила автоматизации: режим по каналу, передача по ключевым словам, сообщение в нерабочее время, сценарии автопилота. Классический конструктор «кнопочных» ботов — другой подход.'], ['Можно ли перенести данные из amoCRM?', 'Да, контакты, компании и сделки импортируются через CSV; стадии воронки сопоставляются при внедрении.'], ['Не слишком ли велика LeadDrive только для продаж?', 'Модули подключаются поэтапно: можно начать с продаж и Inbox, а поддержку и финансы добавить позже.']], note: NOTE.ru },
      en: { title: 'LeadDrive vs amoCRM (Kommo): CRM comparison for messenger sales', description: 'A comparison of LeadDrive CRM and amoCRM (Kommo): WhatsApp and Instagram sales, post-sale processes, support and tickets, invoices, field teams, AI, Azerbaijani language.', keywords: ['amoCRM alternative', 'Kommo alternative', 'LeadDrive vs amoCRM', 'amoCRM comparison', 'messenger CRM'], h1: 'LeadDrive vs amoCRM:', h2: 'what happens after the messenger.', intro: 'amoCRM (Kommo) is a strong system for selling in messengers: pipeline, chats, bots. LeadDrive gives the same inbox but continues after the sale: tickets and SLA, invoices, contracts, field teams. The difference is where your company’s process ends.', otherName: 'amoCRM', rows: [
        { feature: 'Focus', leaddrive: 'The full customer cycle: sales, support, contract, invoice, field', other: 'Sales pipeline and messenger communication' },
        { feature: 'Messengers', leaddrive: 'WhatsApp, Instagram, Telegram, Messenger, VK, TikTok, website chat, SMS in one inbox', other: 'Broad messenger support, Salesbot bots' },
        { feature: 'Support and tickets', leaddrive: 'Service Desk: SLA, L1–L3 escalation, skill queues, knowledge base, customer portal', other: 'No separate ticket module; support through the pipeline and chats' },
        { feature: 'Invoices and contracts', leaddrive: 'Invoice registry, reminder chain, contract templates, approval, e-signature', other: 'Basic invoices; contract workflow through integrations' },
        { feature: 'Field sales', leaddrive: 'Routes, GPS visits, photo reports, KPI Arena', other: 'None' },
        { feature: 'AI', leaddrive: 'AI agent, Da Vinci advisor, 14 autopilot scenarios, delegation levels', other: 'AI features in chats and bots' },
        { feature: 'Azerbaijani language and support', leaddrive: 'Interface and local support in Azerbaijani', other: 'Russian and English interface; local support via partners' },
        { feature: 'Rights and audit', leaddrive: 'Module × role matrix, field-level rights, 2FA, audit log', other: 'Roles and rights; audit features depend on the plan' },
        { feature: 'Price', leaddrive: 'Individual terms per company', other: 'Monthly per-user tiers' },
      ], when: ['After the sale, support, invoice and contract must be in the same system.', 'You have a field team or an industry section.', 'You need tickets with SLA.', 'Support in Azerbaijani matters.'], whenOther: ['The whole process is selling in a messenger and nothing is needed in the CRM after the sale.', 'The team is used to amoCRM bots and integrations.'], faq: [['Does LeadDrive have messenger bots?', 'There is an AI agent and automation rules: a mode per channel, keyword handover, an out-of-hours message, autopilot scenarios. A classic “button” bot builder is a different approach.'], ['Can data be migrated from amoCRM?', 'Yes, contacts, companies and deals are imported via CSV; pipeline stages are mapped during implementation.'], ['Is LeadDrive too big for sales only?', 'Modules are switched on in stages: you can start with sales and the inbox and add support and finance later.']], note: NOTE.en },
    },
  },
  {
    slug: 'crm-vs-excel', solutions: ['sales-crm', 'invoicing-finance', 'whatsapp-crm'],
    copy: {
      az: { title: 'CRM və ya Excel: cədvəllər nə vaxt kifayət etmir', description: 'Excel və Google Sheets ilə CRM-in müqayisəsi: müştəri bazası, boru xətti, messencerlər, xatırlatmalar, hüquqlar, hesabatlar. Cədvəldən CRM-ə keçmək vaxtının əlamətləri.', keywords: ['CRM və ya Excel', 'Excel müştəri bazası', 'Google Sheets CRM', 'cədvəldən CRM-ə', 'CRM nə vaxt lazımdır'], h1: 'CRM və ya Excel:', h2: 'cədvəl nə vaxt kifayət etmir.', intro: 'Excel pulsuzdur, hamı bilir və ilk 50 müştəriyə qədər əla işləyir. Sonra cədvəl yenilənmir, kimin nə etdiyi bilinmir, messencerlər isə ayrı yaşayır. Aşağıdakı cədvəl fərqi dürüst göstərir — Excel-in üstün olduğu yerlər də daxil.', otherName: 'Excel / Google Sheets', rows: [
        { feature: 'Başlanğıc', leaddrive: 'Tətbiq və prosesin təsviri lazımdır', other: 'Dərhal, pulsuz' },
        { feature: 'Müştəri kartı və tarixçə', leaddrive: 'Bütün zənglər, yazışmalar, sənədlər, tapşırıqlar bir kartda', other: 'Sətir; tarixçə şərh xanasında və ya yoxdur' },
        { feature: 'Messencerlər', leaddrive: 'WhatsApp, Instagram, Telegram Inbox-da, söhbət kartla əlaqəli', other: 'Yoxdur; yazışma telefonda qalır' },
        { feature: 'Boru xətti və proqnoz', leaddrive: 'Mərhələlər, konversiya, proqnoz görüntüləri, şəlalə', other: 'Əl ilə status sütunu; pivot ilə hesabat' },
        { feature: 'Xatırlatmalar', leaddrive: 'Tapşırıqlar, avtomatlaşdırma qaydaları, AI ssenariləri', other: 'Yoxdur (təqvimə əl ilə)' },
        { feature: 'Fakturalar', leaddrive: 'Reyestr, statuslar, xatırlatma zənciri, PDF', other: 'Ayrı cədvəl və ya Word' },
        { feature: 'Hüquqlar', leaddrive: 'Rollar, sahə səviyyəsində hüquqlar, audit jurnalı', other: 'Fayl səviyyəsində; kim nəyi dəyişib görünmür' },
        { feature: 'Bir neçə istifadəçi', leaddrive: 'Məsul şəxslər, növbələr, eyni vaxtda iş', other: 'Google Sheets-də mümkündür, amma konfliktlər və silinmələr' },
        { feature: 'Xərc', leaddrive: 'Abunə / fərdi şərtlər', other: 'Pulsuz' },
      ], when: ['Ayda 50-dən çox müraciət var.', 'Müştərilər WhatsApp və Instagram-dan yazır.', 'İki və daha çox əməkdaş eyni müştərilərlə işləyir.', 'Fakturalar və borclar nəzarətdən çıxır.'], whenOther: ['Bir nəfər, 20–30 müştəri, müraciətlər nadirdir.', 'Proses hələ formalaşmayıb və hər həftə dəyişir.', 'Büdcə sıfırdır və bu, hələlik dəyişməyəcək.'], faq: [['Excel bazasını CRM-ə köçürmək olar?', 'Bəli, idxal CSV/Excel ilə, sahələr uyğunlaşdırılır, dublikatlar birləşdirilir. Tarixçə şərhləri qeyd kimi köçürülür.'], ['CRM-ə keçid nə qədər çəkir?', 'Kiçik komanda üçün pilot 2–4 həftədir: proses təsviri, idxal, kanal qoşulması, təlim.'], ['Excel-i tamamilə atmaq lazımdır?', 'Xeyr. CRM hesabatları Excel-ə ixrac olunur; analitika üçün cədvəllər qalır, müştəri ilə iş isə CRM-də aparılır.']], note: NOTE.az },
      ru: { title: 'CRM или Excel: когда таблиц уже не хватает', description: 'Сравнение Excel и Google Sheets с CRM: клиентская база, воронка, мессенджеры, напоминания, права, отчёты. Признаки, что пора переходить с таблиц на CRM.', keywords: ['CRM или Excel', 'клиентская база в Excel', 'Google Sheets CRM', 'с таблиц на CRM', 'когда нужна CRM'], h1: 'CRM или Excel:', h2: 'когда таблицы уже не хватает.', intro: 'Excel бесплатный, все его знают, и до первых 50 клиентов он работает отлично. Потом таблица перестаёт обновляться, непонятно, кто что делает, а мессенджеры живут отдельно. Таблица ниже честно показывает разницу, включая места, где Excel лучше.', otherName: 'Excel / Google Sheets', rows: [
        { feature: 'Старт', leaddrive: 'Нужны внедрение и описание процесса', other: 'Сразу, бесплатно' },
        { feature: 'Карточка клиента и история', leaddrive: 'Все звонки, переписка, документы, задачи в одной карточке', other: 'Строка; история в ячейке комментария или отсутствует' },
        { feature: 'Мессенджеры', leaddrive: 'WhatsApp, Instagram, Telegram в Inbox, беседа связана с карточкой', other: 'Нет; переписка остаётся в телефоне' },
        { feature: 'Воронка и прогноз', leaddrive: 'Стадии, конверсия, снимки прогноза, водопад', other: 'Ручной столбец статуса; отчёт через сводные таблицы' },
        { feature: 'Напоминания', leaddrive: 'Задачи, правила автоматизации, AI-сценарии', other: 'Нет (вручную в календарь)' },
        { feature: 'Счета', leaddrive: 'Реестр, статусы, цепочка напоминаний, PDF', other: 'Отдельная таблица или Word' },
        { feature: 'Права', leaddrive: 'Роли, права на уровне полей, журнал аудита', other: 'На уровне файла; не видно, кто что изменил' },
        { feature: 'Несколько пользователей', leaddrive: 'Ответственные, очереди, одновременная работа', other: 'В Google Sheets возможно, но конфликты и случайные удаления' },
        { feature: 'Стоимость', leaddrive: 'Подписка / индивидуальные условия', other: 'Бесплатно' },
      ], when: ['Больше 50 обращений в месяц.', 'Клиенты пишут в WhatsApp и Instagram.', 'Два и больше сотрудников работают с одними клиентами.', 'Счета и долги выходят из-под контроля.'], whenOther: ['Один человек, 20–30 клиентов, обращения редкие.', 'Процесс ещё не сложился и меняется каждую неделю.', 'Бюджет нулевой, и пока это не изменится.'], faq: [['Можно ли перенести базу из Excel в CRM?', 'Да, импорт через CSV/Excel, поля сопоставляются, дубликаты объединяются. Комментарии из истории переносятся как заметки.'], ['Сколько занимает переход на CRM?', 'Для небольшой команды пилот занимает 2–4 недели: описание процесса, импорт, подключение каналов, обучение.'], ['Нужно ли полностью отказаться от Excel?', 'Нет. Отчёты CRM выгружаются в Excel; таблицы остаются для аналитики, а работа с клиентом ведётся в CRM.']], note: NOTE.ru },
      en: { title: 'CRM vs Excel: when spreadsheets are no longer enough', description: 'A comparison of Excel and Google Sheets with a CRM: customer base, funnel, messengers, reminders, rights, reports. Signs it is time to move from spreadsheets to a CRM.', keywords: ['CRM vs Excel', 'customer database in Excel', 'Google Sheets CRM', 'from spreadsheets to CRM', 'when you need a CRM'], h1: 'CRM vs Excel:', h2: 'when the spreadsheet is no longer enough.', intro: 'Excel is free, everyone knows it, and up to the first 50 customers it works great. Then the sheet stops being updated, nobody knows who does what, and messengers live apart. The table below shows the difference honestly, including where Excel is better.', otherName: 'Excel / Google Sheets', rows: [
        { feature: 'Getting started', leaddrive: 'Needs implementation and a process description', other: 'Immediately, for free' },
        { feature: 'Customer card and history', leaddrive: 'Every call, message, document and task on one card', other: 'A row; history in a comment cell or missing' },
        { feature: 'Messengers', leaddrive: 'WhatsApp, Instagram, Telegram in the inbox, the chat linked to the card', other: 'None; the chat stays on the phone' },
        { feature: 'Funnel and forecast', leaddrive: 'Stages, conversion, forecast snapshots, waterfall', other: 'A manual status column; reports via pivot tables' },
        { feature: 'Reminders', leaddrive: 'Tasks, automation rules, AI scenarios', other: 'None (by hand in a calendar)' },
        { feature: 'Invoices', leaddrive: 'Registry, statuses, reminder chain, PDF', other: 'A separate sheet or Word' },
        { feature: 'Rights', leaddrive: 'Roles, field-level rights, audit log', other: 'File level; no visibility of who changed what' },
        { feature: 'Several users', leaddrive: 'Owners, queues, simultaneous work', other: 'Possible in Google Sheets, but conflicts and accidental deletions' },
        { feature: 'Cost', leaddrive: 'Subscription / individual terms', other: 'Free' },
      ], when: ['More than 50 requests a month.', 'Customers write on WhatsApp and Instagram.', 'Two or more employees work with the same customers.', 'Invoices and debts get out of control.'], whenOther: ['One person, 20–30 customers, rare requests.', 'The process has not settled and changes every week.', 'The budget is zero and will stay that way for now.'], faq: [['Can an Excel base be moved to the CRM?', 'Yes, import via CSV/Excel, fields are mapped, duplicates merged. History comments are migrated as notes.'], ['How long does the move take?', 'For a small team the pilot takes 2–4 weeks: process description, import, channel setup, training.'], ['Do we have to drop Excel entirely?', 'No. CRM reports export to Excel; spreadsheets stay for analysis while customer work happens in the CRM.']], note: NOTE.en },
    },
  },
];

export const comparisonBySlug = (slug: string) => COMPARISONS.find((c) => c.slug === slug);
