import type { Lang } from './product-map';
import { COMPANY } from './company';

export type LegalSection = { h: string; p?: string[]; list?: string[] };
export type LegalCopy = { title: string; description: string; label: string; h1: string; intro: string; sections: LegalSection[] };
export type LegalKey = 'privacy' | 'terms-of-use' | 'cookies' | 'refund';

export const LEGAL_LABELS: Record<Lang, { legal: string; updated: string; home: string; contact: string; operator: string; contactLine: string }> = {
  az: { legal: 'Hüquqi məlumat', updated: 'Son yenilənmə', home: 'Ana səhifə', contact: 'Sual üçün əlaqə', operator: 'Operator', contactLine: 'Sual və müraciətlər üçün:' },
  ru: { legal: 'Правовая информация', updated: 'Последнее обновление', home: 'Главная', contact: 'Контакт по вопросам', operator: 'Оператор', contactLine: 'По вопросам обращайтесь:' },
  en: { legal: 'Legal', updated: 'Last updated', home: 'Home', contact: 'Contact', operator: 'Operator', contactLine: 'Questions and requests:' },
};

const E = COMPANY.email; const P = COMPANY.phone;

export const LEGAL: Record<LegalKey, Record<Lang, LegalCopy>> = {
  privacy: {
    az: { title: 'Məxfilik siyasəti — LeadDrive CRM', description: 'leaddrivecrm.org saytında hansı fərdi məlumatların toplandığı, nə məqsədlə emal edildiyi, kimə ötürüldüyü və istifadəçinin hüquqları.', label: 'Məxfilik siyasəti', h1: 'Məxfilik siyasəti', intro: 'Bu siyasət leaddrivecrm.org saytına (bundan sonra «Sayt») aiddir və Azərbaycan Respublikasının «Fərdi məlumatlar haqqında» Qanununa (11 may 2010-cu il, № 998-IIIQ) uyğun tərtib edilib. Sayt LeadDrive CRM məhsulunun marketinq saytıdır; CRM-in özündə (app.leaddrivecrm.org) məlumatların emalı müştəri ilə bağlanan müqavilə ilə tənzimlənir.', sections: [
      { h: '1. Hansı məlumatları toplayırıq', p: ['Yalnız sizin özünüzün demo sorğusu formu vasitəsilə göndərdiyiniz məlumatları: ad və soyad, iş e-poçtu, telefon və ya WhatsApp nömrəsi; istəyə görə şirkət adı və mesaj. Formu göndərərkən sorğunun göndərildiyi səhifənin ünvanı və seçdiyiniz sayt dili də əlavə olunur.', 'Sayt hesab yaratmır, ödəniş qəbul etmir və izləmə analitikası istifadə etmir.'] },
      { h: '2. Texniki məlumatlar', p: ['Sayt Cloudflare şəbəkəsində yerləşir. Cloudflare təhlükəsizlik və işləkliyi təmin etmək üçün sorğunun IP ünvanını və texniki başlıqlarını (brauzer, vaxt) məhdud müddətə jurnal formasında saxlaya bilər. Sayt özü bu məlumatlardan profil yaratmaq üçün istifadə etmir.'] },
      { h: '3. Emalın məqsədi və əsası', list: ['Demo sorğusuna cavab vermək və LeadDrive CRM-in təqdimatını razılaşdırmaq — sizin razılığınız (formadakı işarə) və müqaviləöncəsi tədbirlər əsasında.', 'Saytın təhlükəsizliyi və işləkliyi — operatorun qanuni maraqları əsasında.', 'Marketinq göndərişləri yalnız ayrıca razılıqla aparılır; demo sorğusu belə razılıq sayılmır.'] },
      { h: '4. Məlumatlar hara ötürülür', list: ['LeadDrive CRM (app.leaddrivecrm.org) — sorğu orada lid kimi qeydə alınır və operatorun əməkdaşları tərəfindən emal olunur.', 'Cloudflare, Inc. — saytın hostinqi və qorunması (texniki jurnal).', 'WhatsApp (Meta Platforms) — yalnız siz özünüz «WhatsApp-da yazın» düyməsini seçdikdə; bu halda Meta-nın öz məxfilik şərtləri tətbiq olunur.', 'Məlumatlar üçüncü şəxslərə satılmır və reklam məqsədilə ötürülmür.'] },
      { h: '5. Saxlama müddəti', p: ['Sorğu məlumatları emalın məqsədinə çatana qədər, lakin sorğudan sonra ən çox 24 ay saxlanılır; müqavilə bağlandıqda — müqavilənin şərtlərinə uyğun. Silinmə tələbi ilə müraciət etdikdə məlumatlar 30 gün ərzində silinir, qanunla saxlanması tələb olunan hallar istisna olmaqla.'] },
      { h: '6. Hüquqlarınız', list: ['Sizin haqqınızda hansı məlumatların emal olunduğunu öyrənmək.', 'Məlumatların düzəldilməsini, bloklanmasını və ya silinməsini tələb etmək.', 'Razılığı istənilən vaxt geri götürmək.', `Müraciət ünvanı: ${E}, ${P}. Cavab 10 iş günü ərzində verilir.`] },
      { h: '7. Uşaqların məlumatları', p: ['Sayt 18 yaşına çatmamış şəxslərə yönəlməyib və onların məlumatlarını bilərəkdən toplamır.'] },
      { h: '8. Təhlükəsizlik', p: ['Sayt yalnız HTTPS üzərində işləyir. Sorğular CRM-ə şifrələnmiş kanalla ötürülür; CRM-də rollar, sahə səviyyəsində hüquqlar, ikifaktorlu giriş və audit jurnalı tətbiq olunur.'] },
      { h: '9. Dəyişikliklər', p: ['Siyasət yeniləndikdə bu səhifədə yeni tarix göstərilir. Əhəmiyyətli dəyişikliklər barədə sorğu göndərmiş şəxslərə e-poçtla məlumat verilir.'] },
    ] },
    ru: { title: 'Политика конфиденциальности — LeadDrive CRM', description: 'Какие персональные данные собирает сайт leaddrivecrm.org, для чего они обрабатываются, кому передаются и какие права есть у пользователя.', label: 'Политика конфиденциальности', h1: 'Политика конфиденциальности', intro: 'Политика относится к сайту leaddrivecrm.org (далее «Сайт») и составлена в соответствии с Законом Азербайджанской Республики «О персональных данных» (от 11 мая 2010 г., № 998-IIIQ). Сайт является маркетинговым сайтом продукта LeadDrive CRM; обработка данных внутри самой CRM (app.leaddrivecrm.org) регулируется договором с клиентом.', sections: [
      { h: '1. Какие данные мы собираем', p: ['Только те, что вы сами отправляете через форму запроса демо: имя и фамилию, рабочую почту, телефон или номер WhatsApp; по желанию название компании и сообщение. К запросу добавляются адрес страницы, с которой он отправлен, и выбранный язык сайта.', 'Сайт не создаёт аккаунтов, не принимает платежи и не использует аналитику для отслеживания.'] },
      { h: '2. Технические данные', p: ['Сайт размещён в сети Cloudflare. Для безопасности и работоспособности Cloudflare может ограниченное время хранить в журналах IP-адрес запроса и технические заголовки (браузер, время). Сайт не использует эти данные для построения профилей.'] },
      { h: '3. Цели и основания обработки', list: ['Ответ на запрос демо и согласование показа LeadDrive CRM — на основании вашего согласия (отметка в форме) и преддоговорных мер.', 'Безопасность и работоспособность сайта — на основании законного интереса оператора.', 'Маркетинговые рассылки ведутся только по отдельному согласию; запрос демо таким согласием не является.'] },
      { h: '4. Кому передаются данные', list: ['LeadDrive CRM (app.leaddrivecrm.org) — запрос сохраняется там как лид и обрабатывается сотрудниками оператора.', 'Cloudflare, Inc. — хостинг и защита сайта (технические журналы).', 'WhatsApp (Meta Platforms) — только если вы сами выбираете кнопку «Написать в WhatsApp»; тогда действуют условия конфиденциальности Meta.', 'Данные не продаются третьим лицам и не передаются для рекламы.'] },
      { h: '5. Срок хранения', p: ['Данные запроса хранятся до достижения цели обработки, но не дольше 24 месяцев после запроса; при заключении договора — по его условиям. По требованию об удалении данные удаляются в течение 30 дней, кроме случаев, когда закон обязывает их хранить.'] },
      { h: '6. Ваши права', list: ['Узнать, какие данные о вас обрабатываются.', 'Требовать исправления, блокировки или удаления данных.', 'Отозвать согласие в любой момент.', `Адрес для обращений: ${E}, ${P}. Ответ даётся в течение 10 рабочих дней.`] },
      { h: '7. Данные детей', p: ['Сайт не предназначен для лиц младше 18 лет и сознательно не собирает их данные.'] },
      { h: '8. Безопасность', p: ['Сайт работает только по HTTPS. Запросы передаются в CRM по шифрованному каналу; в CRM действуют роли, права на уровне полей, двухфакторный вход и журнал аудита.'] },
      { h: '9. Изменения', p: ['При обновлении политики на этой странице указывается новая дата. О существенных изменениях лица, отправлявшие запросы, уведомляются по почте.'] },
    ] },
    en: { title: 'Privacy Policy — LeadDrive CRM', description: 'What personal data the leaddrivecrm.org website collects, why it is processed, who it is shared with and what rights users have.', label: 'Privacy Policy', h1: 'Privacy Policy', intro: 'This policy applies to the leaddrivecrm.org website (the “Site”) and follows the Law of the Republic of Azerbaijan “On Personal Data” (11 May 2010, No. 998-IIIQ). The Site is the marketing site of the LeadDrive CRM product; processing inside the CRM itself (app.leaddrivecrm.org) is governed by the customer contract.', sections: [
      { h: '1. What we collect', p: ['Only what you submit yourself through the demo request form: name, work email, phone or WhatsApp number; optionally company name and a message. The page you sent the request from and the site language you chose are added to the request.', 'The Site does not create accounts, take payments or use tracking analytics.'] },
      { h: '2. Technical data', p: ['The Site is hosted on the Cloudflare network. For security and reliability, Cloudflare may keep the request IP address and technical headers (browser, time) in logs for a limited period. The Site does not use this data to build profiles.'] },
      { h: '3. Purposes and legal basis', list: ['Answering your demo request and scheduling a LeadDrive CRM presentation — based on your consent (the checkbox in the form) and pre-contractual steps.', 'Site security and reliability — based on the operator’s legitimate interest.', 'Marketing emails are sent only with separate consent; a demo request is not such consent.'] },
      { h: '4. Who receives the data', list: ['LeadDrive CRM (app.leaddrivecrm.org) — the request is stored there as a lead and handled by the operator’s staff.', 'Cloudflare, Inc. — hosting and protection of the Site (technical logs).', 'WhatsApp (Meta Platforms) — only if you choose the “Write on WhatsApp” button yourself; Meta’s own privacy terms then apply.', 'Data is not sold to third parties or shared for advertising.'] },
      { h: '5. Retention', p: ['Request data is kept until the purpose is fulfilled and no longer than 24 months after the request; if a contract is signed, per its terms. On a deletion request the data is erased within 30 days unless the law requires keeping it.'] },
      { h: '6. Your rights', list: ['Learn what data about you is processed.', 'Request correction, blocking or deletion of the data.', 'Withdraw consent at any time.', `Contact: ${E}, ${P}. We answer within 10 business days.`] },
      { h: '7. Children', p: ['The Site is not aimed at persons under 18 and does not knowingly collect their data.'] },
      { h: '8. Security', p: ['The Site runs over HTTPS only. Requests reach the CRM over an encrypted channel; the CRM applies roles, field-level rights, two-factor login and an audit log.'] },
      { h: '9. Changes', p: ['When the policy is updated, a new date appears on this page. People who submitted requests are notified by email about material changes.'] },
    ] },
  },
  'terms-of-use': {
    az: { title: 'Saytdan istifadə şərtləri — LeadDrive CRM', description: 'leaddrivecrm.org saytından istifadə qaydaları: məzmun, əqli mülkiyyət, məsuliyyətin məhdudlaşdırılması, tətbiq olunan hüquq.', label: 'İstifadə şərtləri', h1: 'Saytdan istifadə şərtləri', intro: 'Sayta daxil olmaqla siz bu şərtlərlə razılaşırsınız. Şərtlər yalnız marketinq saytına aiddir; LeadDrive CRM məhsulundan istifadə ayrıca müqavilə ilə tənzimlənir.', sections: [
      { h: '1. Saytın məqsədi', p: ['Sayt LeadDrive CRM məhsulu haqqında məlumat verir və demo sorğusu qəbul edir. Saytdakı təsvirlər, ekran görüntüləri və rəqəmlər məhsulun 2026-cı ilin sentyabr ayındakı vəziyyətini əks etdirir və ictimai təklif (oferta) deyil.'] },
      { h: '2. Əqli mülkiyyət', p: ['Saytın mətnləri, dizaynı, LeadDrive adı və loqotipi, CRM-in ekran görüntüləri operatora məxsusdur. Başqa şirkətlərin adları və nişanları (WhatsApp, Instagram, TikTok, Facebook, Telegram, Bitrix24, amoCRM və s.) yalnız müvafiq xidmətləri göstərmək üçün istifadə olunur və öz sahiblərinə məxsusdur.', 'Saytın məzmununu şəxsi tanışlıq üçün istifadə etmək olar; ticari məqsədlə surətini çıxarmaq və yaymaq yazılı icazə tələb edir.'] },
      { h: '3. Müqayisə səhifələri', p: ['Digər sistemlər haqqında məlumatlar dərc tarixinə onların açıq sənədlərindən götürülüb və dəyişə bilər. Qeyri-dəqiqlik aşkar etsəniz, bizə yazın, düzəldərik.'] },
      { h: '4. Məsuliyyətin məhdudlaşdırılması', p: ['Sayt «olduğu kimi» təqdim olunur. Operator saytın fasiləsiz işləməsinə və məlumatların hər an tam olmasına zəmanət vermir və saytdan istifadə nəticəsində yaranan dolayı zərərə görə məsuliyyət daşımır, qanunla nəzərdə tutulan hallar istisna olmaqla.'] },
      { h: '5. Kənar keçidlər', p: ['Saytda WhatsApp və digər xarici xidmətlərə keçidlər var. Onların məzmununa və məxfilik şərtlərinə operator cavabdeh deyil.'] },
      { h: '6. Tətbiq olunan hüquq', p: ['Şərtlərə Azərbaycan Respublikasının qanunvericiliyi tətbiq olunur. Mübahisələr danışıqlar yolu ilə, razılıq əldə olunmadıqda Azərbaycan Respublikasının məhkəmələrində həll edilir.'] },
      { h: '7. Əlaqə', p: [`${E}, ${P}.`] },
    ] },
    ru: { title: 'Условия использования сайта — LeadDrive CRM', description: 'Правила использования сайта leaddrivecrm.org: контент, интеллектуальная собственность, ограничение ответственности, применимое право.', label: 'Условия использования', h1: 'Условия использования сайта', intro: 'Заходя на сайт, вы соглашаетесь с этими условиями. Они относятся только к маркетинговому сайту; использование продукта LeadDrive CRM регулируется отдельным договором.', sections: [
      { h: '1. Назначение сайта', p: ['Сайт информирует о продукте LeadDrive CRM и принимает запросы на демо. Описания, скриншоты и цифры отражают состояние продукта на сентябрь 2026 года и не являются публичной офертой.'] },
      { h: '2. Интеллектуальная собственность', p: ['Тексты, дизайн, название и логотип LeadDrive, скриншоты CRM принадлежат оператору. Названия и знаки других компаний (WhatsApp, Instagram, TikTok, Facebook, Telegram, Bitrix24, amoCRM и др.) используются только для обозначения соответствующих сервисов и принадлежат их владельцам.', 'Содержимое сайта можно использовать для личного ознакомления; копирование и распространение в коммерческих целях требует письменного разрешения.'] },
      { h: '3. Страницы сравнений', p: ['Сведения о других системах взяты из их публичной документации на дату публикации и могут меняться. Заметили неточность — напишите нам, исправим.'] },
      { h: '4. Ограничение ответственности', p: ['Сайт предоставляется «как есть». Оператор не гарантирует бесперебойную работу сайта и полноту сведений в каждый момент и не отвечает за косвенные убытки от использования сайта, кроме случаев, предусмотренных законом.'] },
      { h: '5. Внешние ссылки', p: ['На сайте есть ссылки на WhatsApp и другие внешние сервисы. За их содержание и условия конфиденциальности оператор не отвечает.'] },
      { h: '6. Применимое право', p: ['К условиям применяется законодательство Азербайджанской Республики. Споры решаются переговорами, а при недостижении согласия — в судах Азербайджанской Республики.'] },
      { h: '7. Контакты', p: [`${E}, ${P}.`] },
    ] },
    en: { title: 'Website Terms of Use — LeadDrive CRM', description: 'Rules for using leaddrivecrm.org: content, intellectual property, limitation of liability, governing law.', label: 'Terms of Use', h1: 'Website Terms of Use', intro: 'By using the Site you agree to these terms. They apply to the marketing site only; use of the LeadDrive CRM product is governed by a separate contract.', sections: [
      { h: '1. Purpose of the Site', p: ['The Site informs about the LeadDrive CRM product and accepts demo requests. Descriptions, screenshots and figures reflect the product as of September 2026 and are not a public offer.'] },
      { h: '2. Intellectual property', p: ['Texts, design, the LeadDrive name and logo and CRM screenshots belong to the operator. Names and marks of other companies (WhatsApp, Instagram, TikTok, Facebook, Telegram, Bitrix24, amoCRM and others) are used only to identify those services and belong to their owners.', 'Site content may be used for personal reference; copying and distribution for commercial purposes requires written permission.'] },
      { h: '3. Comparison pages', p: ['Information about other systems is taken from their public documentation as of the publication date and may change. If you spot an inaccuracy, write to us and we will fix it.'] },
      { h: '4. Limitation of liability', p: ['The Site is provided “as is”. The operator does not guarantee uninterrupted operation or completeness of information at every moment and is not liable for indirect losses from using the Site, except where the law provides otherwise.'] },
      { h: '5. External links', p: ['The Site links to WhatsApp and other external services. The operator is not responsible for their content or privacy terms.'] },
      { h: '6. Governing law', p: ['These terms are governed by the laws of the Republic of Azerbaijan. Disputes are resolved by negotiation and, failing that, in the courts of the Republic of Azerbaijan.'] },
      { h: '7. Contact', p: [`${E}, ${P}.`] },
    ] },
  },
  cookies: {
    az: { title: 'Kuki siyasəti — LeadDrive CRM', description: 'leaddrivecrm.org saytı hansı kukilərdən istifadə edir: yalnız texniki zəruri, izləmə analitikası yoxdur.', label: 'Kuki siyasəti', h1: 'Kuki siyasəti', intro: 'Sayt sizi izləmək və ya reklam göstərmək üçün kukilərdən istifadə etmir. Buna görə də razılıq banneri göstərilmir: qanunvericilik yalnız texniki zəruri olmayan kukilər üçün razılıq tələb edir.', sections: [
      { h: '1. Sayt özü', p: ['leaddrivecrm.org saytı öz kukilərini yaratmır. Seçdiyiniz dil ünvanla müəyyən olunur (/ru, /en), brauzerdə saxlanılmır. Analitika, reklam pikselləri və sosial şəbəkə vidjetləri quraşdırılmayıb.'] },
      { h: '2. Hostinq (Cloudflare)', p: ['Cloudflare şübhəli trafikdən qorunmaq üçün ayrı-ayrı hallarda texniki zəruri kuki (məsələn, __cf_bm) qoya bilər. Bu kuki sizi eyniləşdirmir, 30 dəqiqədən sonra silinir və razılıq tələb etmir.'] },
      { h: '3. Xarici xidmətlər', p: ['Demo sorğusu formu CRM-ə (app.leaddrivecrm.org) məlumat göndərir, lakin saytda kuki qoymur. «WhatsApp-da yazın» düyməsi sizi Meta-nın xidmətinə aparır; orada onların kuki siyasəti tətbiq olunur.'] },
      { h: '4. Gələcəkdə', p: ['Sayta analitika (məsələn, Google Analytics) əlavə edilərsə, bu səhifə yenilənəcək və izləmə kukiləri yalnız sizin razılığınızdan sonra işə düşəcək.'] },
      { h: '5. Kukiləri necə idarə etmək', p: ['Brauzer parametrlərində kukiləri silmək və bloklamaq olar. Sayt onlarsız da tam işləyir.'] },
    ] },
    ru: { title: 'Политика cookie — LeadDrive CRM', description: 'Какие cookie использует сайт leaddrivecrm.org: только технически необходимые, без аналитики отслеживания.', label: 'Политика cookie', h1: 'Политика cookie', intro: 'Сайт не использует cookie для отслеживания или показа рекламы. Поэтому баннер согласия не показывается: законодательство требует согласия только для cookie, которые не являются технически необходимыми.', sections: [
      { h: '1. Сам сайт', p: ['Сайт leaddrivecrm.org не создаёт собственных cookie. Выбранный язык определяется адресом (/ru, /en) и не хранится в браузере. Аналитика, рекламные пиксели и виджеты соцсетей не установлены.'] },
      { h: '2. Хостинг (Cloudflare)', p: ['Для защиты от подозрительного трафика Cloudflare в отдельных случаях может установить технически необходимый cookie (например, __cf_bm). Он не идентифицирует вас, удаляется через 30 минут и не требует согласия.'] },
      { h: '3. Внешние сервисы', p: ['Форма запроса демо отправляет данные в CRM (app.leaddrivecrm.org), но не ставит cookie на сайте. Кнопка «Написать в WhatsApp» ведёт в сервис Meta, где действует их политика cookie.'] },
      { h: '4. На будущее', p: ['Если на сайт будет добавлена аналитика (например, Google Analytics), эта страница будет обновлена, а cookie отслеживания будут включаться только после вашего согласия.'] },
      { h: '5. Как управлять cookie', p: ['Cookie можно удалять и блокировать в настройках браузера. Сайт полностью работает и без них.'] },
    ] },
    en: { title: 'Cookie Policy — LeadDrive CRM', description: 'Which cookies leaddrivecrm.org uses: strictly necessary only, no tracking analytics.', label: 'Cookie Policy', h1: 'Cookie Policy', intro: 'The Site does not use cookies for tracking or advertising. That is why no consent banner is shown: the law requires consent only for cookies that are not strictly necessary.', sections: [
      { h: '1. The Site itself', p: ['leaddrivecrm.org sets no cookies of its own. Your language is determined by the URL (/ru, /en) and is not stored in the browser. No analytics, advertising pixels or social widgets are installed.'] },
      { h: '2. Hosting (Cloudflare)', p: ['To protect against suspicious traffic, Cloudflare may in some cases set a strictly necessary cookie (for example, __cf_bm). It does not identify you, expires after 30 minutes and needs no consent.'] },
      { h: '3. External services', p: ['The demo request form sends data to the CRM (app.leaddrivecrm.org) but sets no cookie on the Site. The “Write on WhatsApp” button takes you to Meta’s service, where their cookie policy applies.'] },
      { h: '4. In the future', p: ['If analytics (for example, Google Analytics) is added to the Site, this page will be updated and tracking cookies will be enabled only after your consent.'] },
      { h: '5. Managing cookies', p: ['You can delete and block cookies in your browser settings. The Site works fully without them.'] },
    ] },
  },
  refund: {
    az: { title: 'Ödənişin geri qaytarılması siyasəti — LeadDrive CRM', description: 'LeadDrive CRM üçün ödənişlərin geri qaytarılması qaydası: sınaq dövrü, istifadə olunmamış abunə dövrü, tətbiq işləri.', label: 'Geri qaytarma siyasəti', h1: 'Ödənişin geri qaytarılması siyasəti', intro: 'Sayt ödəniş qəbul etmir. LeadDrive CRM-ə abunəlik və tətbiq xidmətləri müştəri ilə bağlanan müqavilə və hesab-faktura əsasında ödənilir. Aşağıdakı qaydalar müqavilədə başqa şərt nəzərdə tutulmadıqda tətbiq olunur.', sections: [
      { h: '1. Sınaq dövrü', p: ['Tətbiqdən əvvəl pilot şöbə üçün sınaq dövrü razılaşdırılır. Sınaq dövründə abunə haqqı tutulmur.'] },
      { h: '2. Abunəlik', p: ['Abunə haqqı ödənilmiş dövrün əvvəlində tutulur. Müştəri ödənişdən sonra 14 təqvim günü ərzində yazılı şəkildə imtina edərsə, istifadə olunmamış tam aylar üçün ödəniş 10 iş günü ərzində ödənişin edildiyi üsulla geri qaytarılır. Başlanmış ay geri qaytarılmır.'] },
      { h: '3. Tətbiq və fərdi işlər', p: ['Prosesin təsviri, məlumatların köçürülməsi, kanalların qoşulması, təlim və fərdi tənzimləmələr görülmüş iş həcminə görə ödənilir və artıq görülmüş hissəsi geri qaytarılmır.'] },
      { h: '4. Üçüncü tərəf xərcləri', p: ['Kanal provayderlərinin (WhatsApp Business API, SMS, telefoniya) və AI modellərinin tarifləri üçüncü tərəfə ödənilir və geri qaytarılmır.'] },
      { h: '5. Xidmətin göstərilməməsi', p: ['Operatorun təqsiri üzündən xidmət müqavilədə nəzərdə tutulan müddətdən artıq əlçatmaz olarsa, müştəri həmin dövr üçün mütənasib geri qaytarma və ya abunənin uzadılmasını tələb edə bilər.'] },
      { h: '6. Müraciət qaydası', p: [`Geri qaytarma tələbi ${E} ünvanına müqavilə və ya faktura nömrəsi göstərilməklə göndərilir. Cavab 5 iş günü ərzində verilir.`] },
    ] },
    ru: { title: 'Политика возврата средств — LeadDrive CRM', description: 'Порядок возврата платежей за LeadDrive CRM: пробный период, неиспользованный период подписки, работы по внедрению.', label: 'Политика возврата', h1: 'Политика возврата средств', intro: 'Сайт не принимает платежи. Подписка на LeadDrive CRM и услуги внедрения оплачиваются по договору с клиентом и счёту. Правила ниже применяются, если договор не предусматривает иного.', sections: [
      { h: '1. Пробный период', p: ['Перед внедрением согласуется пробный период для пилотного отдела. В пробный период абонентская плата не взимается.'] },
      { h: '2. Подписка', p: ['Абонентская плата списывается в начале оплаченного периода. Если клиент письменно отказывается в течение 14 календарных дней после оплаты, плата за неиспользованные полные месяцы возвращается тем же способом в течение 10 рабочих дней. Начатый месяц не возвращается.'] },
      { h: '3. Внедрение и индивидуальные работы', p: ['Описание процесса, перенос данных, подключение каналов, обучение и индивидуальные настройки оплачиваются по фактически выполненному объёму, и уже выполненная часть возврату не подлежит.'] },
      { h: '4. Расходы третьих сторон', p: ['Тарифы провайдеров каналов (WhatsApp Business API, SMS, телефония) и AI-моделей уплачиваются третьим сторонам и не возвращаются.'] },
      { h: '5. Недоступность сервиса', p: ['Если по вине оператора сервис недоступен дольше срока, предусмотренного договором, клиент вправе требовать пропорциональный возврат за этот период или продление подписки.'] },
      { h: '6. Как обратиться', p: [`Запрос на возврат направляется на ${E} с указанием номера договора или счёта. Ответ даётся в течение 5 рабочих дней.`] },
    ] },
    en: { title: 'Refund Policy — LeadDrive CRM', description: 'How refunds work for LeadDrive CRM: trial period, unused subscription period, implementation work.', label: 'Refund Policy', h1: 'Refund Policy', intro: 'The Site takes no payments. LeadDrive CRM subscriptions and implementation services are paid under a customer contract and invoice. The rules below apply unless the contract says otherwise.', sections: [
      { h: '1. Trial period', p: ['A trial period for a pilot department is agreed before implementation. No subscription fee is charged during the trial.'] },
      { h: '2. Subscription', p: ['The subscription fee is charged at the start of the paid period. If the customer cancels in writing within 14 calendar days after payment, the fee for unused full months is refunded by the same method within 10 business days. A started month is not refunded.'] },
      { h: '3. Implementation and custom work', p: ['Process description, data migration, channel setup, training and custom configuration are billed by the work actually done, and the completed part is non-refundable.'] },
      { h: '4. Third-party costs', p: ['Fees of channel providers (WhatsApp Business API, SMS, telephony) and AI models are paid to third parties and are not refundable.'] },
      { h: '5. Service unavailability', p: ['If the service is unavailable through the operator’s fault for longer than the contract allows, the customer may request a proportional refund for that period or an extension of the subscription.'] },
      { h: '6. How to request', p: [`Send refund requests to ${E} with the contract or invoice number. We reply within 5 business days.`] },
    ] },
  },
};

export const LEGAL_PATH: Record<LegalKey, string> = { privacy: '/privacy', 'terms-of-use': '/terms-of-use', cookies: '/cookies', refund: '/refund' };
export const LEGAL_KEYS: LegalKey[] = ['privacy', 'terms-of-use', 'cookies', 'refund'];
