// Product map data. Only modules confirmed by the visual audit of app.leaddrivecrm.org
// are marked `confirmed` + `public`; everything else stays out of the rendered page.
// Audit registry: realtime-voice-chat/outputs/leaddrive-product-audit/section-register.json

export type Lang = 'ru' | 'az' | 'en';
export const LANGS: Lang[] = ['az', 'ru', 'en'];
export type Localized = Record<Lang, string>;
export type ModuleStatus = 'confirmed' | 'unverified';
export type ModuleVisibility = 'public' | 'hidden';
export type IconKey = 'briefcase' | 'users' | 'target' | 'file' | 'gift' | 'message' | 'chart' | 'layers' | 'sparkles' | 'kanban' | 'package' | 'bell' | 'funnel' | 'calendar' | 'radio' | 'timer' | 'zap' | 'quote' | 'route' | 'shield' | 'settings' | 'plug' | 'lock' | 'workflow' | 'heart' | 'umbrella' | 'landmark' | 'newspaper';

/** Industry sections seen in the CRM (M14–M18). Rendered as scenarios, not as packaged vertical products. */
export type IndustryScenario = {
  id: string;
  order: number;
  status: ModuleStatus;
  icon: IconKey;
  title: Localized;
  summary: Localized;
  sections: Localized[];
  auditRefs: string[];
};

export type ProductDomain = {
  id: string;
  order: number;
  icon: IconKey;
  title: Localized;
  summary: Localized;
};

export type ProductModule = {
  id: string;
  domainId: string;
  order: number;
  status: ModuleStatus;
  visibility: ModuleVisibility;
  icon: IconKey;
  title: Localized;
  description: Localized;
  capabilities: Localized[];
  /** Audit rows that back this entry. Internal only, never rendered. */
  auditRefs: string[];
};

import { EXTRA } from './i18n-extra';
/** RU/AZ inline; EN comes from the dictionary keyed by the Russian text (fallback: Russian). */
const l = (ru: string, az: string): Localized => ({ ru, az, en: EXTRA[ru]?.[1] ?? ru });

export const DOMAINS: ProductDomain[] = [
  { id: 'core', order: 1, icon: 'layers', title: l('Основа CRM', 'CRM əsası'), summary: l('Компании, люди, задачи и проекты в одном рабочем контуре. То, к чему подключаются остальные модули.', 'Şirkətlər, insanlar, tapşırıqlar və layihələr bir iş konturunda. Qalan modullar buna qoşulur.') },
  { id: 'sales', order: 2, icon: 'briefcase', title: l('Продажи', 'Satış'), summary: l('От лида до сделки: воронки, предложения, прогноз и распределение работы между менеджерами.', 'Liddən sövdələşməyə: satış boru xətləri, təkliflər, proqnoz və işin menecerlər arasında bölünməsi.') },
  { id: 'omni', order: 3, icon: 'message', title: l('Коммуникации', 'Ünsiyyət'), summary: l('Общий Inbox для мессенджеров, звонков, SMS и почты. Правила ответов, рабочие часы и аналитика входящих.', 'Messencerlər, zənglər, SMS və e-poçt üçün ümumi Inbox. Cavab qaydaları, iş saatları və daxil olanların analitikası.') },
  { id: 'support', order: 4, icon: 'shield', title: l('Поддержка', 'Dəstək'), summary: l('Тикеты с SLA, жалобы, база знаний, маршрутизация по навыкам, макросы и клиентский портал.', 'SLA ilə tiketlər, şikayətlər, bilik bazası, bacarıq üzrə yönləndirmə, makrolar və müştəri portalı.') },
  { id: 'marketing', order: 5, icon: 'target', title: l('Маркетинг', 'Marketinq'), summary: l('Сегменты, кампании, цепочки касаний, мероприятия и обратная связь от клиентов.', 'Seqmentlər, kampaniyalar, əlaqə ssenariləri, tədbirlər və müştərilərdən rəy.') },
  { id: 'contracts', order: 6, icon: 'file', title: l('Договоры', 'Müqavilələr'), summary: l('Реестр договоров, шаблоны и пункты, запросы, согласование и контроль исполнения.', 'Müqavilə reyestri, şablonlar və bəndlər, sorğular, təsdiq və icraya nəzarət.') },
  { id: 'finance', order: 9, icon: 'chart', title: l('Финансы', 'Maliyyə'), summary: l('Счета с оплатами и напоминаниями, повторяющиеся счета, подписки, модель рентабельности и ценообразование услуг.', 'Ödənişlər və xatırlatmalarla hesab-fakturalar, təkrarlanan fakturalar, abunəliklər, gəlirlilik modeli və xidmət qiymətləndirməsi.') },
  { id: 'analytics', order: 10, icon: 'chart', title: l('Аналитика и Da Vinci', 'Analitika və Da Vinci'), summary: l('Сводные отчёты, конструктор отчётов, KPI Arena и центр управления AI-агентами.', 'İcmal hesabatlar, hesabat qurucusu, KPI Arena və AI agentlərinin idarəetmə mərkəzi.') },
  { id: 'field', order: 11, icon: 'route', title: l('Маршруты и поле', 'Marşrut və sahə'), summary: l('Полевые команды: маршруты, визиты с GPS, точки и контакты, задачи, фотоотчёты, предупреждения и аналитика исполнения.', 'Sahə komandaları: marşrutlar, GPS ilə vizitlər, nöqtələr və kontaktlar, tapşırıqlar, fotohesabatlar, xəbərdarlıqlar və icra analitikası.') },
  { id: 'social', order: 8, icon: 'radio', title: l('Социальный мониторинг', 'Sosial monitorinq'), summary: l('Упоминания бренда в соцсетях и новостях: источники, сценарии поиска, AI-черновики ответов и отчёты для клиентов.', 'Sosial şəbəkələrdə və xəbərlərdə brend qeydləri: mənbələr, axtarış ssenariləri, AI cavab qaralamaları və müştərilər üçün hesabatlar.') },
  { id: 'loyalty', order: 7, icon: 'gift', title: l('Лояльность', 'Loyallıq'), summary: l('Программа с уровнями, правилами начисления, наградами и промокодами.', 'Səviyyələr, xal qazanma qaydaları, mükafatlar və promo-kodlarla loyallıq proqramı.') },
  { id: 'platform', order: 12, icon: 'settings', title: l('Платформа и настройки', 'Platforma və parametrlər'), summary: l('Роли и права до уровня поля, безопасность и журнал аудита, свои поля, автоматизации, интеграции и AI-делегирование.', 'Sahə səviyyəsinə qədər rollar və icazələr, təhlükəsizlik və audit jurnalı, öz sahələr, avtomatlaşdırmalar, inteqrasiyalar və AI-yə həvalə.') },
];

export const MODULES: ProductModule[] = [
  // ——— Core (M01) ———
  { id: 'companies-contacts', domainId: 'core', order: 1, status: 'confirmed', visibility: 'public', icon: 'users', title: l('Компании и контакты', 'Şirkətlər və kontaktlar'), description: l('Единая карточка клиента: контакты, сделки, договоры, обращения и общая хронология.', 'Vahid müştəri kartı: kontaktlar, sövdələşmələr, müqavilələr, müraciətlər və ümumi xronologiya.'), capabilities: [l('Хронология продаж и поддержки', 'Satış və dəstək xronologiyası'), l('Активности и коммуникации', 'Fəaliyyətlər və ünsiyyət'), l('Сегментная аналитика контактов', 'Kontaktların seqment analitikası')], auditRefs: ['M01-S03', 'M01-S04'] },
  { id: 'tasks-projects', domainId: 'core', order: 2, status: 'confirmed', visibility: 'public', icon: 'kanban', title: l('Задачи, доски и проекты', 'Tapşırıqlar, lövhələr və layihələr'), description: l('Рабочие доски задач связаны с лидами и проектами. Проект показывает план, финансы и связанные CRM-задачи.', 'İş lövhələri lidlər və layihələrlə əlaqəlidir. Layihədə plan, maliyyə və bağlı CRM tapşırıqları görünür.'), capabilities: [l('Доска и список задач', 'Lövhə və tapşırıq siyahısı'), l('Отчёты по производительности', 'Məhsuldarlıq hesabatları'), l('Шаблоны задач', 'Tapşırıq şablonları')], auditRefs: ['M01-S05', 'M01-S10', 'M01-S11'] },
  { id: 'products', domainId: 'core', order: 3, status: 'confirmed', visibility: 'public', icon: 'package', title: l('Каталог продуктов', 'Məhsul kataloqu'), description: l('Продукты и услуги с ценами и характеристиками. Позиции каталога подставляются в коммерческие предложения.', 'Qiymət və xüsusiyyətləri olan məhsul və xidmətlər. Kataloq mövqeləri kommersiya təkliflərinə əlavə olunur.'), capabilities: [l('Цены и характеристики', 'Qiymətlər və xüsusiyyətlər'), l('Подстановка в предложения', 'Təkliflərə əlavə')], auditRefs: ['M01-S06', 'X01'] },
  { id: 'customer-insights', domainId: 'core', order: 4, status: 'confirmed', visibility: 'public', icon: 'chart', title: l('Клиентская аналитика', 'Müştəri analitikası'), description: l('Профили клиентов по ценности, риску оттока и активности. Очередь дублей показывает совпадения и объясняет их.', 'Dəyər, itirmə riski və aktivliyə görə müştəri profilləri. Dublikat növbəsi uyğunluqları göstərir və izah edir.'), capabilities: [l('LTV, отток, активность', 'LTV, itirmə riski, aktivlik'), l('Очередь объединения профилей', 'Profil birləşdirmə növbəsi')], auditRefs: ['M01-S08', 'M01-S09'] },
  { id: 'dashboard', domainId: 'core', order: 5, status: 'confirmed', visibility: 'public', icon: 'bell', title: l('Панель и уведомления', 'Panel və bildirişlər'), description: l('Сводный экран продаж, кампаний и операционных рисков. Центр уведомлений о событиях CRM.', 'Satış, kampaniya və əməliyyat risklərinin icmal ekranı. CRM hadisələri üzrə bildiriş mərkəzi.'), capabilities: [l('Сводка по продажам и кампаниям', 'Satış və kampaniya icmalı'), l('Уведомления о событиях', 'Hadisə bildirişləri')], auditRefs: ['M01-S01', 'M01-S07'] },
  { id: 'davinci-advisor', domainId: 'core', order: 6, status: 'confirmed', visibility: 'public', icon: 'sparkles', title: l('Da Vinci: советник', 'Da Vinci: məsləhətçi'), description: l('Сигналы по клиентам и сделкам с объяснением и предлагаемым действием. Подтверждение остаётся за сотрудником.', 'Müştərilər və sövdələşmələr üzrə izahlı siqnallar və təklif olunan hərəkət. Təsdiq əməkdaşda qalır.'), capabilities: [l('Сигналы и доказательства', 'Siqnallar və əsaslar'), l('Очередь подтверждений', 'Təsdiq növbəsi'), l('След исполнения', 'İcra izi')], auditRefs: ['M01-S02'] },

  // ——— Sales (M02) ———
  { id: 'leads', domainId: 'sales', order: 1, status: 'confirmed', visibility: 'public', icon: 'funnel', title: l('Лиды', 'Lidlər'), description: l('Реестр и карточки лидов, квалификация, активности и аналитика. Очереди звонков для обзвона выбранных лидов.', 'Lid reyestri və kartları, qiymətləndirmə, fəaliyyətlər və analitika. Seçilmiş lidlər üçün zəng növbələri.'), capabilities: [l('Квалификация и статусы', 'Qiymətləndirmə və statuslar'), l('Аналитика лидов', 'Lid analitikası'), l('Очереди звонков', 'Zəng növbələri')], auditRefs: ['M02-S01'] },
  { id: 'deals', domainId: 'sales', order: 2, status: 'confirmed', visibility: 'public', icon: 'briefcase', title: l('Сделки и воронки', 'Sövdələşmələr və boru xətləri'), description: l('Несколько воронок со своими стадиями, вероятностями и правилами перехода. У сделки есть ответственный и следующий шаг.', 'Öz mərhələləri, ehtimalları və keçid qaydaları olan bir neçə boru xətti. Sövdələşmənin məsul şəxsi və növbəti addımı var.'), capabilities: [l('Стадии и вероятности', 'Mərhələlər və ehtimallar'), l('Правила перехода', 'Keçid qaydaları'), l('Аналитика сделок', 'Sövdələşmə analitikası')], auditRefs: ['M02-S02', 'M02-S09'] },
  { id: 'quotes', domainId: 'sales', order: 3, status: 'confirmed', visibility: 'public', icon: 'quote', title: l('Коммерческие предложения', 'Kommersiya təklifləri'), description: l('Реестр предложений, редактор строк, скидки и статусы. Позиции берутся из каталога.', 'Təklif reyestri, sətir redaktoru, endirimlər və statuslar. Mövqelər kataloqdan götürülür.'), capabilities: [l('Строки и скидки', 'Sətirlər və endirimlər'), l('Статусы предложения', 'Təklif statusları')], auditRefs: ['M02-S03'] },
  { id: 'sequences', domainId: 'sales', order: 4, status: 'confirmed', visibility: 'public', icon: 'timer', title: l('Последовательности касаний', 'Əlaqə ardıcıllıqları'), description: l('Сценарии касаний для лидов и контактов с очередью шагов для менеджера.', 'Lidlər və kontaktlar üçün əlaqə ssenariləri, menecer üçün addım növbəsi ilə.'), capabilities: [l('Шаги и условия', 'Addımlar və şərtlər'), l('Очередь менеджера', 'Menecer növbəsi')], auditRefs: ['M02-S04'] },
  { id: 'forecast', domainId: 'sales', order: 5, status: 'confirmed', visibility: 'public', icon: 'chart', title: l('Прогноз продаж', 'Satış proqnozu'), description: l('Прогноз выручки и выполнение квот, снимки прогноза на дату, водопад изменений воронки и скорость сделок по стадиям.', 'Gəlir proqnozu və kvotaların icrası, tarixə görə proqnoz görüntüləri, boru xətti dəyişikliklərinin şəlaləsi və mərhələlər üzrə sövdələşmə sürəti.'), capabilities: [l('Снимки прогноза', 'Proqnoz görüntüləri'), l('Водопад воронки', 'Boru xətti şəlaləsi'), l('Скорость сделок', 'Sövdələşmə sürəti'), l('Плановые суммы по месяцам', 'Aylıq plan məbləğləri')], auditRefs: ['M02-S05', 'M02-S06', 'M02-S07', 'M02-S08', 'M02-S11'] },
  { id: 'sales-settings', domainId: 'sales', order: 6, status: 'confirmed', visibility: 'public', icon: 'route', title: l('Квоты, территории, правила', 'Kvotalar, ərazilər, qaydalar'), description: l('Квартальные квоты менеджеров, территории по географии и отрасли, распределение новых лидов по условиям или очередности.', 'Menecerlərin rüblük kvotaları, coğrafiya və sahə üzrə ərazilər, yeni lidlərin şərtlərə və ya növbəyə görə bölünməsi.'), capabilities: [l('План и факт по квотам', 'Kvota üzrə plan və fakt'), l('Территории и участники', 'Ərazilər və iştirakçılar'), l('Правила распределения лидов', 'Lid bölgüsü qaydaları')], auditRefs: ['M02-S10', 'M02-S12', 'M02-S13'] },
  { id: 'web-to-lead', domainId: 'sales', order: 7, status: 'confirmed', visibility: 'public', icon: 'zap', title: l('Web-to-Lead', 'Web-to-Lead'), description: l('Конструктор встраиваемой формы: заявки с сайта попадают в лиды.', 'Yerləşdirilə bilən forma konstruktoru: saytdan gələn müraciətlər lidlərə düşür.'), capabilities: [l('Код встраивания', 'Yerləşdirmə kodu'), l('Предпросмотр формы', 'Forma önizləməsi')], auditRefs: ['M02-S14'] },

  // ——— Omni-channel (M06) ———
  { id: 'inbox', domainId: 'omni', order: 1, status: 'confirmed', visibility: 'public', icon: 'message', title: l('Общий Inbox', 'Ümumi Inbox'), description: l('Переписки из подключённых каналов в одном месте: очереди, ответственные, связь беседы с лидом или контактом.', 'Qoşulmuş kanallardan yazışmalar bir yerdə: növbələr, məsul şəxslər, söhbətin lid və ya kontaktla əlaqəsi.'), capabilities: [l('Очереди и назначение', 'Növbələr və təyinat'), l('Связь с карточкой CRM', 'CRM kartı ilə əlaqə'), l('Быстрые ответы с переменными', 'Dəyişənli hazır cavablar')], auditRefs: ['M06-S01', 'M06-S02'] },
  { id: 'channels', domainId: 'omni', order: 2, status: 'confirmed', visibility: 'public', icon: 'radio', title: l('Каталог каналов', 'Kanal kataloqu'), description: l('Мессенджеры, звонки, SMS, почта и чат на сайте подключаются по пошаговой инструкции для каждого провайдера.', 'Messencerlər, zənglər, SMS, e-poçt və sayt çatı hər provayder üçün addım-addım təlimatla qoşulur.'), capabilities: [l('WhatsApp Business, Facebook Messenger, Instagram, Telegram, VK, TikTok', 'WhatsApp Business, Facebook Messenger, Instagram, Telegram, VK, TikTok'), l('Звонки: Twilio, 3CX, Asterisk, SIP', 'Zənglər: Twilio, 3CX, Asterisk, SIP'), l('SMS, Google Workspace и SMTP', 'SMS, Google Workspace və SMTP'), l('Чат на сайте', 'Sayt çatı')], auditRefs: ['M06-S07'] },
  { id: 'auto-replies', domainId: 'omni', order: 3, status: 'confirmed', visibility: 'public', icon: 'zap', title: l('Автоответы и сценарии', 'Avtomatik cavablar və ssenarilər'), description: l('Правила автоответов в социальных каналах и конструктор сценариев обработки входящих: маршрутизация, ответ, создание контакта, передача сотруднику.', 'Sosial kanallarda avtomatik cavab qaydaları və daxil olanların emalı üçün ssenari konstruktoru: yönləndirmə, cavab, kontakt yaradılması, əməkdaşa ötürmə.'), capabilities: [l('Правила автоответа', 'Avtomatik cavab qaydaları'), l('Сценарии обработки входящих', 'Daxil olanların emal ssenariləri'), l('Передача разговора команде', 'Söhbətin komandaya ötürülməsi')], auditRefs: ['M06-S04', 'M06-S05'] },
  { id: 'business-hours', domainId: 'omni', order: 4, status: 'confirmed', visibility: 'public', icon: 'timer', title: l('Рабочие часы', 'İş saatları'), description: l('Расписание по каналам и тексты для рабочего и нерабочего времени.', 'Kanallar üzrə cədvəl və iş vaxtı ilə qeyri-iş vaxtı üçün mətnlər.'), capabilities: [l('Недельное расписание', 'Həftəlik cədvəl'), l('Сообщения вне рабочего времени', 'İş vaxtından kənar mesajlar')], auditRefs: ['M06-S06'] },
  { id: 'voip-journal', domainId: 'omni', order: 6, status: 'confirmed', visibility: 'public', icon: 'radio', title: l('VoIP: журнал звонков', 'VoIP: zəng jurnalı'), description: l('История звонков со статусами, длительностью и исходом разговора. Пропущенные входящие собраны отдельно.', 'Status, müddət və nəticə ilə zəng tarixçəsi. Buraxılmış daxil olan zənglər ayrıca toplanır.'), capabilities: [l('Статусы и причины недозвона', 'Statuslar və cavabsız səbəbləri'), l('Исход звонка', 'Zəngin nəticəsi'), l('Пропущенные входящие', 'Buraxılmış daxil olanlar')], auditRefs: ['M06-S08'] },
  { id: 'web-chat', domainId: 'omni', order: 7, status: 'confirmed', visibility: 'public', icon: 'message', title: l('Чат на сайте', 'Sayt çatı'), description: l('Виджет с кодом встраивания, оформлением, предчат-формой и разрешёнными доменами. AI-ответы включаются отдельно.', 'Yerləşdirmə kodu, görünüş, ön-çat forması və icazəli domenləri olan vidcet. AI cavabları ayrıca qoşulur.'), capabilities: [l('Код встраивания и внешний вид', 'Yerləşdirmə kodu və görünüş'), l('Предчат-форма и контакт CRM', 'Ön-çat forması və CRM kontaktı'), l('Часы работы и офлайн-сообщение', 'İş saatları və oflayn mesaj')], auditRefs: ['M06-S09'] },
  { id: 'ai-agent-settings', domainId: 'omni', order: 8, status: 'confirmed', visibility: 'public', icon: 'sparkles', title: l('AI-агент: настройки', 'AI agent: parametrlər'), description: l('Для каждого канала выбирается, кто отвечает: человек, AI-черновик или AI-агент. Персона, база знаний, эскалация оператору.', 'Hər kanal üçün kimin cavab verdiyi seçilir: insan, AI qaralaması və ya AI agent. Persona, bilik bazası, operatora eskalasiya.'), capabilities: [l('Режим ответа по каналам', 'Kanallar üzrə cavab rejimi'), l('Персона и база знаний', 'Persona və bilik bazası'), l('Автосоздание лида и задачи', 'Lid və tapşırığın avtomatik yaradılması'), l('Эскалация по ключевым словам', 'Açar sözlərlə eskalasiya')], auditRefs: ['M06-S10'] },
  { id: 'call-insights', domainId: 'omni', order: 9, status: 'confirmed', visibility: 'public', icon: 'sparkles', title: l('AI-анализ звонков', 'Zənglərin AI təhlili'), description: l('После звонка AI готовит резюме разговора, темы, настроение клиента и задачи для менеджера.', 'Zəngdən sonra AI söhbətin xülasəsini, mövzuları, müştərinin əhvalını və menecer üçün tapşırıqları hazırlayır.'), capabilities: [l('Резюме и темы разговора', 'Söhbətin xülasəsi və mövzuları'), l('Настроение клиента', 'Müştərinin əhvalı'), l('Задачи из разговора', 'Söhbətdən tapşırıqlar')], auditRefs: ['M08-S01'] },
  { id: 'inbox-analytics', domainId: 'omni', order: 5, status: 'confirmed', visibility: 'public', icon: 'chart', title: l('Аналитика входящих', 'Daxil olanların analitikası'), description: l('Нагрузка по каналам, время первого ответа, невыполненные обращения, участие AI и передача лидов в продажи.', 'Kanallar üzrə yük, ilk cavab vaxtı, gözləyən müraciətlər, AI iştirakı və lidlərin satışa ötürülməsi.'), capabilities: [l('Первый ответ и backlog', 'İlk cavab və gözləyənlər'), l('Передача в продажи', 'Satışa ötürmə')], auditRefs: ['M06-S03'] },


  // ——— Social monitoring (M07) ———
  { id: 'social-sources', domainId: 'social', order: 1, status: 'confirmed', visibility: 'public', icon: 'radio', title: l('Источники и сценарии', 'Mənbələr və ssenarilər'), description: l('Собственные страницы, внешние профили и URL как источники. Сценарии задают ключевые слова, платформы и правило AI-классификации.', 'Öz səhifələr, xarici profillər və URL-lər mənbə kimi. Ssenarilər açar sözləri, platformaları və AI təsnifat qaydasını təyin edir.'), capabilities: [l('Instagram, Facebook, TikTok, YouTube, WEB-новости', 'Instagram, Facebook, TikTok, YouTube, WEB xəbərləri'), l('Ключевые слова и хештеги', 'Açar sözlər və həştəqlər'), l('Объекты мониторинга и алиасы', 'Monitorinq obyektləri və aliaslar')], auditRefs: ['M07-S02', 'M07-S05', 'M07-S06', 'M07-S07'] },
  { id: 'social-findings', domainId: 'social', order: 2, status: 'confirmed', visibility: 'public', icon: 'funnel', title: l('Находки и ответы', 'Tapıntılar və cavablar'), description: l('Посты, комментарии и медиа с фильтрами по языку и периоду. AI готовит черновики ответов; отправка требует подтверждения.', 'Dil və dövr üzrə filtrlərlə paylaşımlar, şərhlər və media. AI cavab qaralamaları hazırlayır; göndərmə təsdiq tələb edir.'), capabilities: [l('Тональность и приоритет', 'Tonallıq və prioritet'), l('AI-черновики с подтверждением', 'Təsdiqli AI qaralamaları'), l('Юридические риски на проверку человеком', 'İnsan yoxlamasına hüquqi risklər')], auditRefs: ['M07-S03', 'M07-S04', 'M07-S10', 'M07-S11'] },
  { id: 'social-reports', domainId: 'social', order: 3, status: 'confirmed', visibility: 'public', icon: 'file', title: l('Отчёты и медиа-анализ', 'Hesabatlar və media təhlili'), description: l('Еженедельная сводка новых находок, конструктор PDF-отчёта с предпросмотром и настройки обработки видео и изображений с бюджетами.', 'Yeni tapıntıların həftəlik icmalı, önizləməli PDF hesabat qurucusu və büdcəli video/şəkil emalı parametrləri.'), capabilities: [l('Сводка для клиента и XLSX', 'Müştəri üçün icmal və XLSX'), l('PDF-отчёт по разделам', 'Bölmələr üzrə PDF hesabat'), l('OCR и распознавание речи по лимитам', 'Limitlərlə OCR və nitq tanıma')], auditRefs: ['M07-S01', 'M07-S08', 'M07-S09', 'M07-S12'] },


  // ——— Support (M09) ———
  { id: 'service-desk', domainId: 'support', order: 1, status: 'confirmed', visibility: 'public', icon: 'kanban', title: l('Service Desk', 'Service Desk'), description: l('Список и канбан тикетов, карточка с ответом клиенту, внутренними заметками, статусами и назначением. Отчёты по SLA, категориям, источникам и агентам.', 'Tiketlərin siyahısı və kanbanı, müştəriyə cavab, daxili qeydlər, statuslar və təyinatla kart. SLA, kateqoriya, mənbə və agentlər üzrə hesabatlar.'), capabilities: [l('Приоритеты, SLA и эскалация', 'Prioritetlər, SLA və eskalasiya'), l('Ответ, заметка, макрос в один клик', 'Cavab, qeyd, bir kliklik makro'), l('Отчёты службы поддержки', 'Dəstək hesabatları')], auditRefs: ['M09-S01', 'M09-S01-T1', 'M09-S01-T2', 'M09-S01-D1', 'M09-S13'] },
  { id: 'sla-routing', domainId: 'support', order: 2, status: 'confirmed', visibility: 'public', icon: 'timer', title: l('SLA, условия и маршрутизация', 'SLA, şərtlər və yönləndirmə'), description: l('Политики SLA по приоритетам, правила эскалации, условия поддержки для компаний с шаблонами по уровням, очереди по навыкам агентов.', 'Prioritetlər üzrə SLA siyasətləri, eskalasiya qaydaları, səviyyə şablonları ilə şirkətlər üçün dəstək şərtləri, agent bacarıqları üzrə növbələr.'), capabilities: [l('Сроки ответа и решения', 'Cavab və həll müddətləri'), l('Уровни эскалации L1–L3', 'L1–L3 eskalasiya səviyyələri'), l('Очереди по навыкам', 'Bacarıq üzrə növbələr'), l('Категории тикетов', 'Tiket kateqoriyaları')], auditRefs: ['M09-S06', 'M09-S07', 'M09-S08', 'M09-S09', 'M09-S10', 'M09-S12'] },
  { id: 'complaints', domainId: 'support', order: 3, status: 'confirmed', visibility: 'public', icon: 'quote', title: l('Реестр жалоб', 'Şikayət reyestri'), description: l('Жалобы и предложения с источником, маркой, продуктом, ответственным отделом и уровнем риска. Импорт и экспорт XLSX.', 'Mənbə, marka, məhsul, məsul şöbə və risk səviyyəsi ilə şikayət və təkliflər. XLSX idxal və ixrac.'), capabilities: [l('Риск и статус обращения', 'Müraciətin riski və statusu'), l('Связь с тикетами', 'Tiketlərlə əlaqə')], auditRefs: ['M09-S02'] },
  { id: 'agent-workspace', domainId: 'support', order: 4, status: 'confirmed', visibility: 'public', icon: 'users', title: l('Рабочий стол и календарь агента', 'Agent masaüstü və təqvimi'), description: l('Личные и командные показатели, открытые обращения, рейтинг агентов и недельный календарь тикетов и задач.', 'Şəxsi və komanda göstəriciləri, açıq müraciətlər, agent reytinqi və tiket-tapşırıq həftəlik təqvimi.'), capabilities: [l('CSAT и SLA команды', 'Komandanın CSAT və SLA-sı'), l('Календарь тикетов и задач', 'Tiket və tapşırıq təqvimi')], auditRefs: ['M09-S03', 'M09-S11'] },
  { id: 'knowledge-portal', domainId: 'support', order: 5, status: 'confirmed', visibility: 'public', icon: 'file', title: l('База знаний и портал', 'Bilik bazası və portal'), description: l('Статьи для агентов и AI-ответов, доступ контактов к клиентскому порталу. Единый переключатель AI-функций поддержки.', 'Agentlər və AI cavabları üçün məqalələr, kontaktların müştəri portalına girişi. Dəstək AI funksiyalarının vahid açarı.'), capabilities: [l('Статьи и категории', 'Məqalələr və kateqoriyalar'), l('Пользователи портала', 'Portal istifadəçiləri'), l('AI-черновики и резюме тикетов', 'Tiketlərin AI qaralamaları və xülasələri')], auditRefs: ['M09-S05', 'M09-S14', 'M09-S15'] },


  // ——— Finance (M10) ———
  { id: 'invoices', domainId: 'finance', order: 1, status: 'confirmed', visibility: 'public', icon: 'file', title: l('Счета', 'Hesab-fakturalar'), description: l('Реестр счетов со статусами и остатками, карточка с позициями, платежами и цепочкой напоминаний. Позиции из каталога, скидка и НДС.', 'Status və qalıqlarla faktura reyestri, mövqelər, ödənişlər və xatırlatma zənciri ilə kart. Kataloqdan mövqelər, endirim və ƏDV.'), capabilities: [l('Статусы: черновик, отправлен, оплачен, просрочен', 'Statuslar: qaralama, göndərilib, ödənilib, gecikmiş'), l('PDF и акт', 'PDF və akt'), l('Повторяющиеся счета', 'Təkrarlanan fakturalar'), l('Реквизиты, печать и подпись', 'Rekvizitlər, möhür və imza')], auditRefs: ['M10-S01', 'M10-S01-D1', 'M10-S01-T1', 'M10-S01-F1', 'M10-S06', 'M10-S07'] },
  { id: 'profitability', domainId: 'finance', order: 2, status: 'confirmed', visibility: 'public', icon: 'chart', title: l('Рентабельность и цены', 'Gəlirlilik və qiymətlər'), description: l('Модель затрат по услугам, клиентам, накладным расходам и штату. Ценовая модель услуг с корректировками по группам и компаниям.', 'Xidmətlər, müştərilər, əlavə xərclər və ştat üzrə xərc modeli. Qruplar və şirkətlər üzrə düzəlişli xidmət qiymət modeli.'), capabilities: [l('Маржа по услугам и клиентам', 'Xidmət və müştəri üzrə marja'), l('Накладные расходы и ФОТ', 'Əlavə xərclər və əmək haqqı fondu'), l('Ценовые корректировки', 'Qiymət düzəlişləri'), l('Подписки и MRR', 'Abunəliklər və MRR')], auditRefs: ['M10-S02', 'M10-S04', 'M10-S04-T1', 'M10-S04-T2', 'M10-S04-T3', 'M10-S04-T4', 'M10-S05'] },


  // ——— Analytics (M11) ———
  { id: 'reports', domainId: 'analytics', order: 1, status: 'confirmed', visibility: 'public', icon: 'chart', title: l('Отчёты и конструктор', 'Hesabatlar və qurucu'), description: l('Сводная панель по клиентам, сделкам, лидам, задачам и тикетам с прогнозом продаж. Конструктор отчётов с выбором объекта, столбцов, фильтров и графиков.', 'Satış proqnozu ilə müştərilər, sövdələşmələr, lidlər, tapşırıqlar və tiketlər üzrə icmal panel. Obyekt, sütun, filtr və qrafik seçimi ilə hesabat qurucusu.'), capabilities: [l('Показатели и топ клиентов', 'Göstəricilər və top müştərilər'), l('Таблица и графики по объекту', 'Obyekt üzrə cədvəl və qrafiklər'), l('Экспорт CSV', 'CSV ixracı')], auditRefs: ['M11-S01', 'M11-S02'] },
  { id: 'kpi-arena', domainId: 'analytics', order: 2, status: 'confirmed', visibility: 'public', icon: 'target', title: l('KPI Arena', 'KPI Arena'), description: l('Живой рейтинг сотрудников по выполнению KPI: продажи, полевые агенты, поддержка, проекты и задачи.', 'KPI icrası üzrə canlı əməkdaş reytinqi: satış, sahə agentləri, dəstək, layihələr və tapşırıqlar.'), capabilities: [l('Пузырьковый и списочный вид', 'Qabarcıq və siyahı görünüşü'), l('Периоды от дня до года', 'Gündən ilə qədər dövrlər')], auditRefs: ['M11-S04'] },
  { id: 'davinci-center', domainId: 'analytics', order: 3, status: 'confirmed', visibility: 'public', icon: 'sparkles', title: l('Центр управления Da Vinci', 'Da Vinci idarəetmə mərkəzi'), description: l('Метрики AI-агентов, сессии и журнал вызовов с моделью, временем и стоимостью. Конструктор агентов с инструментами, правилами и ограничениями.', 'AI agentlərinin metrikaları, sessiyalar və model, vaxt və xərc ilə çağırış jurnalı. Alətlər, qaydalar və məhdudiyyətlərlə agent konstruktoru.'), capabilities: [l('Сессии, эскалации, задержки', 'Sessiyalar, eskalasiyalar, gecikmələr'), l('Агенты продаж, поддержки, соцсетей, договоров', 'Satış, dəstək, sosial, müqavilə agentləri'), l('Правила и защита промпта', 'Qaydalar və prompt qoruması')], auditRefs: ['M11-S03', 'M11-S03-T1'] },


  // ——— Field / MTM (M12) ———
  { id: 'field-routes', domainId: 'field', order: 1, status: 'confirmed', visibility: 'public', icon: 'route', title: l('Маршруты, визиты и живая карта', 'Marşrutlar, vizitlər və canlı xəritə'), description: l('Календарь маршрутов по дням, регистрация визитов с GPS-подтверждением, позиции агентов на карте и история перемещений.', 'Günlər üzrə marşrut təqvimi, GPS təsdiqi ilə vizit qeydi, agentlərin xəritədə mövqeləri və hərəkət tarixçəsi.'), capabilities: [l('Планирование маршрута по точкам', 'Nöqtələr üzrə marşrut planı'), l('GPS-статусы и геозоны', 'GPS statusları və geozonalar'), l('Предупреждения об отклонениях', 'Sapma xəbərdarlıqları')], auditRefs: ['M12-S01', 'M12-S02', 'M12-S03', 'M12-S05', 'M12-S11', 'M12-S17'] },
  { id: 'field-points', domainId: 'field', order: 2, status: 'confirmed', visibility: 'public', icon: 'users', title: l('Точки, контакты и задачи', 'Nöqtələr, kontaktlar və tapşırıqlar'), description: l('Каталог организаций с категориями и назначением агентам, полевые контакты (врачи, фармацевты), задачи по точкам и промо-операции аптек.', 'Kateqoriyalar və agent təyinatı ilə təşkilat kataloqu, sahə kontaktları (həkimlər, əczaçılar), nöqtələr üzrə tapşırıqlar və aptek promo əməliyyatları.'), capabilities: [l('Категории A–D и ответственные', 'A–D kateqoriyaları və məsullar'), l('Мерчендайзинговые задачи', 'Merçendayzinq tapşırıqları'), l('Промо-факты с проверкой L1/L2', 'L1/L2 yoxlamalı promo faktları')], auditRefs: ['M12-S06', 'M12-S07', 'M12-S08', 'M12-S09'] },
  { id: 'field-control', domainId: 'field', order: 3, status: 'confirmed', visibility: 'public', icon: 'chart', title: l('Контроль и отчёты поля', 'Sahə nəzarəti və hesabatları'), description: l('Фотоотчёты с модерацией, операционный центр для сообщений и документов агентам, журнал активности, рейтинг агентов и аналитика исполнения плана.', 'Moderasiyalı fotohesabatlar, agentlərə mesaj və sənədlər üçün əməliyyat mərkəzi, aktivlik jurnalı, agent reytinqi və plan icrası analitikası.'), capabilities: [l('Подтверждение и отклонение фото', 'Fotoların təsdiqi və rəddi'), l('Объявления и документы команде', 'Komandaya elanlar və sənədlər'), l('Исполнение плана и GPS-подтверждение', 'Plan icrası və GPS təsdiqi')], auditRefs: ['M12-S04', 'M12-S10', 'M12-S12', 'M12-S13', 'M12-S14', 'M12-S15', 'M12-S16'] },

  { id: 'workforce', domainId: 'field', order: 4, status: 'confirmed', visibility: 'public', icon: 'timer', title: l('Рабочее время команды', 'Komandanın iş vaxtı'), description: l('Состояние рабочего дня сотрудников, табель с подтверждением периода, запросы на отпуск и корректировки, политики и шаблоны смен.', 'Əməkdaşların iş günü vəziyyəti, dövr təsdiqi ilə tabel, məzuniyyət və düzəliş sorğuları, siyasətlər və növbə şablonları.'), capabilities: [l('Табель и подтверждение периода', 'Tabel və dövr təsdiqi'), l('Политики расчёта и смены', 'Hesablama siyasətləri və növbələr'), l('Запросы сотрудников', 'Əməkdaş sorğuları')], auditRefs: ['M13-S01', 'M13-S02', 'M13-S03', 'M13-S04'] },

  // ——— Marketing (M04) ———
  { id: 'campaigns', domainId: 'marketing', order: 1, status: 'confirmed', visibility: 'public', icon: 'target', title: l('Кампании и сегменты', 'Kampaniyalar və seqmentlər'), description: l('Аудитория из контактов, лидов или сегментов, выбор каналов и шаблонов, A/B-варианты. Сегменты собирают контакты по условиям.', 'Kontaktlar, lidlər və ya seqmentlərdən auditoriya, kanal və şablon seçimi, A/B variantları. Seqmentlər kontaktları şərtlərə görə toplayır.'), capabilities: [l('Аудитории и каналы', 'Auditoriyalar və kanallar'), l('A/B-варианты', 'A/B variantları'), l('Динамические сегменты', 'Dinamik seqmentlər')], auditRefs: ['M04-S01', 'M04-S02'] },
  { id: 'email', domainId: 'marketing', order: 2, status: 'confirmed', visibility: 'public', icon: 'file', title: l('Email: шаблоны и журнал', 'E-poçt: şablonlar və jurnal'), description: l('Шаблоны с локализацией и переменными. Журнал входящих и исходящих писем с диагностикой доставки.', 'Lokalizasiya və dəyişənləri olan şablonlar. Çatdırılma diaqnostikası ilə daxil olan və göndərilən məktubların jurnalı.'), capabilities: [l('Локализация и переменные', 'Lokalizasiya və dəyişənlər'), l('Журнал доставки', 'Çatdırılma jurnalı')], auditRefs: ['M04-S03', 'M04-S04'] },
  { id: 'journeys', domainId: 'marketing', order: 3, status: 'confirmed', visibility: 'public', icon: 'route', title: l('Цепочки касаний', 'Əlaqə ssenariləri'), description: l('События запуска, шаги, задержки, условия и участники маркетинговых цепочек.', 'Marketinq ssenarilərinin başlanğıc hadisələri, addımları, fasilələri, şərtləri və iştirakçıları.'), capabilities: [l('События и условия', 'Hadisələr və şərtlər'), l('Шаги и задержки', 'Addımlar və fasilələr'), l('Участники', 'İştirakçılar')], auditRefs: ['M04-S08'] },
  { id: 'attribution', domainId: 'marketing', order: 4, status: 'confirmed', visibility: 'public', icon: 'chart', title: l('Атрибуция и ROI', 'Atribusiya və ROI'), description: l('Модели распределения выручки между касаниями и отчёт по эффективности кампаний.', 'Gəlirin əlaqə nöqtələri arasında bölünmə modelləri və kampaniya effektivliyi hesabatı.'), capabilities: [l('Модели атрибуции', 'Atribusiya modelləri'), l('ROI кампаний', 'Kampaniya ROI-si')], auditRefs: ['M04-S05', 'M04-S06'] },
  { id: 'events', domainId: 'marketing', order: 5, status: 'confirmed', visibility: 'public', icon: 'calendar', title: l('Мероприятия', 'Tədbirlər'), description: l('Планирование мероприятий, бюджеты, участники и приглашения.', 'Tədbirlərin planlaşdırılması, büdcələr, iştirakçılar və dəvətlər.'), capabilities: [l('Бюджет и участники', 'Büdcə və iştirakçılar'), l('Приглашения', 'Dəvətlər')], auditRefs: ['M04-S09'] },
  { id: 'surveys', domainId: 'marketing', order: 6, status: 'confirmed', visibility: 'public', icon: 'quote', title: l('Опросы и NPS', 'Sorğular və NPS'), description: l('Опросы с публичной анкетой, NPS и связь ответов с карточками CRM.', 'İctimai anketli sorğular, NPS və cavabların CRM kartları ilə əlaqəsi.'), capabilities: [l('NPS и вопросы', 'NPS və suallar'), l('Ответы в контексте клиента', 'Müştəri kontekstində cavablar')], auditRefs: ['M04-S10'] },
  { id: 'abm', domainId: 'marketing', order: 7, status: 'confirmed', visibility: 'public', icon: 'sparkles', title: l('Приоритеты: ABM и рейтинг лидов', 'Prioritetlər: ABM və lid reytinqi'), description: l('Целевые компании по соответствию профилю и активности. Da Vinci показывает рейтинг качества лидов.', 'Profilə uyğunluq və aktivliyə görə hədəf şirkətlər. Da Vinci lidlərin keyfiyyət reytinqini göstərir.'), capabilities: [l('Соответствие профилю', 'Profilə uyğunluq'), l('Рейтинг лидов', 'Lid reytinqi')], auditRefs: ['M04-S11', 'M04-S07'] },

  // ——— Contracts (M03) ———
  { id: 'contract-registry', domainId: 'contracts', order: 1, status: 'confirmed', visibility: 'public', icon: 'file', title: l('Реестр и карточка договора', 'Müqavilə reyestri və kartı'), description: l('Реквизиты, текст, версии, цепочка согласования, конверты подписи, отклонения от шаблона, этапы и обязательства.', 'Rekvizitlər, mətn, versiyalar, təsdiq zənciri, imza zərfləri, şablondan kənarlaşmalar, mərhələlər və öhdəliklər.'), capabilities: [l('Версии и сравнение', 'Versiyalar və müqayisə'), l('Согласование и подпись', 'Təsdiq və imza'), l('Отклонения и обязательства', 'Kənarlaşmalar və öhdəliklər')], auditRefs: ['M03-S01'] },
  { id: 'contract-templates', domainId: 'contracts', order: 2, status: 'confirmed', visibility: 'public', icon: 'layers', title: l('Шаблоны и пункты', 'Şablonlar və bəndlər'), description: l('Шаблоны с переменными и блоками текста. Библиотека пунктов с владельцами и уровнями риска.', 'Dəyişənləri və mətn blokları olan şablonlar. Sahibləri və risk səviyyələri olan bəndlər kitabxanası.'), capabilities: [l('Переменные и блоки', 'Dəyişənlər və bloklar'), l('Уровни риска пунктов', 'Bəndlərin risk səviyyələri')], auditRefs: ['M03-S03'] },
  { id: 'contract-requests', domainId: 'contracts', order: 3, status: 'confirmed', visibility: 'public', icon: 'kanban', title: l('Запросы на договор', 'Müqavilə sorğuları'), description: l('Формы, по которым сотрудники запрашивают договор, стандартные этапы согласования и очередь запросов.', 'Əməkdaşların müqavilə tələb etdiyi formalar, standart təsdiq mərhələləri və sorğu növbəsi.'), capabilities: [l('Формы запросов', 'Sorğu formaları'), l('Очередь и связь с договором', 'Növbə və müqavilə ilə əlaqə')], auditRefs: ['M03-S04', 'M03-S05'] },
  { id: 'contract-lifecycle', domainId: 'contracts', order: 4, status: 'confirmed', visibility: 'public', icon: 'timer', title: l('Жизненный цикл и аналитика', 'Həyat dövrü və analitika'), description: l('Напоминания о продлении, задержки согласований, правила маршрута и делегирование. Аналитика сроков, стоимости и отклонений.', 'Uzadılma xatırlatmaları, təsdiq gecikmələri, marşrut qaydaları və nümayəndəlik. Müddət, dəyər və kənarlaşmalar analitikası.'), capabilities: [l('Продления и задержки', 'Uzadılmalar və gecikmələr'), l('Правила и делегирование', 'Qaydalar və nümayəndəlik'), l('Аналитика договоров', 'Müqavilə analitikası')], auditRefs: ['M03-S02', 'M03-S06', 'M03-S07', 'M03-S08', 'M03-S09'] },

  // ——— Loyalty (M05) ———
  { id: 'loyalty-builder', domainId: 'loyalty', order: 1, status: 'confirmed', visibility: 'public', icon: 'gift', title: l('Конструктор программы', 'Proqram konstruktoru'), description: l('Уровни, правила начисления, награды, промокоды и участники в одном конструкторе с предварительным расчётом баллов.', 'Səviyyələr, xal qaydaları, mükafatlar, promo-kodlar və iştirakçılar bir konstruktorda, xalların ilkin hesablanması ilə.'), capabilities: [l('Уровни и пороги', 'Səviyyələr və hədlər'), l('Правила начисления', 'Xal qazanma qaydaları'), l('Награды и промокоды', 'Mükafatlar və promo-kodlar')], auditRefs: ['M05-S01', 'M05-S04', 'M05-S05', 'M05-S06'] },
  { id: 'loyalty-dashboard', domainId: 'loyalty', order: 2, status: 'confirmed', visibility: 'public', icon: 'chart', title: l('Панель и история участника', 'Panel və iştirakçı tarixçəsi'), description: l('Состояние программы, распределение уровней и активность. У участника видны баланс и накопленные баллы.', 'Proqramın vəziyyəti, səviyyələrin bölgüsü və aktivlik. İştirakçının balansı və toplanmış xalları görünür.'), capabilities: [l('Здоровье программы', 'Proqramın vəziyyəti'), l('Баланс и история баллов', 'Balans və xal tarixçəsi')], auditRefs: ['M05-S02', 'M05-S01-T7-D1'] },

  // ——— Platform / settings (M19) ———
  { id: 'roles-access', domainId: 'platform', order: 1, status: 'confirmed', visibility: 'public', icon: 'users', title: l('Роли и права доступа', 'Rollar və giriş hüquqları'), description: l('Системные и свои роли, матрица доступа к модулям и права на отдельные поля. По умолчанию сотрудник видит только свои записи, правила совместного доступа расширяют видимость.', 'Sistem və xüsusi rollar, modullara giriş matrisi və ayrı-ayrı sahələrə hüquqlar. Standart olaraq əməkdaş yalnız öz qeydlərini görür, paylaşma qaydaları görünürlüyü genişləndirir.'), capabilities: [l('Матрица модуль × роль', 'Modul × rol matrisi'), l('Права на поля и отметка чувствительных', 'Sahə hüquqları və həssas işarəsi'), l('Правила совместного доступа', 'Paylaşma qaydaları')], auditRefs: ['M19-S03', 'M19-S18'] },
  { id: 'security', domainId: 'platform', order: 2, status: 'confirmed', visibility: 'public', icon: 'lock', title: l('Безопасность и аудит', 'Təhlükəsizlik və audit'), description: l('Двухфакторная защита входа через приложение или SMS, API-ключи для интеграций и журнал всех действий: кто, что и когда.', 'Tətbiq və ya SMS ilə ikifaktorlu giriş, inteqrasiyalar üçün API açarları və bütün hərəkətlərin jurnalı: kim, nə və nə vaxt.'), capabilities: [l('2FA: приложение и SMS', '2FA: tətbiq və SMS'), l('API-ключи с отзывом', 'Ləğv edilə bilən API açarları'), l('Журнал аудита с фильтрами', 'Filtrli audit jurnalı')], auditRefs: ['M19-S04', 'M19-S05', 'M19-S17'] },
  { id: 'custom-fields', domainId: 'platform', order: 3, status: 'confirmed', visibility: 'public', icon: 'layers', title: l('Свои поля и справочники', 'Öz sahələr və soraqçalar'), description: l('Текст, число, дата, да/нет и списки для контактов, компаний, сделок, лидов и задач. Поля видны в формах и доступны в условиях автоматизаций.', 'Kontakt, şirkət, sövdələşmə, lid və tapşırıqlar üçün mətn, rəqəm, tarix, bəli/xeyr və siyahılar. Sahələr formalarda görünür və avtomatlaşdırma şərtlərində istifadə olunur.'), capabilities: [l('Пять типов полей', 'Beş sahə növü'), l('Поля в условиях workflow', 'Workflow şərtlərində sahələr')], auditRefs: ['M19-S06'] },
  { id: 'workflows', domainId: 'platform', order: 4, status: 'confirmed', visibility: 'public', icon: 'workflow', title: l('Автоматизации', 'Avtomatlaşdırmalar'), description: l('Правила «когда произошло событие → сделать действие»: письмо, задача, уведомление, вебхук, автоназначение. Готовые шаблоны для продаж, маркетинга, поддержки и операций.', '«Hadisə baş verdi → hərəkət et» qaydaları: məktub, tapşırıq, bildiriş, vebhuk, avtotəyinat. Satış, marketinq, dəstək və əməliyyatlar üçün hazır şablonlar.'), capabilities: [l('Триггеры по лидам, контактам, сделкам, тикетам', 'Lid, kontakt, sövdələşmə, tiket triggerləri'), l('Условия и несколько действий', 'Şərtlər və bir neçə hərəkət'), l('Шаблоны в один клик', 'Bir kliklə şablonlar')], auditRefs: ['M19-S10', 'M19-S11'] },
  { id: 'ai-delegation', domainId: 'platform', order: 5, status: 'confirmed', visibility: 'public', icon: 'sparkles', title: l('AI-делегирование', 'AI-yə həvalə'), description: l('Три уровня: AI анализирует, AI предлагает на проверку, AI действует сам. Дневной бюджет, лимиты ответов и сводки по email, Telegram или Slack.', 'Üç səviyyə: AI analiz edir, AI yoxlamaya təklif edir, AI özü edir. Gündəlik büdcə, cavab limitləri və email, Telegram və ya Slack ilə icmallar.'), capabilities: [l('Режим «проверка» перед автопилотом', 'Avtopilotdan əvvəl «yoxla» rejimi'), l('14 сценариев автопилота', '14 avtopilot ssenarisi'), l('Дневной бюджет AI', 'Gündəlik AI büdcəsi')], auditRefs: ['M19-S21'] },
  { id: 'integrations', domainId: 'platform', order: 6, status: 'confirmed', visibility: 'public', icon: 'plug', title: l('Интеграции и каналы', 'İnteqrasiyalar və kanallar'), description: l('Вебхуки и Zapier, уведомления в Slack и Teams, Google Calendar, встроенная электронная подпись и DocuSign, трекинг сайта, телефония Twilio, 3CX, Asterisk или SIP, почта из коробки или свой SMTP, свой домен для лендингов.', 'Vebhuklar və Zapier, Slack və Teams bildirişləri, Google Calendar, daxili elektron imza və DocuSign, sayt izləmə, Twilio, 3CX, Asterisk və ya SIP telefoniya, hazır poçt və ya öz SMTP, lendinqlər üçün öz domen.'), capabilities: [l('Вебхуки по событиям', 'Hadisə vebhukları'), l('Телефония и AI-оператор звонков', 'Telefoniya və AI zəng operatoru'), l('Web-трекинг с режимом согласия', 'Razılıq rejimli veb-izləmə')], auditRefs: ['M19-S08', 'M19-S13', 'M19-S14', 'M19-S15'] },
  { id: 'marketplace', domainId: 'platform', order: 7, status: 'confirmed', visibility: 'public', icon: 'package', title: l('Магазин расширений', 'Genişləndirmə mağazası'), description: l('Официальные пакеты LeadDrive: поля, автоматизации и вебхуки под конкретную задачу, например защита от дублей лидов или SLA-эскалация.', 'LeadDrive-ın rəsmi paketləri: konkret tapşırıq üçün sahələr, avtomatlaşdırmalar və vebhuklar, məsələn dublikat lid qoruması və ya SLA eskalasiyası.'), capabilities: [l('14 официальных пакетов', '14 rəsmi paket'), l('Установка в один клик', 'Bir kliklə quraşdırma')], auditRefs: ['M19-S16'] },
  { id: 'team-settings', domainId: 'platform', order: 8, status: 'confirmed', visibility: 'public', icon: 'settings', title: l('Команда и рабочее место', 'Komanda və iş yeri'), description: l('Пользователи с ролями, отделами и навыками, персональные уведомления по модулям, состав и порядок блоков дашборда, лимит минут голосового помощника.', 'Rol, şöbə və bacarıqları olan istifadəçilər, modullar üzrə şəxsi bildirişlər, dashboard bloklarının tərkibi və sırası, səsli köməkçi üçün dəqiqə limiti.'), capabilities: [l('Пользователи и доступность', 'İstifadəçilər və mövcudluq'), l('Уведомления по модулям', 'Modullar üzrə bildirişlər'), l('Настройка дашборда', 'Dashboard tənzimi')], auditRefs: ['M19-S01', 'M19-S07', 'M19-S09', 'M19-S12'] },
];

export const INDUSTRIES: IndustryScenario[] = [
  { id: 'health', order: 1, status: 'confirmed', icon: 'heart', title: l('Медицина', 'Səhiyyə'), summary: l('Пациенты и клинический контур для медицинского учреждения.', 'Tibb müəssisəsi üçün xəstələr və klinik kontur.'), sections: [l('Пациенты', 'Xəstələr'), l('Визиты', 'Ziyarətlər'), l('Планы лечения', 'Müalicə planları'), l('Врачи и персонал', 'Həkimlər və personal')], auditRefs: ['M14-S01', 'M14-S02', 'M14-S03', 'M14-S04'] },
  { id: 'insurance', order: 2, status: 'confirmed', icon: 'umbrella', title: l('Страхование', 'Sığorta'), summary: l('Застрахованные, полисы и работа с требованиями.', 'Sığortalılar, polislər və iddialarla iş.'), sections: [l('Застрахованные', 'Sığortalılar'), l('Полисы', 'Polislər'), l('Страховые требования', 'İddialar'), l('Бенефициары', 'Benefisiarlar')], auditRefs: ['M15-S01', 'M15-S02', 'M15-S03', 'M15-S04'] },
  { id: 'public-sector', order: 3, status: 'confirmed', icon: 'landmark', title: l('Госсектор', 'Dövlət sektoru'), summary: l('Обращения граждан, разрешительные документы и гранты.', 'Vətəndaş müraciətləri, icazə sənədləri və qrantlar.'), sections: [l('Граждане', 'Vətəndaşlar'), l('Дела и обращения', 'İşlər və müraciətlər'), l('Лицензии и разрешения', 'Lisenziyalar və icazələr'), l('Гранты', 'Qrantlar')], auditRefs: ['M16-S01', 'M16-S02', 'M16-S03', 'M16-S04'] },
  { id: 'media', order: 4, status: 'confirmed', icon: 'newspaper', title: l('Медиа', 'Media'), summary: l('Подписчики издания, контент и рекламные кампании.', 'Nəşrin abunəçiləri, kontent və reklam kampaniyaları.'), sections: [l('Подписчики', 'Abunəçilər'), l('Библиотека контента', 'Məzmun kitabxanası'), l('Рекламные кампании', 'Reklam kampaniyaları')], auditRefs: ['M17-S01', 'M17-S02', 'M17-S03'] },
  { id: 'energy', order: 5, status: 'confirmed', icon: 'zap', title: l('Энергетика и ЖКХ', 'Enerji və kommunal'), summary: l('Абоненты, точки учёта, аварии и сервисные вызовы.', 'Abonentlər, uçot nöqtələri, qəzalar və xidmət çağırışları.'), sections: [l('Клиенты', 'Müştərilər'), l('Точки учёта', 'Uçot nöqtələri'), l('Аварии', 'Qəzalar'), l('Сервисные вызовы', 'Xidmət çağırışları')], auditRefs: ['M18-S01', 'M18-S02', 'M18-S03', 'M18-S04'] },
];

export const publicIndustries = (): IndustryScenario[] => INDUSTRIES.filter((i) => i.status === 'confirmed').sort((a, b) => a.order - b.order);

/** Pain → solution pairs. Each solution names only modules that exist in MODULES (auditRefs there). */
export type SceneKind = 'inbox' | 'calls' | 'contract' | 'invoice' | 'field' | 'support';
export type Pain = { id: string; scene: SceneKind; domainId: string; pain: Localized; solution: Localized; modules: string[] };
export const PAINS: Pain[] = [
  { id: 'lost-messages', scene: 'inbox', domainId: 'omni', pain: l('Заявки теряются в WhatsApp, Instagram и Telegram у разных сотрудников', 'Müraciətlər müxtəlif əməkdaşların WhatsApp, Instagram və Telegram-ında itir'), solution: l('Один Inbox на все каналы: кто отвечает, за сколько, что не отвечено. Правила ответов и рабочие часы.', 'Bütün kanallar üçün bir Inbox: kim cavab verir, nə qədər vaxta, nə cavabsız qalıb. Cavab qaydaları və iş saatları.'), modules: ['inbox', 'channels'] },
  { id: 'forgotten-calls', scene: 'calls', domainId: 'sales', pain: l('Менеджер обещал перезвонить и забыл, лид ушёл к конкуренту', 'Menecer geri zəng edəcəyini söylədi və unutdu, lid rəqibə getdi'), solution: l('Очереди звонков по выбранным лидам, задачи из разговоров с датой по умолчанию, история и аналитика звонков.', 'Seçilmiş lidlər üzrə zəng növbələri, söhbətdən yaranan tapşırıqlar, zəng tarixçəsi və analitikası.'), modules: ['leads', 'voip-journal', 'call-insights'] },
  { id: 'slow-contracts', scene: 'contract', domainId: 'contracts', pain: l('Договор неделями ходит по согласованиям, версии путаются', 'Müqavilə həftələrlə təsdiqdə gəzir, versiyalar qarışır'), solution: l('Шаблоны с пунктами, цепочка согласования, версии, электронная подпись и напоминания о продлении.', 'Bəndli şablonlar, təsdiq zənciri, versiyalar, elektron imza və uzadılma xatırlatmaları.'), modules: ['contract-registry', 'contract-templates', 'contract-lifecycle'] },
  { id: 'unpaid-invoices', scene: 'invoice', domainId: 'finance', pain: l('Счета выставлены, а кто и сколько должен, видно только в Excel', 'Fakturalar kəsilib, amma kim nə qədər borcludur, yalnız Excel-də görünür'), solution: l('Счета с оплатами и напоминаниями, повторяющиеся счета, подписки и модель рентабельности по клиентам.', 'Ödəniş və xatırlatmalı fakturalar, təkrarlanan fakturalar, abunəliklər və müştərilər üzrə gəlirlilik modeli.'), modules: ['invoices', 'profitability'] },
  { id: 'field-blind', scene: 'field', domainId: 'field', pain: l('Полевые агенты в дороге, а что они реально сделали, неизвестно', 'Sahə agentləri yoldadır, real nə etdikləri isə bilinmir'), solution: l('Маршруты по дням, визиты с GPS, фотоотчёты с модерацией, живая карта и рейтинг KPI.', 'Günlük marşrutlar, GPS-li vizitlər, moderasiyalı fotohesabatlar, canlı xəritə və KPI reytinqi.'), modules: ['field-routes', 'field-control', 'kpi-arena'] },
  { id: 'support-drowning', scene: 'support', domainId: 'support', pain: l('Поддержка тонет в обращениях, сроки ответа никто не контролирует', 'Dəstək müraciətlərdə batır, cavab müddətlərinə heç kim nəzarət etmir'), solution: l('Тикеты с SLA и эскалацией, маршрутизация по навыкам, макросы, база знаний и клиентский портал.', 'SLA və eskalasiyalı tiketlər, bacarıq üzrə yönləndirmə, makrolar, bilik bazası və müştəri portalı.'), modules: ['service-desk', 'sla-routing', 'knowledge-portal'] },
];

/** AI delegation levels as shown in Settings → AI Avtomatlaşdırma (M19-S21). */
export const AI_LEVELS: { id: string; title: Localized; badge: Localized; text: Localized }[] = [
  { id: 'analyze', title: l('AI анализирует', 'AI analiz edir'), badge: l('Только чтение', 'Yalnız oxu'), text: l('Утренняя сводка, поиск аномалий, оценка лидов. Ничего не меняет.', 'Səhər icmalı, anomaliyaların tapılması, lidlərin qiymətləndirilməsi. Heç nə dəyişmir.') },
  { id: 'suggest', title: l('AI предлагает', 'AI təklif edir'), badge: l('Проверка', 'Yoxla'), text: l('Готовит напоминания и ответы. Без подтверждения сотрудника ничего не отправляется.', 'Xatırlatmalar və cavablar hazırlayır. Əməkdaşın təsdiqi olmadan heç nə göndərilmir.') },
  { id: 'autopilot', title: l('AI действует сам', 'AI özü edir'), badge: l('Автопилот', 'Avtopilot'), text: l('Отправляет сообщения и создаёт задачи автоматически. Включается по сценариям и в рамках дневного бюджета.', 'Mesajları göndərir və tapşırıqları avtomatik yaradır. Ssenarilər üzrə və gündəlik büdcə çərçivəsində işə salınır.') },
];

/** The 14 autopilot scenarios listed on the same screen. Names only; none is claimed as enabled by default. */
export const AUTOPILOT_SCENARIOS: Localized[] = [
  l('Предупреждение о кредитном лимите', 'Kredit limiti xəbərdarlığı'), l('Эскалация негативного тона', 'Neqativ ton eskalasiyası'), l('Эскалация горячего лида', 'İsti lidin eskalasiyası'), l('Автоклассификация тикетов', 'Avto-bilet təsnifatı'), l('Автозакрытие по базе знаний', 'Bilik bazası ilə avto-bağlama'), l('Продвижение стадии сделки', 'Sövdə mərhələsinin irəliləməsi'), l('Резюме встречи', 'Görüş xülasəsi'), l('Вирусное предупреждение', 'Viral xəbərdarlıq'), l('AI-ответ в соцсетях', 'AI sosial cavab'), l('Предложение о продлении', 'Yenilənmə təklifi'), l('Объединение дубликатов', 'Dublikatların birləşdirilməsi'), l('Автоответ по SLA', 'SLA avto-cavab'), l('Follow-up по застрявшим сделкам', 'Durğun sövdələr üçün follow-up'), l('Напоминание об оплате', 'Ödəniş xatırlatması'),
];

/** Channels, integrations and security facts seen in Kanallar (M06-S07) and Parametrlər (M19). Text chips only. */
export const TRUST: { id: string; title: Localized; items: Localized[] }[] = [
  { id: 'channels', title: l('Каналы общения', 'Ünsiyyət kanalları'), items: ['WhatsApp Business', 'Facebook Messenger', 'Instagram', 'Telegram', 'VK', 'TikTok'].map((x) => l(x, x)).concat([l('Веб-чат', 'Veb-çat'), l('Email', 'E-poçt'), l('SMS', 'SMS')]) },
  { id: 'telephony', title: l('Телефония', 'Telefoniya'), items: ['Twilio', '3CX', 'Asterisk', 'SIP', 'WhatsApp Calling'].map((x) => l(x, x)) },
  { id: 'integrations', title: l('Интеграции', 'İnteqrasiyalar'), items: [l('Вебхуки', 'Vebhuklar'), l('Zapier', 'Zapier'), l('Slack', 'Slack'), l('Microsoft Teams', 'Microsoft Teams'), l('Google Calendar', 'Google Calendar'), l('DocuSign', 'DocuSign'), l('SMTP', 'SMTP'), l('Web-трекинг', 'Veb-izləmə')] },
  { id: 'security', title: l('Безопасность и контроль', 'Təhlükəsizlik və nəzarət'), items: [l('2FA', '2FA'), l('Роли и права на поля', 'Rollar və sahə hüquqları'), l('Журнал аудита', 'Audit jurnalı'), l('API-ключи', 'API açarları'), l('AZ · RU · EN', 'AZ · RU · EN')] },
];

/** Numbers derived from the data above, never typed by hand. */
/** Audit figures (realtime-voice-chat/outputs/leaddrive-product-audit/section-register.json, module-register.json):
 *  19 top-level modules in the CRM navigation; 486 sections registered, 433 opened and confirmed on 6–7 Sep 2026. */
export const CRM_MODULES = 19;
export const CRM_SECTIONS_CONFIRMED = 433;
export const siteNumbers = () => ({ domains: publicDomains().length, modules: CRM_MODULES, sections: CRM_SECTIONS_CONFIRMED, screens: publicModules().length, channels: TRUST[0].items.length, autopilot: AUTOPILOT_SCENARIOS.length, industries: publicIndustries().length });

export const publicModules = (domainId?: string): ProductModule[] =>
  MODULES.filter((m) => m.status === 'confirmed' && m.visibility === 'public' && (!domainId || m.domainId === domainId)).sort((a, b) => a.order - b.order);

/** Domains that have at least one public confirmed module. */
export const publicDomains = (): ProductDomain[] =>
  DOMAINS.filter((d) => publicModules(d.id).length > 0).sort((a, b) => a.order - b.order);
