import type { Lang } from './product-map';

type Steps = Record<Lang, [string, string][]>;

export const STEPS_LABEL: Record<Lang, { eyebrow: string; title: string }> = {
  ru: { eyebrow: 'Как это работает', title: 'Четыре шага от внедрения до результата.' },
  az: { eyebrow: 'Bu necə işləyir', title: 'Tətbiqdən nəticəyə dörd addım.' },
  en: { eyebrow: 'How it works', title: 'Four steps from setup to result.' },
};

/** "How it works" steps per solution. Every step describes a screen or setting seen in the audit. */
export const SOLUTION_STEPS: Record<string, Steps> = {
  'whatsapp-crm': {
    az: [['Kanalları qoşun', 'Kanal kataloqunda WhatsApp Business, Instagram və Telegram üçün addım-addım təlimat; hər kanal üçün cavab rejimi və iş saatları seçilir.'], ['Növbələri və məsulları təyin edin', 'Söhbətlər növbələrə düşür, məsul şəxs avtomatik və ya əl ilə təyin olunur, cavabsız söhbətlər Inbox-da görünür.'], ['Söhbəti müştəriyə bağlayın', 'Hər söhbət lid və ya kontakta bağlanır, yazışma tarixçəsi müştəri kartında qalır.'], ['AI-ni tədricən qoşun', 'Əvvəlcə AI qaralaması, əməkdaş təsdiqləyir; sonra seçilmiş kanallarda AI agent, açar sözlərlə operatora ötürmə.']],
    ru: [['Подключите каналы', 'В каталоге каналов пошаговая инструкция для WhatsApp Business, Instagram и Telegram; для каждого канала выбирается режим ответа и рабочие часы.'], ['Настройте очереди и ответственных', 'Беседы попадают в очереди, ответственный назначается автоматически или вручную, неотвеченные видны в Inbox.'], ['Привяжите беседу к клиенту', 'Каждая беседа связана с лидом или контактом, история переписки остаётся в карточке клиента.'], ['Подключайте AI постепенно', 'Сначала AI-черновик с подтверждением сотрудника, затем AI-агент в выбранных каналах с передачей оператору по ключевым словам.']],
    en: [['Connect the channels', 'The channel catalogue has step-by-step setup for WhatsApp Business, Instagram and Telegram; a reply mode and business hours are chosen per channel.'], ['Set up queues and owners', 'Conversations land in queues, an owner is assigned automatically or by hand, unanswered chats are visible in the inbox.'], ['Link the chat to the customer', 'Every conversation is tied to a lead or contact; the history stays on the customer card.'], ['Add AI gradually', 'Start with AI drafts confirmed by an employee, then an AI agent on selected channels with keyword handover to an operator.']],
  },
  'sales-crm': {
    az: [['Boru xətləri qurun', 'Hər satış xətti üçün mərhələlər, ehtimallar və keçid qaydaları; bir neçə boru xətti paralel işləyir.'], ['Lidləri qəbul edin və bölün', 'Lidlər formadan, kanaldan və ya idxaldan gəlir, qiymətləndirilir və qaydalara görə menecerlərə paylanır.'], ['Təklif və sövdələşmə', 'Kommersiya təklifi kataloqdan yığılır, sövdələşmə mərhələ və növbəti addımla aparılır, zənglər növbədə.'], ['Proqnoz və kvotalar', 'Gəlir proqnozu boru xətti ehtimalından hesablanır, kvotalar rüb üzrə, dəyişikliklər şəlalə hesabatında.']],
    ru: [['Постройте воронки', 'Для каждой линии продаж свои стадии, вероятности и правила перехода; несколько воронок работают параллельно.'], ['Принимайте и распределяйте лиды', 'Лиды приходят из форм, каналов или импорта, квалифицируются и распределяются по правилам между менеджерами.'], ['Предложение и сделка', 'Коммерческое предложение собирается из каталога, сделка ведётся по стадиям с следующим шагом, звонки в очереди.'], ['Прогноз и квоты', 'Прогноз выручки считается по вероятностям стадий, квоты по кварталам, изменения видны в отчёте-водопаде.']],
    en: [['Build the pipelines', 'Each sales line gets its own stages, probabilities and transition rules; several pipelines run in parallel.'], ['Capture and distribute leads', 'Leads arrive from forms, channels or import, get qualified and are distributed to managers by rules.'], ['Quote and deal', 'A quote is built from the catalogue, the deal moves through stages with a next step, calls sit in queues.'], ['Forecast and quotas', 'Revenue forecast is calculated from stage probabilities, quotas per quarter, changes show in the waterfall report.']],
  },
  'support-helpdesk-crm': {
    az: [['Müraciət mənbələrini qoşun', 'E-poçt, WhatsApp, sayt çatı və portal müraciətləri avtomatik tiket olur.'], ['SLA və eskalasiyanı təyin edin', 'Prioritetlər üzrə cavab və həll müddətləri, L1–L3 eskalasiya qaydaları, şirkətlər üçün dəstək şərtləri.'], ['Agentləri və makroları hazırlayın', 'Bacarıq üzrə növbələr, ən az yüklü agentə avtomatik təyinat, tez-tez verilən cavablar üçün makrolar.'], ['Bilik bazası və portal', 'Məqalələr agentlərə və AI cavablarına kömək edir, müştəri portalda tiket statusunu görür.']],
    ru: [['Подключите источники обращений', 'Обращения из почты, WhatsApp, чата на сайте и портала автоматически становятся тикетами.'], ['Задайте SLA и эскалацию', 'Сроки ответа и решения по приоритетам, правила эскалации L1–L3, условия поддержки для компаний.'], ['Подготовьте агентов и макросы', 'Очереди по навыкам, автоназначение наименее загруженному агенту, макросы для частых ответов.'], ['База знаний и портал', 'Статьи помогают агентам и AI-ответам, клиент видит статус тикета в портале.']],
    en: [['Connect request sources', 'Requests from email, WhatsApp, website chat and the portal become tickets automatically.'], ['Set SLA and escalation', 'Response and resolution times by priority, L1–L3 escalation rules, support entitlements for companies.'], ['Prepare agents and macros', 'Skill-based queues, auto-assignment to the least loaded agent, macros for frequent replies.'], ['Knowledge base and portal', 'Articles help agents and AI replies; the customer sees the ticket status in the portal.']],
  },
  'field-sales-crm': {
    az: [['Nöqtələri və kontaktları yükləyin', 'Təşkilatlar kataloqu kateqoriya və məsul şəxslərlə, sahə kontaktları və tapşırıq şablonları.'], ['Marşrutları planlaşdırın', 'Günlük marşrut nöqtələr üzrə, agentə mobil tətbiqdə görünür.'], ['Vizitləri təsdiqləyin', 'GPS mövqe və geozona yoxlanılır, fotohesabat moderasiya növbəsinə düşür, sapmalar xəbərdarlıq verir.'], ['KPI və tabel', 'Plan icrası, foto təsdiqi və marşrut icrası çəkiləri ilə reytinq; iş vaxtı tabeli və təsdiqlər.']],
    ru: [['Загрузите точки и контакты', 'Каталог организаций с категориями и ответственными, полевые контакты и шаблоны задач.'], ['Спланируйте маршруты', 'Маршрут на день по точкам, агент видит его в мобильном приложении.'], ['Подтверждайте визиты', 'Проверяются GPS-позиция и геозона, фотоотчёт попадает в очередь модерации, отклонения дают предупреждение.'], ['KPI и табель', 'Рейтинг по весам исполнения плана, подтверждения фото и маршрута; табель рабочего времени и подтверждения.']],
    en: [['Load points and contacts', 'An organisation catalogue with categories and owners, field contacts and task templates.'], ['Plan the routes', 'A daily route by points, visible to the agent in the mobile app.'], ['Confirm visits', 'GPS position and geofence are checked, photo reports go to the moderation queue, deviations raise alerts.'], ['KPI and timesheet', 'Ranking by weights for plan execution, photo approval and route execution; working-time timesheet and approvals.']],
  },
  'contract-management': {
    az: [['Şablonları hazırlayın', 'Bəndli şablonlar, risk səviyyələri və öhdəliklər; standart təsdiq mərhələləri.'], ['Müqavilə tələb edin', 'Əməkdaş formadan tələb göndərir, sənəd şablondan yığılır və reyestrə düşür.'], ['Təsdiq və imza', 'Marşrut qaydaları ilə təsdiq zənciri, versiyaların müqayisəsi, daxili imza və ya DocuSign.'], ['Nəzarət və uzadılma', 'Uzadılma xatırlatmaları, gecikmə analitikası, müqavilə kartında bütün tarixçə.']],
    ru: [['Подготовьте шаблоны', 'Шаблоны с пунктами, уровнями риска и обязательствами; стандартные этапы согласования.'], ['Запросите договор', 'Сотрудник отправляет запрос через форму, документ собирается из шаблона и попадает в реестр.'], ['Согласование и подпись', 'Цепочка согласования по правилам маршрута, сравнение версий, встроенная подпись или DocuSign.'], ['Контроль и продление', 'Напоминания о продлении, аналитика задержек, вся история в карточке договора.']],
    en: [['Prepare templates', 'Templates with clauses, risk levels and obligations; standard approval stages.'], ['Request a contract', 'An employee sends a request through a form; the document is built from the template and lands in the registry.'], ['Approval and signature', 'An approval chain by routing rules, version comparison, built-in signature or DocuSign.'], ['Control and renewal', 'Renewal reminders, delay analytics, the whole history on the contract card.']],
  },
  'invoicing-finance': {
    az: [['Rekvizitləri tənzimləyin', 'Bank rekvizitləri, imzalayan şəxs, möhür və faktura şablonu parametrlərdə.'], ['Faktura kəsin', 'Sövdələşmədən və kataloqdan faktura, PDF və akt bir kliklə, status: qaralama, göndərilib, ödənilib, gecikmiş.'], ['Ödənişləri izləyin', 'Qismən ödənişlər və qalıq kartda, gecikənlərə xatırlatma zənciri, təkrarlanan fakturalar və abunəliklər.'], ['Gəlirliliyi ölçün', 'Xidmət, müştəri, əlavə xərc və ştat üzrə marja; MRR abunəliklər üzrə.']],
    ru: [['Настройте реквизиты', 'Банковские реквизиты, подписант, печать и шаблон счёта в параметрах.'], ['Выставьте счёт', 'Счёт из сделки и каталога, PDF и акт в один клик, статусы: черновик, отправлен, оплачен, просрочен.'], ['Отслеживайте оплаты', 'Частичные оплаты и остаток в карточке, цепочка напоминаний по просроченным, повторяющиеся счета и подписки.'], ['Измеряйте рентабельность', 'Маржа по услугам, клиентам, накладным расходам и штату; MRR по подпискам.']],
    en: [['Set up bank details', 'Bank details, signatory, stamp and invoice template in the settings.'], ['Issue an invoice', 'An invoice from a deal and the catalogue, PDF and act in one click, statuses: draft, sent, paid, overdue.'], ['Track payments', 'Partial payments and balance on the card, a reminder chain for overdue ones, recurring invoices and subscriptions.'], ['Measure profitability', 'Margin by services, customers, overheads and staff; MRR for subscriptions.']],
  },
  'marketing-automation': {
    az: [['Seqmentləri qurun', 'Dinamik seqmentlər şərtlərə görə kontaktları avtomatik toplayır.'], ['Kampaniya yaradın', 'Kanal və şablon seçimi, A/B variantları, göndərmə cədvəli.'], ['Ssenariləri işə salın', 'Əlaqə ssenariləri addımlar və fasilələrlə, hadisələr üzrə avtomatik başlama.'], ['Nəticəni ölçün', 'Atribusiya və ROI hesabatı, sorğular və NPS cavabları müştəri kartında.']],
    ru: [['Соберите сегменты', 'Динамические сегменты автоматически собирают контакты по условиям.'], ['Создайте кампанию', 'Выбор каналов и шаблонов, A/B-варианты, расписание отправки.'], ['Запустите цепочки', 'Цепочки касаний с шагами и паузами, автоматический старт по событиям.'], ['Измерьте результат', 'Отчёт атрибуции и ROI, ответы опросов и NPS в карточке клиента.']],
    en: [['Build segments', 'Dynamic segments collect contacts by rules automatically.'], ['Create a campaign', 'Channel and template choice, A/B variants, send schedule.'], ['Launch journeys', 'Journeys with steps and delays, automatic start on events.'], ['Measure the result', 'Attribution and ROI report, survey and NPS answers on the customer card.']],
  },
  'ai-crm': {
    az: [['Həvalə səviyyəsini seçin', 'Təhlil, təklif və ya avtopilot; gündəlik büdcə və cavab limitləri parametrlərdə.'], ['AI agenti tənzimləyin', 'Hər kanal üçün rejim, persona və bilik bazası, açar sözlərlə operatora ötürmə.'], ['Zəngləri və sövdələşmələri təhlil edin', 'Zəngdən sonra xülasə, mövzular və tapşırıqlar; Da Vinci siqnalları və izahları.'], ['Ssenariləri «yoxla» rejimində sınayın', '14 avtopilot ssenarisi əvvəlcə təsdiqlə işləyir, sonra seçilmişlər avtopilotə keçir.']],
    ru: [['Выберите уровень делегирования', 'Анализ, предложение или автопилот; дневной бюджет и лимиты ответов в настройках.'], ['Настройте AI-агента', 'Режим для каждого канала, персона и база знаний, передача оператору по ключевым словам.'], ['Анализируйте звонки и сделки', 'После звонка резюме, темы и задачи; сигналы и объяснения Da Vinci.'], ['Проверьте сценарии в режиме «проверка»', '14 сценариев автопилота сначала работают с подтверждением, потом выбранные переводятся в автопилот.']],
    en: [['Choose the delegation level', 'Analyse, suggest or autopilot; daily budget and reply limits in the settings.'], ['Configure the AI agent', 'A mode per channel, persona and knowledge base, keyword handover to an operator.'], ['Analyse calls and deals', 'Summary, topics and tasks after a call; Da Vinci signals and explanations.'], ['Test scenarios in review mode', '14 autopilot scenarios first run with confirmation, then selected ones switch to autopilot.']],
  },
  'crm-for-clinics': {
    az: [['Xəstə reyestrini köçürün', 'Xəstələr, həkimlər və personal idxal olunur, sahələr klinikaya uyğunlaşdırılır.'], ['Müraciət kanallarını qoşun', 'WhatsApp və Instagram Inbox-a düşür, resepşn növbə ilə cavab verir, AI qaralama kömək edir.'], ['Ziyarətləri və planları aparın', 'Ziyarətlər və müalicə planları statuslarla, xatırlatmalar kampaniyalarla.'], ['Rəyi toplayın', 'Ziyarətdən sonra NPS sorğusu, sosial monitorinq klinika haqqında qeydləri göstərir.']],
    ru: [['Перенесите реестр пациентов', 'Импорт пациентов, врачей и персонала, поля настраиваются под клинику.'], ['Подключите каналы обращений', 'WhatsApp и Instagram попадают в Inbox, ресепшн отвечает по очереди, AI-черновик помогает.'], ['Ведите визиты и планы', 'Визиты и планы лечения со статусами, напоминания кампаниями.'], ['Собирайте обратную связь', 'NPS-опрос после визита, социальный мониторинг показывает упоминания клиники.']],
    en: [['Migrate the patient registry', 'Import patients, doctors and staff; fields are configured for the clinic.'], ['Connect request channels', 'WhatsApp and Instagram land in the inbox, reception replies by queue, AI drafts help.'], ['Run encounters and plans', 'Encounters and care plans with statuses, reminders as campaigns.'], ['Collect feedback', 'An NPS survey after the visit; social monitoring shows mentions of the clinic.']],
  },
  'crm-for-insurance': {
    az: [['Polisləri və sığortalıları yükləyin', 'Sığortalılar, polislər, benefisiarlar sahə bölməsində statuslarla.'], ['Müraciətləri tiketə çevirin', 'İddia və şikayət müraciətləri SLA ilə tiketlərdə, məsul şəxs və eskalasiya.'], ['Uzadılmaları avtomatlaşdırın', 'Avtomatlaşdırma qaydası və AI ssenarisi müddət yaxınlaşanda tapşırıq və məktub yaradır.'], ['Agent şəbəkəsini idarə edin', 'Satış boru xətləri, kvotalar, ərazilər və KPI Arena reytinqi agentlər üzrə.']],
    ru: [['Загрузите полисы и застрахованных', 'Застрахованные, полисы, бенефициары в отраслевом разделе со статусами.'], ['Превращайте обращения в тикеты', 'Заявления по убыткам и жалобы в тикетах с SLA, ответственный и эскалация.'], ['Автоматизируйте продления', 'Правило автоматизации и AI-сценарий создают задачу и письмо при приближении срока.'], ['Управляйте агентской сетью', 'Воронки продаж, квоты, территории и рейтинг KPI Arena по агентам.']],
    en: [['Load policies and policyholders', 'Policyholders, policies, beneficiaries in the industry section with statuses.'], ['Turn requests into tickets', 'Claims and complaints as tickets with SLA, owner and escalation.'], ['Automate renewals', 'An automation rule and an AI scenario create a task and an email as the date approaches.'], ['Manage the agent network', 'Sales pipelines, quotas, territories and the KPI Arena ranking per agent.']],
  },
  'crm-for-public-sector': {
    az: [['Rolları və hüquqları təyin edin', 'Modul × rol matrisi, sahə səviyyəsində hüquqlar, 2FA, audit jurnalı.'], ['Müraciət kanallarını qoşun', 'E-poçt, portal və messencer müraciətləri SLA ilə tiketlərə çevrilir.'], ['İşləri və lisenziyaları aparın', 'Vətəndaşlar, işlər, lisenziyalar və qrantlar statuslu reyestrlərdə.'], ['Vətəndaşa status göstərin', 'Portalda müraciətin statusu, bilik bazasında tez-tez verilən suallar.']],
    ru: [['Задайте роли и права', 'Матрица модуль × роль, права на уровне полей, 2FA, журнал аудита.'], ['Подключите каналы обращений', 'Обращения из почты, портала и мессенджеров становятся тикетами с SLA.'], ['Ведите дела и лицензии', 'Граждане, дела, лицензии и гранты в реестрах со статусами.'], ['Показывайте статус гражданину', 'Статус обращения в портале, частые вопросы в базе знаний.']],
    en: [['Define roles and rights', 'A module × role matrix, field-level rights, 2FA, audit log.'], ['Connect request channels', 'Requests from email, the portal and messengers become tickets with SLA.'], ['Run cases and licences', 'Citizens, cases, licences and grants in registries with statuses.'], ['Show the status to the citizen', 'Request status in the portal, frequent questions in the knowledge base.']],
  },
  'crm-for-media': {
    az: [['Abunəçiləri köçürün', 'Abunəçilər plan, status və ömürlük gəlirlə reyestrdə.'], ['Reklamçılarla boru xətti qurun', 'Satış boru xətti, kommersiya təklifləri, müqavilələr və fakturalar reklamçılar üçün.'], ['Kampaniyaları idarə edin', 'Reklam kampaniyaları büdcə və müddətlərlə, kontent inventarı.'], ['Sosial şəbəkəni izləyin', 'Mənbələr və açar sözlər, AI cavab qaralamaları, PDF hesabatlar.']],
    ru: [['Перенесите подписчиков', 'Подписчики с планом, статусом и пожизненной выручкой в реестре.'], ['Постройте воронку с рекламодателями', 'Воронка продаж, коммерческие предложения, договоры и счета для рекламодателей.'], ['Управляйте кампаниями', 'Рекламные кампании с бюджетами и сроками, инвентарь контента.'], ['Следите за соцсетями', 'Источники и ключевые слова, AI-черновики ответов, PDF-отчёты.']],
    en: [['Migrate subscribers', 'Subscribers with plan, status and lifetime revenue in the registry.'], ['Build a pipeline with advertisers', 'Sales pipeline, quotes, contracts and invoices for advertisers.'], ['Manage campaigns', 'Ad campaigns with budgets and dates, a content inventory.'], ['Monitor social media', 'Sources and keywords, AI reply drafts, PDF reports.']],
  },
  'crm-for-utilities': {
    az: [['Abonentləri və sayğacları yükləyin', 'Abonentlər və uçot nöqtələri sahə bölməsində.'], ['Çağırışları tiketə çevirin', 'Xidmət çağırışları və qəzalar SLA ilə tiketlərdə, dispetçer növbəsi.'], ['Briqadaları marşruta göndərin', 'Marşrutlar, GPS vizitlər, fotohesabatlar və tapşırıqlar sahə modulunda.'], ['Fakturalar və xatırlatmalar', 'Statuslu və təkrarlanan fakturalar, borclulara xatırlatma zənciri.']],
    ru: [['Загрузите абонентов и счётчики', 'Абоненты и точки учёта в отраслевом разделе.'], ['Превращайте вызовы в тикеты', 'Сервисные вызовы и аварии в тикетах с SLA, диспетчерская очередь.'], ['Отправляйте бригады по маршруту', 'Маршруты, GPS-визиты, фотоотчёты и задачи в полевом модуле.'], ['Счета и напоминания', 'Счета со статусами и повторяющиеся, цепочка напоминаний должникам.']],
    en: [['Load customers and meters', 'Customers and metering points in the industry section.'], ['Turn calls into tickets', 'Service calls and outages as tickets with SLA, a dispatch queue.'], ['Send crews on routes', 'Routes, GPS visits, photo reports and tasks in the field module.'], ['Invoices and reminders', 'Invoices with statuses and recurring ones, a reminder chain for debtors.']],
  },
};
