import type { Lang, Localized } from './product-map';

/** Solution landing pages. Only modules that exist in MODULES are referenced; copy describes screens seen in the audit. */
export type SolutionCopy = { title: string; description: string; keywords: string[]; h1: string; h2: string; intro: string; pains: string[]; faq: [string, string][] };
export type Solution = { slug: string; domainId: string; moduleIds: string[]; industryId?: string; copy: Record<Lang, SolutionCopy> };

const L = (ru: string, az: string, en: string): Localized => ({ ru, az, en });

export const SOLUTION_LABEL = L('Решения', 'Həllər', 'Solutions');
export const SOLUTIONS_INTRO = L('Готовые сценарии LeadDrive под конкретную задачу и отрасль.', 'Konkret tapşırıq və sahə üçün hazır LeadDrive ssenariləri.', 'Ready LeadDrive scenarios for a specific task and industry.');

export const SOLUTIONS: Solution[] = [
  {
    slug: 'whatsapp-crm', domainId: 'omni', moduleIds: ['inbox', 'channels', 'ai-agent-settings', 'business-hours'],
    copy: {
      az: { title: 'WhatsApp CRM — WhatsApp, Instagram və Telegram bir Inbox-da | LeadDrive', description: 'WhatsApp Business, Instagram və Telegram yazışmaları bir CRM Inbox-da: növbələr, məsul şəxslər, AI cavabları və hər söhbətin müştəri kartına bağlanması. Azərbaycan şirkətləri üçün.', keywords: ['WhatsApp CRM', 'WhatsApp Business CRM', 'Instagram CRM', 'Telegram CRM', 'CRM Azərbaycan'], h1: 'WhatsApp CRM:', h2: 'bütün söhbətlər bir yerdə.', intro: 'Müştərilər WhatsApp, Instagram və Telegram-da yazır, əməkdaşlar isə hərə öz telefonunda cavab verir. LeadDrive bütün kanalları bir Inbox-a yığır: kim cavab verir, nə qədər vaxta, nə cavabsız qalıb — hamısı görünür və hər söhbət lid və ya kontakta bağlıdır.', pains: ['Müraciətlər əməkdaşların şəxsi telefonlarında qalır, işdən çıxanda müştəri də gedir.', 'Kim cavab verməlidir və nə vaxt — heç kim bilmir, cavab saatlarla gecikir.', 'Yazışma tarixçəsi CRM-də yoxdur, satış həmişə sıfırdan başlayır.'], faq: [['Hansı kanallar qoşulur?', 'WhatsApp Business, Facebook Messenger, Instagram, Telegram, VK, TikTok, sayt çatı, e-poçt və SMS. Hər provayder üçün addım-addım qoşulma təlimatı kanal kataloqundadır.'], ['AI özü cavab verə bilər?', 'Hər kanal üçün rejim seçilir: insan, AI qaralaması (əməkdaş təsdiqləyir) və ya AI agent. Açar sözlərlə söhbət operatora ötürülür.'], ['İş saatlarından kənar nə olur?', 'Kanallar üzrə həftəlik cədvəl və qeyri-iş vaxtı üçün avtomatik mesaj tənzimlənir.']] },
      ru: { title: 'WhatsApp CRM — WhatsApp, Instagram и Telegram в одном Inbox | LeadDrive', description: 'Переписки WhatsApp Business, Instagram и Telegram в одном CRM-Inbox: очереди, ответственные, AI-ответы и привязка каждой беседы к карточке клиента. Для компаний в Азербайджане.', keywords: ['WhatsApp CRM', 'CRM с WhatsApp', 'Instagram CRM', 'Telegram CRM', 'CRM Азербайджан'], h1: 'WhatsApp CRM:', h2: 'все разговоры в одном месте.', intro: 'Клиенты пишут в WhatsApp, Instagram и Telegram, а сотрудники отвечают каждый со своего телефона. LeadDrive собирает все каналы в один Inbox: кто отвечает, за сколько, что не отвечено — видно сразу, а каждая беседа привязана к лиду или контакту.', pains: ['Заявки остаются в личных телефонах сотрудников, вместе с уволившимся уходит и клиент.', 'Кто и когда должен ответить, никто не знает, ответ задерживается на часы.', 'Истории переписки нет в CRM, продажа каждый раз начинается с нуля.'], faq: [['Какие каналы подключаются?', 'WhatsApp Business, Facebook Messenger, Instagram, Telegram, VK, TikTok, чат на сайте, email и SMS. Для каждого провайдера в каталоге каналов есть пошаговая инструкция.'], ['Может ли AI отвечать сам?', 'Для каждого канала выбирается режим: человек, AI-черновик с подтверждением сотрудника или AI-агент. По ключевым словам разговор передаётся оператору.'], ['Что происходит вне рабочего времени?', 'Настраиваются недельное расписание по каналам и автоматическое сообщение для нерабочего времени.']] },
      en: { title: 'WhatsApp CRM — WhatsApp, Instagram and Telegram in one inbox | LeadDrive', description: 'WhatsApp Business, Instagram and Telegram conversations in one CRM inbox: queues, owners, AI replies and every chat linked to the customer card. For companies in Azerbaijan.', keywords: ['WhatsApp CRM', 'CRM with WhatsApp', 'Instagram CRM', 'Telegram CRM', 'CRM Azerbaijan'], h1: 'WhatsApp CRM:', h2: 'every conversation in one place.', intro: 'Customers write on WhatsApp, Instagram and Telegram while employees reply from their own phones. LeadDrive gathers every channel into one inbox: who replies, how fast, what is still unanswered — all visible, and every chat is linked to a lead or contact.', pains: ['Requests stay on employees’ personal phones; when they leave, the customer leaves too.', 'Nobody knows who should reply and when; answers slip by hours.', 'There is no conversation history in the CRM, so every sale starts from scratch.'], faq: [['Which channels can be connected?', 'WhatsApp Business, Facebook Messenger, Instagram, Telegram, VK, TikTok, website chat, email and SMS. The channel catalogue has step-by-step setup for each provider.'], ['Can the AI reply on its own?', 'A mode is chosen per channel: a person, an AI draft confirmed by an employee, or an AI agent. Keywords hand the conversation to an operator.'], ['What happens outside business hours?', 'A weekly schedule per channel and an automatic out-of-hours message are configured.']] },
    },
  },
  {
    slug: 'sales-crm', domainId: 'sales', moduleIds: ['leads', 'deals', 'quotes', 'forecast', 'sales-settings'],
    copy: {
      az: { title: 'Satış üçün CRM — lidlər, pipeline-lar, təkliflər və proqnoz | LeadDrive', description: 'Satış CRM sistemi: lid reyestri və zəng növbələri, bir neçə satış pipeline-ı, kommersiya təklifləri kataloqdan, gəlir proqnozu və kvotalar. Azərbaycan şirkətləri üçün.', keywords: ['satış CRM', 'CRM satış', 'satış pipeline-ı', 'lid idarəetməsi', 'CRM sistemi'], h1: 'Satış üçün CRM:', h2: 'liddən sövdələşməyə qədər.', intro: 'Hər sövdələşmənin mərhələsi, məsul şəxsi və növbəti addımı var. Lidlər qiymətləndirilir və zəng növbələrinə düşür, təkliflər kataloqdan yığılır, proqnoz və kvotalar real pipeline-dan hesablanır.', pains: ['Lidlər cədvəllərdə və mesajlarda itir, kim nəyi izləyir bilinmir.', 'Rəhbər ayın sonunda nə qədər gəlir gələcəyini görmür.', 'Təkliflər əl ilə Word-də yığılır və qiymətlər hər dəfə fərqli olur.'], faq: [['Bir neçə satış pipeline-ı ola bilər?', 'Bəli. Hər pipeline-ın öz mərhələləri, ehtimalları və keçid qaydaları var; sistemdə eyni vaxtda bir neçə satış xətti işləyir.'], ['Lidlər menecerlər arasında necə bölünür?', 'Şərtlərə və ya növbə ilə (round robin) bölgü qaydaları, ərazilər və rüblük kvotalar tənzimlənir.'], ['Proqnoz nədən hesablanır?', 'Pipeline mərhələlərinin ehtimalından, kvotalardan və tarixə görə saxlanan proqnoz görüntülərindən; dəyişikliklər şəlalə hesabatında görünür.']] },
      ru: { title: 'CRM для продаж — лиды, воронки, предложения и прогноз | LeadDrive', description: 'CRM-система для отдела продаж: реестр лидов и очереди звонков, несколько воронок, коммерческие предложения из каталога, прогноз выручки и квоты. Для компаний в Азербайджане.', keywords: ['CRM для продаж', 'CRM отдел продаж', 'воронка продаж', 'управление лидами', 'CRM система'], h1: 'CRM для продаж:', h2: 'от лида до сделки.', intro: 'У каждой сделки есть стадия, ответственный и следующий шаг. Лиды квалифицируются и попадают в очереди звонков, предложения собираются из каталога, прогноз и квоты считаются по реальной воронке.', pains: ['Лиды теряются в таблицах и чатах, непонятно, кто что ведёт.', 'Руководитель не видит, сколько денег придёт в конце месяца.', 'Предложения собираются вручную в Word, цены каждый раз разные.'], faq: [['Можно ли вести несколько воронок?', 'Да. У каждой воронки свои стадии, вероятности и правила перехода; в системе одновременно работают несколько линий продаж.'], ['Как распределяются лиды между менеджерами?', 'Правила распределения по условиям или по очереди (round robin), территории и квартальные квоты настраиваются в CRM.'], ['Из чего считается прогноз?', 'Из вероятностей стадий воронки, квот и снимков прогноза на дату; изменения видны в отчёте-водопаде.']] },
      en: { title: 'Sales CRM — leads, pipelines, quotes and forecast | LeadDrive', description: 'A CRM for sales teams: lead registry and call queues, multiple pipelines, quotes from the catalogue, revenue forecast and quotas. For companies in Azerbaijan.', keywords: ['sales CRM', 'CRM for sales team', 'sales pipeline', 'lead management', 'CRM software'], h1: 'Sales CRM:', h2: 'from lead to deal.', intro: 'Every deal has a stage, an owner and a next step. Leads are qualified and routed to call queues, quotes are built from the catalogue, forecast and quotas are calculated from the real pipeline.', pains: ['Leads get lost in spreadsheets and chats; nobody knows who owns what.', 'The leader cannot see how much revenue will land by month end.', 'Quotes are built by hand in Word and prices differ every time.'], faq: [['Can we run several pipelines?', 'Yes. Each pipeline has its own stages, probabilities and transition rules; several sales lines run in parallel.'], ['How are leads distributed between managers?', 'Assignment rules by conditions or round robin, territories and quarterly quotas are configured in the CRM.'], ['What is the forecast based on?', 'Stage probabilities, quotas and dated forecast snapshots; changes show in the waterfall report.']] },
    },
  },
  {
    slug: 'support-helpdesk-crm', domainId: 'support', moduleIds: ['service-desk', 'sla-routing', 'agent-workspace', 'knowledge-portal'],
    copy: {
      az: { title: 'Dəstək və tiket sistemi — SLA, eskalasiya, bilik bazası | LeadDrive', description: 'Service Desk: SLA və eskalasiyalı tiketlər, bacarıq üzrə yönləndirmə, makrolar, şikayət reyestri, bilik bazası və müştəri portalı bir CRM-də.', keywords: ['tiket sistemi', 'helpdesk', 'service desk', 'SLA', 'müştəri dəstəyi CRM'], h1: 'Dəstək və tiketlər:', h2: 'heç bir müraciət itmir.', intro: 'Müraciətlər e-poçt, WhatsApp, sayt çatı və portaldan tiket olur. Prioritet, SLA və eskalasiya qaydaları müddətlərə nəzarət edir, makrolar bir kliklə cavab verir, bilik bazası agentlərə və AI cavablarına kömək edir.', pains: ['Cavab müddətlərinə heç kim nəzarət etmir, müştərilər gözləyir.', 'Eyni suallara hər dəfə əl ilə cavab yazılır.', 'Şikayətlər ayrı Excel-də, tiketlərlə əlaqəsi yoxdur.'], faq: [['SLA necə işləyir?', 'Prioritetlər üzrə cavab və həll müddətləri, L1–L3 eskalasiya qaydaları və şirkətlər üçün dəstək şərtləri şablonlarla təyin olunur.'], ['Tiketlər agentlərə necə paylanır?', 'Agent bacarıqları üzrə növbələr və ən az yüklü agent metodu ilə avtomatik təyinat.'], ['Müştəri öz tiketlərini görə bilər?', 'Bəli, müştəri portalı vasitəsilə; giriş kontaktlara portal istifadəçiləri bölməsində verilir.']] },
      ru: { title: 'Служба поддержки и тикеты — SLA, эскалация, база знаний | LeadDrive', description: 'Service Desk: тикеты с SLA и эскалацией, маршрутизация по навыкам, макросы, реестр жалоб, база знаний и клиентский портал в одной CRM.', keywords: ['система тикетов', 'helpdesk', 'service desk', 'SLA', 'CRM для поддержки'], h1: 'Поддержка и тикеты:', h2: 'ни одно обращение не теряется.', intro: 'Обращения из почты, WhatsApp, чата на сайте и портала становятся тикетами. Приоритеты, SLA и правила эскалации следят за сроками, макросы отвечают в один клик, база знаний помогает агентам и AI-ответам.', pains: ['Сроки ответа никто не контролирует, клиенты ждут.', 'На одни и те же вопросы каждый раз пишут ответ вручную.', 'Жалобы ведутся в отдельном Excel и не связаны с тикетами.'], faq: [['Как работает SLA?', 'Сроки ответа и решения по приоритетам, правила эскалации L1–L3 и условия поддержки для компаний задаются шаблонами.'], ['Как тикеты распределяются между агентами?', 'Очереди по навыкам агентов и автоматическое назначение методом наименьшей загрузки.'], ['Видит ли клиент свои тикеты?', 'Да, через клиентский портал; доступ выдаётся контактам в разделе пользователей портала.']] },
      en: { title: 'Helpdesk and ticketing — SLA, escalation, knowledge base | LeadDrive', description: 'Service Desk: tickets with SLA and escalation, skill-based routing, macros, a complaint registry, knowledge base and customer portal in one CRM.', keywords: ['ticketing system', 'helpdesk', 'service desk', 'SLA', 'customer support CRM'], h1: 'Support and tickets:', h2: 'no request gets lost.', intro: 'Requests from email, WhatsApp, website chat and the portal become tickets. Priorities, SLA and escalation rules watch the deadlines, macros reply in one click, the knowledge base helps agents and AI replies.', pains: ['Nobody tracks response times; customers wait.', 'The same questions are answered by hand every time.', 'Complaints live in a separate spreadsheet, unlinked from tickets.'], faq: [['How does SLA work?', 'Response and resolution times by priority, L1–L3 escalation rules and support entitlements for companies are set with templates.'], ['How are tickets distributed between agents?', 'Skill-based queues and automatic assignment to the least loaded agent.'], ['Can customers see their tickets?', 'Yes, through the customer portal; access is granted to contacts in the portal users section.']] },
    },
  },
  {
    slug: 'field-sales-crm', domainId: 'field', moduleIds: ['field-routes', 'field-points', 'field-control', 'workforce'],
    copy: {
      az: { title: 'Sahə satışları və marşrutlar — GPS vizitlər, fotohesabatlar, KPI | LeadDrive', description: 'Sahə komandaları üçün CRM: günlük marşrutlar, GPS təsdiqli vizitlər, nöqtələr və kontaktlar, fotohesabatlar, canlı xəritə, agent reytinqi və iş vaxtı tabeli.', keywords: ['sahə satışları CRM', 'marşrut planlaması', 'GPS vizit', 'merçendayzinq', 'tibbi nümayəndə CRM'], h1: 'Sahə satışları:', h2: 'marşrut, vizit, sübut.', intro: 'Agentlər yoldadır, rəhbər isə canlı xəritədə kimin harada olduğunu, hansı vizitlərin GPS ilə təsdiqləndiyini və hansı fotohesabatların gəldiyini görür. Plan icrası və KPI reytinqi avtomatik hesablanır.', pains: ['Agentin real olaraq harada olduğu və nə etdiyi bilinmir.', 'Vizit hesabatları WhatsApp-a fotolarla gəlir və itir.', 'Plan icrası ayın sonunda əl ilə hesablanır.'], faq: [['Vizit necə təsdiqlənir?', 'Agent nöqtədə vizit qeyd edir, sistem GPS mövqeyini və geozonaya uyğunluğu yoxlayır; sapmalar xəbərdarlıq kimi gəlir.'], ['Fotohesabatlar kim tərəfindən yoxlanır?', 'Moderasiya növbəsində rəhbər fotoları təsdiqləyir və ya rədd edir; promo faktları L1/L2 yoxlamadan keçir.'], ['KPI necə hesablanır?', 'Tapşırıq icrası, foto təsdiqi və marşrut icrası çəkiləri ilə; hədlər KPI Arena parametrlərində tənzimlənir.']] },
      ru: { title: 'Полевые продажи и маршруты — GPS-визиты, фотоотчёты, KPI | LeadDrive', description: 'CRM для полевых команд: маршруты по дням, визиты с GPS-подтверждением, точки и контакты, фотоотчёты, живая карта, рейтинг агентов и табель рабочего времени.', keywords: ['CRM для полевых продаж', 'планирование маршрутов', 'GPS визиты', 'мерчендайзинг', 'CRM для медпредставителей'], h1: 'Полевые продажи:', h2: 'маршрут, визит, доказательство.', intro: 'Агенты в дороге, а руководитель видит на живой карте, кто где находится, какие визиты подтверждены GPS и какие фотоотчёты пришли. Исполнение плана и рейтинг KPI считаются автоматически.', pains: ['Неизвестно, где реально агент и что он сделал.', 'Отчёты о визитах приходят фотографиями в WhatsApp и теряются.', 'Исполнение плана считают вручную в конце месяца.'], faq: [['Как подтверждается визит?', 'Агент регистрирует визит на точке, система проверяет GPS-позицию и попадание в геозону; отклонения приходят предупреждениями.'], ['Кто проверяет фотоотчёты?', 'В очереди модерации руководитель подтверждает или отклоняет фото; промо-факты проходят проверку L1/L2.'], ['Как считается KPI?', 'По весам исполнения задач, подтверждения фото и исполнения маршрута; пороги настраиваются в параметрах KPI Arena.']] },
      en: { title: 'Field sales and routes — GPS visits, photo reports, KPI | LeadDrive', description: 'A CRM for field teams: daily routes, GPS-confirmed visits, points and contacts, photo reports, a live map, agent ranking and a working-time timesheet.', keywords: ['field sales CRM', 'route planning', 'GPS visits', 'merchandising', 'medical rep CRM'], h1: 'Field sales:', h2: 'route, visit, proof.', intro: 'Agents are on the road while the manager sees on a live map who is where, which visits are GPS-confirmed and which photo reports arrived. Plan execution and the KPI ranking are calculated automatically.', pains: ['Nobody knows where the agent really is or what they did.', 'Visit reports arrive as photos on WhatsApp and get lost.', 'Plan execution is calculated by hand at month end.'], faq: [['How is a visit confirmed?', 'The agent checks in at the point; the system verifies the GPS position and geofence, deviations arrive as alerts.'], ['Who reviews photo reports?', 'In the moderation queue the manager approves or rejects photos; promo facts pass L1/L2 checks.'], ['How is KPI calculated?', 'By weights for task execution, photo approval and route execution; thresholds are set in KPI Arena settings.']] },
    },
  },
  {
    slug: 'contract-management', domainId: 'contracts', moduleIds: ['contract-registry', 'contract-templates', 'contract-requests', 'contract-lifecycle'],
    copy: {
      az: { title: 'Müqavilə idarəetməsi — şablonlar, təsdiq, e-imza | LeadDrive', description: 'Müqavilə reyestri, bəndli şablonlar, təsdiq zənciri, versiyalar, elektron imza və DocuSign, uzadılma xatırlatmaları və müqavilə analitikası bir CRM-də.', keywords: ['müqavilə idarəetməsi', 'elektron imza', 'müqavilə şablonu', 'CRM müqavilə', 'sənəd dövriyyəsi'], h1: 'Müqavilələr:', h2: 'həftələr yox, günlər.', intro: 'Əməkdaş formadan müqavilə tələb edir, sənəd şablondan yığılır, təsdiq zənciri ilə keçir və elektron imzalanır. Versiyalar müqayisə olunur, uzadılma vaxtı xatırladılır, gecikmələr analitikada görünür.', pains: ['Müqavilə həftələrlə e-poçtlarda gəzir, kimdə qaldığı bilinmir.', 'Versiyalar qarışır, imzalanan mətn təsdiqlənəndən fərqlənir.', 'Uzadılma tarixləri unudulur.'], faq: [['Elektron imza necə işləyir?', 'Daxili HMAC imza həmişə mövcuddur; istəyə görə DocuSign qoşulur. İmza zərfləri müqavilə kartında izlənir.'], ['Şablondan kənarlaşmalar görünür?', 'Bəli, kart şablondan sapmaları, bəndlərin risk səviyyələrini və öhdəlikləri göstərir.'], ['Təsdiq marşrutu tənzimlənir?', 'Standart mərhələlər, marşrut qaydaları və nümayəndəlik (əvəzetmə) parametrlərdə təyin olunur.']] },
      ru: { title: 'Управление договорами — шаблоны, согласование, электронная подпись | LeadDrive', description: 'Реестр договоров, шаблоны с пунктами, цепочка согласования, версии, электронная подпись и DocuSign, напоминания о продлении и аналитика договоров в одной CRM.', keywords: ['управление договорами', 'электронная подпись', 'шаблон договора', 'CRM договоры', 'документооборот'], h1: 'Договоры:', h2: 'дни вместо недель.', intro: 'Сотрудник запрашивает договор через форму, документ собирается из шаблона, проходит цепочку согласования и подписывается электронно. Версии сравниваются, о продлении напоминает система, задержки видны в аналитике.', pains: ['Договор неделями ходит по почте, непонятно, у кого он застрял.', 'Версии путаются, подписанный текст отличается от согласованного.', 'Сроки продления забываются.'], faq: [['Как работает электронная подпись?', 'Встроенная HMAC-подпись доступна всегда; по желанию подключается DocuSign. Конверты подписи отслеживаются в карточке договора.'], ['Видны ли отклонения от шаблона?', 'Да, карточка показывает отклонения от шаблона, уровни риска пунктов и обязательства.'], ['Настраивается ли маршрут согласования?', 'Стандартные этапы, правила маршрута и делегирование задаются в настройках.']] },
      en: { title: 'Contract management — templates, approval, e-signature | LeadDrive', description: 'Contract registry, templates with clauses, approval chain, versions, e-signature and DocuSign, renewal reminders and contract analytics in one CRM.', keywords: ['contract management', 'e-signature', 'contract template', 'CRM contracts', 'document workflow'], h1: 'Contracts:', h2: 'days instead of weeks.', intro: 'An employee requests a contract through a form, the document is built from a template, passes the approval chain and is signed electronically. Versions are compared, renewals are reminded, delays show in analytics.', pains: ['A contract circulates by email for weeks; nobody knows where it is stuck.', 'Versions get mixed up; the signed text differs from the approved one.', 'Renewal dates are forgotten.'], faq: [['How does e-signature work?', 'A built-in HMAC signature is always available; DocuSign can be connected. Signature envelopes are tracked on the contract card.'], ['Are deviations from the template visible?', 'Yes, the card shows deviations from the template, clause risk levels and obligations.'], ['Can the approval route be configured?', 'Standard stages, routing rules and delegation are set in the settings.']] },
    },
  },
  {
    slug: 'invoicing-finance', domainId: 'finance', moduleIds: ['invoices', 'profitability'],
    copy: {
      az: { title: 'Fakturalar və maliyyə — ödənişlər, xatırlatmalar, gəlirlilik | LeadDrive', description: 'Statuslu faktura reyestri, ödənişlər və xatırlatma zənciri, təkrarlanan fakturalar, abunəliklər və MRR, xidmət və müştəri üzrə gəlirlilik modeli CRM-in içində.', keywords: ['faktura sistemi', 'hesab-faktura CRM', 'ödəniş xatırlatması', 'gəlirlilik', 'abunəlik MRR'], h1: 'Fakturalar və maliyyə:', h2: 'kim nə qədər borcludur — bir ekranda.', intro: 'Faktura sövdələşmədən və kataloqdan yaranır, PDF və akt bir kliklə çıxır, ödənişlər və qalıqlar kartda görünür, gecikənlərə xatırlatma zənciri gedir. Gəlirlilik modeli xidmət, müştəri, əlavə xərc və ştat üzrə marjı göstərir.', pains: ['Fakturalar kəsilib, borclar isə yalnız Excel-də.', 'Xatırlatmalar əl ilə göndərilir və ya heç göndərilmir.', 'Hansı müştərinin real gəlirli olduğu bilinmir.'], faq: [['Hansı statuslar var?', 'Qaralama, göndərilib, ödənilib, gecikmiş; qismən ödənişlər və qalıq kartda görünür.'], ['Təkrarlanan fakturalar dəstəklənir?', 'Bəli, abunəliklər və təkrarlanan fakturalar ayrı bölmədə, MRR hesablanır.'], ['Rekvizitlər və möhür?', 'Bank rekvizitləri, imzalayan şəxs və möhür faktura parametrlərində tənzimlənir; PDF möhürlü və möhürsüz çıxır.']] },
      ru: { title: 'Счета и финансы — оплаты, напоминания, рентабельность | LeadDrive', description: 'Реестр счетов со статусами, оплаты и цепочка напоминаний, повторяющиеся счета, подписки и MRR, модель рентабельности по услугам и клиентам внутри CRM.', keywords: ['выставление счетов', 'счета в CRM', 'напоминание об оплате', 'рентабельность', 'подписки MRR'], h1: 'Счета и финансы:', h2: 'кто и сколько должен, на одном экране.', intro: 'Счёт создаётся из сделки и каталога, PDF и акт выходят в один клик, оплаты и остатки видны в карточке, по просроченным идёт цепочка напоминаний. Модель рентабельности показывает маржу по услугам, клиентам, накладным расходам и штату.', pains: ['Счета выставлены, а долги только в Excel.', 'Напоминания отправляют вручную или не отправляют вовсе.', 'Непонятно, какой клиент на самом деле прибыльный.'], faq: [['Какие есть статусы?', 'Черновик, отправлен, оплачен, просрочен; частичные оплаты и остаток видны в карточке.'], ['Поддерживаются ли повторяющиеся счета?', 'Да, подписки и повторяющиеся счета ведутся в отдельном разделе, считается MRR.'], ['Реквизиты и печать?', 'Банковские реквизиты, подписант и печать настраиваются в параметрах счетов; PDF выходит с печатью и без.']] },
      en: { title: 'Invoicing and finance — payments, reminders, profitability | LeadDrive', description: 'Invoice registry with statuses, payments and a reminder chain, recurring invoices, subscriptions and MRR, a profitability model by service and customer inside the CRM.', keywords: ['invoicing', 'invoices in CRM', 'payment reminders', 'profitability', 'subscriptions MRR'], h1: 'Invoices and finance:', h2: 'who owes what, on one screen.', intro: 'An invoice is created from a deal and the catalogue, PDF and act come out in one click, payments and balances show on the card, overdue ones get a reminder chain. The profitability model shows margin by services, customers, overheads and staff.', pains: ['Invoices are issued, but debts live only in Excel.', 'Reminders are sent by hand or not at all.', 'Nobody knows which customer is actually profitable.'], faq: [['Which statuses exist?', 'Draft, sent, paid, overdue; partial payments and the balance are visible on the card.'], ['Are recurring invoices supported?', 'Yes, subscriptions and recurring invoices live in a separate section and MRR is calculated.'], ['Bank details and stamp?', 'Bank details, signatory and stamp are set in invoice settings; the PDF comes with or without the stamp.']] },
    },
  },
  {
    slug: 'marketing-automation', domainId: 'marketing', moduleIds: ['campaigns', 'email', 'journeys', 'surveys'],
    copy: {
      az: { title: 'Marketinq avtomatlaşdırması — seqmentlər, kampaniyalar, NPS | LeadDrive', description: 'Dinamik seqmentlər, çoxkanallı kampaniyalar və A/B variantları, əlaqə ssenariləri, e-poçt şablonları, atribusiya və ROI, sorğular və NPS — hamısı CRM kontaktları üzərində.', keywords: ['marketinq avtomatlaşdırması', 'e-poçt marketinqi', 'seqmentasiya', 'NPS sorğusu', 'CRM marketinq'], h1: 'Marketinq:', h2: 'düzgün mesaj, düzgün auditoriya.', intro: 'Seqmentlər kontaktları şərtlərə görə toplayır, kampaniyalar kanal və şablon seçir, ssenarilər addımları və fasilələri idarə edir. Nəticə atribusiya və ROI hesabatında, müştəri rəyi isə NPS sorğularında.', pains: ['Bütün bazaya eyni məktub göndərilir, cavab yoxdur.', 'Kampaniyanın satışa təsiri hesablanmır.', 'Müştəri rəyi toplanmır və ya CRM-ə bağlı deyil.'], faq: [['Seqmentlər dinamikdir?', 'Bəli, kontaktlar şərtlərə görə avtomatik daxil olur və çıxır.'], ['A/B testlər var?', 'Kampaniya daxilində A/B variantları seçilir; nəticələr göndərilmə, açılma və klik üzrə görünür.'], ['NPS cavabları hara düşür?', 'Cavablar CRM kartlarına bağlanır və müştəri kontekstində görünür.']] },
      ru: { title: 'Маркетинговая автоматизация — сегменты, кампании, NPS | LeadDrive', description: 'Динамические сегменты, многоканальные кампании и A/B-варианты, цепочки касаний, email-шаблоны, атрибуция и ROI, опросы и NPS — всё поверх контактов CRM.', keywords: ['маркетинговая автоматизация', 'email маркетинг', 'сегментация', 'NPS опрос', 'CRM маркетинг'], h1: 'Маркетинг:', h2: 'нужное сообщение нужной аудитории.', intro: 'Сегменты собирают контакты по условиям, кампании выбирают каналы и шаблоны, цепочки управляют шагами и паузами. Результат виден в атрибуции и ROI, обратная связь приходит через опросы и NPS.', pains: ['Всей базе уходит одно и то же письмо, ответа нет.', 'Влияние кампаний на продажи не считается.', 'Обратная связь от клиентов не собирается или не связана с CRM.'], faq: [['Сегменты динамические?', 'Да, контакты автоматически попадают в сегмент и выходят из него по условиям.'], ['Есть A/B-тесты?', 'Внутри кампании выбираются A/B-варианты; результаты видны по отправкам, открытиям и кликам.'], ['Куда попадают ответы NPS?', 'Ответы привязываются к карточкам CRM и видны в контексте клиента.']] },
      en: { title: 'Marketing automation — segments, campaigns, NPS | LeadDrive', description: 'Dynamic segments, multichannel campaigns and A/B variants, journeys, email templates, attribution and ROI, surveys and NPS — all on top of CRM contacts.', keywords: ['marketing automation', 'email marketing', 'segmentation', 'NPS survey', 'CRM marketing'], h1: 'Marketing:', h2: 'the right message to the right audience.', intro: 'Segments collect contacts by rules, campaigns pick channels and templates, journeys manage steps and delays. Results show in attribution and ROI, feedback arrives through surveys and NPS.', pains: ['The whole base gets the same email; nobody answers.', 'The impact of campaigns on sales is not measured.', 'Customer feedback is not collected or not linked to the CRM.'], faq: [['Are segments dynamic?', 'Yes, contacts enter and leave a segment automatically by rules.'], ['Are there A/B tests?', 'A/B variants are chosen inside a campaign; results show by sends, opens and clicks.'], ['Where do NPS answers go?', 'Answers are linked to CRM cards and visible in the customer context.']] },
    },
  },
  {
    slug: 'ai-crm', domainId: 'platform', moduleIds: ['ai-delegation', 'ai-agent-settings', 'call-insights', 'davinci-advisor'],
    copy: {
      az: { title: 'AI CRM — AI agent, Da Vinci məsləhətçi və avtopilot ssenariləri | LeadDrive', description: 'AI dialoqda cavab verir, zəngləri təhlil edir, sövdələşmələr üzrə siqnal verir və 14 avtopilot ssenarisi ilə rutin işi görür. Üç həvalə səviyyəsi və gündəlik büdcə ilə nəzarət sizdə qalır.', keywords: ['AI CRM', 'süni intellekt CRM', 'AI agent', 'AI satış köməkçisi', 'CRM avtomatlaşdırma'], h1: 'AI CRM-də:', h2: 'nə qədər etibar etmək, siz seçirsiniz.', intro: 'AI agent müştəri ilə kanalda danışır, Da Vinci əməkdaşa siqnal və izah verir, zəngdən sonra xülasə və tapşırıqlar hazırlanır. Avtopilot ssenariləri əvvəlcə «yoxla» rejimində işləyir: heç nə təsdiqsiz göndərilmir.', pains: ['AI-dan qorxursunuz: nə göndərəcəyi bilinmir.', 'Zənglərdən sonra heç kim qeyd yazmır, razılaşmalar unudulur.', 'Rutin xatırlatmalar və follow-up-lar əl ilə edilir.'], faq: [['AI nəyi özbaşına edə bilər?', 'Yalnız avtopilot rejimində və seçilmiş ssenarilər üzrə; «yoxla» rejimində AI hərəkəti hazırlayır, əməkdaş təsdiqləyir.'], ['Xərclər necə məhdudlaşdırılır?', 'Gündəlik AI büdcəsi, dialoq və kontakt üzrə cavab limitləri parametrlərdə təyin olunur; limit aşıldıqda dialoq insana keçir.'], ['Hansı ssenarilər var?', 'Kredit limiti xəbərdarlığı, neqativ ton eskalasiyası, qaynar lid eskalasiyası, avto-bilet təsnifatı, görüş xülasəsi, ödəniş xatırlatması və digərləri — cəmi 14.']] },
      ru: { title: 'AI CRM — AI-агент, советник Da Vinci и сценарии автопилота | LeadDrive', description: 'AI отвечает в диалоге, анализирует звонки, подсказывает по сделкам и делает рутину по 14 сценариям автопилота. Три уровня делегирования и дневной бюджет оставляют контроль за вами.', keywords: ['AI CRM', 'CRM с искусственным интеллектом', 'AI агент', 'AI помощник продаж', 'автоматизация CRM'], h1: 'AI в CRM:', h2: 'сколько доверить, решаете вы.', intro: 'AI-агент общается с клиентом в канале, Da Vinci даёт сотруднику сигналы и объяснения, после звонка готовятся резюме и задачи. Сценарии автопилота сначала работают в режиме «проверка»: без подтверждения ничего не отправляется.', pains: ['Страшно доверять AI: неизвестно, что он отправит.', 'После звонков никто не пишет заметки, договорённости забываются.', 'Рутинные напоминания и follow-up делаются вручную.'], faq: [['Что AI может делать сам?', 'Только в режиме автопилота и по выбранным сценариям; в режиме «проверка» AI готовит действие, а сотрудник подтверждает.'], ['Как ограничиваются расходы?', 'Дневной бюджет AI, лимиты ответов на диалог и на контакт задаются в настройках; при превышении диалог передаётся человеку.'], ['Какие есть сценарии?', 'Предупреждение о кредитном лимите, эскалация негативного тона, эскалация горячего лида, автоклассификация тикетов, резюме встречи, напоминание об оплате и другие — всего 14.']] },
      en: { title: 'AI CRM — AI agent, Da Vinci advisor and autopilot scenarios | LeadDrive', description: 'AI replies in conversations, analyses calls, signals on deals and handles routine through 14 autopilot scenarios. Three delegation levels and a daily budget keep you in control.', keywords: ['AI CRM', 'CRM with artificial intelligence', 'AI agent', 'AI sales assistant', 'CRM automation'], h1: 'AI in the CRM:', h2: 'you decide how much to trust it.', intro: 'The AI agent talks to the customer in the channel, Da Vinci gives the employee signals and explanations, summaries and tasks are prepared after calls. Autopilot scenarios start in “review” mode: nothing is sent without confirmation.', pains: ['Trusting AI is scary: you do not know what it will send.', 'Nobody writes notes after calls; agreements are forgotten.', 'Routine reminders and follow-ups are done by hand.'], faq: [['What can the AI do on its own?', 'Only in autopilot mode and for selected scenarios; in “review” mode the AI prepares the action and an employee confirms it.'], ['How are costs limited?', 'A daily AI budget and reply limits per conversation and per contact are set in the settings; when exceeded, the conversation goes to a person.'], ['Which scenarios exist?', 'Credit limit alert, negative tone escalation, hot lead escalation, auto ticket classification, meeting summary, payment reminder and others — 14 in total.']] },
    },
  },
  {
    slug: 'crm-for-clinics', domainId: 'support', industryId: 'health', moduleIds: ['inbox', 'service-desk', 'campaigns'],
    copy: {
      az: { title: 'Klinikalar üçün CRM — xəstələr, ziyarətlər, WhatsApp | LeadDrive', description: 'Tibb mərkəzləri üçün CRM: xəstə reyestri, ziyarətlər və müalicə planları, WhatsApp və Instagram müraciətləri bir Inbox-da, xatırlatmalar və rəy sorğuları.', keywords: ['klinika CRM', 'tibb mərkəzi CRM', 'xəstə bazası', 'stomatologiya CRM', 'CRM Bakı'], h1: 'Klinikalar üçün CRM:', h2: 'xəstə ilk mesajdan növbəti ziyarətə qədər.', intro: 'Səhiyyə bölməsində xəstələr, ziyarətlər, müalicə planları və həkimlər saxlanılır; müraciətlər WhatsApp və Instagram-dan ümumi Inbox-a düşür; xatırlatmalar və rəy sorğuları kampaniyalarla göndərilir.', pains: ['Xəstə WhatsApp-a yazır, resepşn gecikir, xəstə başqa klinikaya gedir.', 'Ziyarət tarixçəsi kağızda və ya ayrı proqramda.', 'Rəy toplanmır, şikayətlər sosial şəbəkəyə çıxır.'], faq: [['Bu tibbi informasiya sistemidir?', 'Xeyr. LeadDrive müştəri münasibətlərini idarə edir: xəstə reyestri, ziyarətlər, planlar, ünsiyyət və marketinq. Tibbi kartlar üçün ixtisaslaşmış sistemlər qalır.'], ['Sahə bölmələrində nə var?', 'Xəstələr, ziyarətlər, müalicə planları, həkimlər və personal — statuslu reyestrlər; sahələr tətbiq zamanı klinikaya uyğunlaşdırılır.'], ['Sosial şəbəkədə klinika haqqında nə yazıldığını izləmək olar?', 'Bəli, sosial monitorinq modulu brend qeydlərini toplayır və AI cavab qaralamaları hazırlayır.']] },
      ru: { title: 'CRM для клиник — пациенты, визиты, WhatsApp | LeadDrive', description: 'CRM для медицинских центров: реестр пациентов, визиты и планы лечения, обращения из WhatsApp и Instagram в одном Inbox, напоминания и опросы обратной связи.', keywords: ['CRM для клиники', 'CRM медицинский центр', 'база пациентов', 'CRM стоматология', 'CRM Баку'], h1: 'CRM для клиник:', h2: 'пациент от первого сообщения до следующего визита.', intro: 'В разделе здравоохранения ведутся пациенты, визиты, планы лечения и врачи; обращения из WhatsApp и Instagram попадают в общий Inbox; напоминания и опросы отправляются кампаниями.', pains: ['Пациент пишет в WhatsApp, ресепшн отвечает с опозданием, пациент уходит в другую клинику.', 'История визитов на бумаге или в отдельной программе.', 'Обратная связь не собирается, жалобы уходят в соцсети.'], faq: [['Это медицинская информационная система?', 'Нет. LeadDrive управляет отношениями с пациентами: реестр, визиты, планы, общение и маркетинг. Медицинские карты остаются в специализированных системах.'], ['Что есть в отраслевых разделах?', 'Пациенты, визиты, планы лечения, врачи и персонал — реестры со статусами; поля настраиваются под клинику при внедрении.'], ['Можно ли следить, что пишут о клинике в соцсетях?', 'Да, модуль социального мониторинга собирает упоминания бренда и готовит AI-черновики ответов.']] },
      en: { title: 'CRM for clinics — patients, encounters, WhatsApp | LeadDrive', description: 'A CRM for medical centres: patient registry, encounters and care plans, WhatsApp and Instagram requests in one inbox, reminders and feedback surveys.', keywords: ['clinic CRM', 'medical centre CRM', 'patient database', 'dental CRM', 'CRM Baku'], h1: 'CRM for clinics:', h2: 'the patient from the first message to the next visit.', intro: 'The healthcare section holds patients, encounters, care plans and doctors; requests from WhatsApp and Instagram land in the shared inbox; reminders and surveys go out as campaigns.', pains: ['A patient writes on WhatsApp, reception replies late, the patient goes to another clinic.', 'Visit history is on paper or in a separate program.', 'Feedback is not collected; complaints end up on social media.'], faq: [['Is this a medical information system?', 'No. LeadDrive manages patient relationships: registry, encounters, plans, communication and marketing. Medical records stay in specialised systems.'], ['What is in the industry sections?', 'Patients, encounters, care plans, doctors and staff — registries with statuses; fields are configured for the clinic during implementation.'], ['Can we monitor what people say about the clinic on social media?', 'Yes, the social monitoring module collects brand mentions and prepares AI reply drafts.']] },
    },
  },
  {
    slug: 'crm-for-insurance', domainId: 'support', industryId: 'insurance', moduleIds: ['service-desk', 'contract-registry', 'invoices'],
    copy: {
      az: { title: 'Sığorta şirkətləri üçün CRM — polislər, iddialar, müştərilər | LeadDrive', description: 'Sığorta buludu: sığortalılar, polislər, iddialar və benefisiarlar; müraciətlər və şikayətlər SLA ilə tiketlərdə; müqavilələr və fakturalar bir CRM-də.', keywords: ['sığorta CRM', 'sığorta şirkəti proqramı', 'polis idarəetməsi', 'iddia emalı', 'CRM Azərbaycan'], h1: 'Sığorta üçün CRM:', h2: 'polis, iddia və müştəri bir kartda.', intro: 'Sığortalılar, polislər, iddialar və benefisiarlar sahə bölməsində saxlanılır. Müştəri müraciətləri SLA ilə tiketlərə çevrilir, uzadılmalar xatırladılır, fakturalar və müqavilələr eyni müştəri kartına bağlıdır.', pains: ['Polisin uzadılma vaxtı keçir, müştəri rəqibə gedir.', 'İddia müraciətləri e-poçtda itir, müddətlərə nəzarət yoxdur.', 'Agentlərin satış pipeline-ı görünmür.'], faq: [['İddialar necə emal olunur?', 'İddia reyestrində status və məsul şəxs, müştəri ilə yazışma isə tiket və Inbox vasitəsilə aparılır.'], ['Uzadılma xatırlatmaları avtomatikdir?', 'Avtomatlaşdırma qaydaları və AI ssenarisi «Yenilənmə təklifi» müddət yaxınlaşanda tapşırıq və məktub yaradır.'], ['Agent şəbəkəsi üçün uyğundur?', 'Bəli: satış pipeline-ları, kvotalar, ərazilər və KPI Arena reytinqi agentlər üzrə işləyir.']] },
      ru: { title: 'CRM для страховых компаний — полисы, требования, клиенты | LeadDrive', description: 'Страховое облако: застрахованные, полисы, требования и бенефициары; обращения и жалобы в тикетах с SLA; договоры и счета в одной CRM.', keywords: ['CRM для страхования', 'программа для страховой компании', 'учёт полисов', 'урегулирование убытков', 'CRM Азербайджан'], h1: 'CRM для страхования:', h2: 'полис, требование и клиент в одной карточке.', intro: 'Застрахованные, полисы, требования и бенефициары ведутся в отраслевом разделе. Обращения клиентов становятся тикетами с SLA, о продлениях напоминает система, счета и договоры привязаны к той же карточке клиента.', pains: ['Срок продления полиса проходит, клиент уходит к конкуренту.', 'Заявления по убыткам теряются в почте, сроки не контролируются.', 'Воронка продаж агентов не видна.'], faq: [['Как обрабатываются требования?', 'В реестре требований ведутся статус и ответственный, переписка с клиентом идёт через тикеты и Inbox.'], ['Напоминания о продлении автоматические?', 'Правила автоматизации и AI-сценарий «Предложение о продлении» создают задачу и письмо при приближении срока.'], ['Подходит ли для агентской сети?', 'Да: воронки продаж, квоты, территории и рейтинг KPI Arena работают по агентам.']] },
      en: { title: 'CRM for insurance companies — policies, claims, customers | LeadDrive', description: 'Insurance cloud: policyholders, policies, claims and beneficiaries; requests and complaints as tickets with SLA; contracts and invoices in one CRM.', keywords: ['insurance CRM', 'insurance company software', 'policy management', 'claims handling', 'CRM Azerbaijan'], h1: 'CRM for insurance:', h2: 'policy, claim and customer on one card.', intro: 'Policyholders, policies, claims and beneficiaries live in the industry section. Customer requests become tickets with SLA, renewals are reminded, invoices and contracts are linked to the same customer card.', pains: ['A policy renewal date passes; the customer goes to a competitor.', 'Claim requests get lost in email; deadlines are not tracked.', 'The agents’ sales pipeline is invisible.'], faq: [['How are claims handled?', 'The claims registry keeps status and owner; customer correspondence runs through tickets and the inbox.'], ['Are renewal reminders automatic?', 'Automation rules and the “Renewal offer” AI scenario create a task and an email as the date approaches.'], ['Does it fit an agent network?', 'Yes: sales pipelines, quotas, territories and the KPI Arena ranking work per agent.']] },
    },
  },
  {
    slug: 'crm-for-public-sector', domainId: 'support', industryId: 'public-sector', moduleIds: ['service-desk', 'knowledge-portal', 'contract-registry'],
    copy: {
      az: { title: 'Dövlət sektoru üçün CRM — vətəndaş müraciətləri, lisenziyalar, qrantlar | LeadDrive', description: 'Vətəndaşlar, işlər və müraciətlər, lisenziyalar və icazələr, qrantlar; müraciətlər SLA ilə tiketlərdə, bilik bazası və portal; audit jurnalı və rollar.', keywords: ['dövlət qurumu CRM', 'vətəndaş müraciətləri', 'elektron xidmət', 'qrant idarəetməsi', 'CRM Azərbaycan'], h1: 'Dövlət sektoru:', h2: 'hər müraciətin izi və müddəti var.', intro: 'Vətəndaşlar, işlər, lisenziyalar və qrantlar sahə bölməsində saxlanılır. Müraciətlər SLA və eskalasiya ilə tiketlərə çevrilir, portal vətəndaşa statusu göstərir, audit jurnalı hər hərəkəti qeyd edir.', pains: ['Müraciətlər müxtəlif kanallardan gəlir və müddətlər itir.', 'Kimin nə etdiyi yoxlanıla bilmir.', 'Vətəndaş statusu öyrənmək üçün zəng edir.'], faq: [['Giriş hüquqları necə məhdudlaşdırılır?', 'Rollar, modul × rol matrisi, sahə səviyyəsində hüquqlar və paylaşma qaydaları; hər hərəkət audit jurnalında.'], ['Vətəndaş öz müraciətini görə bilər?', 'Bəli, müştəri portalı vasitəsilə; bilik bazası tez-tez verilən suallara cavab verir.'], ['İkifaktorlu giriş var?', 'Bəli, tətbiq və ya SMS ilə 2FA, API açarları və audit jurnalı Təhlükəsizlik bölməsindədir.']] },
      ru: { title: 'CRM для госсектора — обращения граждан, лицензии, гранты | LeadDrive', description: 'Граждане, дела и обращения, лицензии и разрешения, гранты; обращения в тикетах с SLA, база знаний и портал; журнал аудита и роли.', keywords: ['CRM для госорганов', 'обращения граждан', 'электронные услуги', 'управление грантами', 'CRM Азербайджан'], h1: 'Госсектор:', h2: 'у каждого обращения есть след и срок.', intro: 'Граждане, дела, лицензии и гранты ведутся в отраслевом разделе. Обращения становятся тикетами с SLA и эскалацией, портал показывает гражданину статус, журнал аудита фиксирует каждое действие.', pains: ['Обращения приходят из разных каналов, сроки теряются.', 'Невозможно проверить, кто что сделал.', 'Гражданин звонит, чтобы узнать статус.'], faq: [['Как ограничиваются права доступа?', 'Роли, матрица модуль × роль, права на уровне полей и правила совместного доступа; каждое действие в журнале аудита.'], ['Видит ли гражданин своё обращение?', 'Да, через клиентский портал; база знаний отвечает на частые вопросы.'], ['Есть двухфакторный вход?', 'Да, 2FA через приложение или SMS, API-ключи и журнал аудита в разделе безопасности.']] },
      en: { title: 'CRM for the public sector — citizen requests, licences, grants | LeadDrive', description: 'Citizens, cases and requests, licences and permits, grants; requests as tickets with SLA, knowledge base and portal; audit log and roles.', keywords: ['public sector CRM', 'citizen requests', 'e-services', 'grant management', 'CRM Azerbaijan'], h1: 'Public sector:', h2: 'every request has a trail and a deadline.', intro: 'Citizens, cases, licences and grants live in the industry section. Requests become tickets with SLA and escalation, the portal shows the citizen the status, the audit log records every action.', pains: ['Requests come through different channels; deadlines get lost.', 'It is impossible to check who did what.', 'Citizens call to find out the status.'], faq: [['How are access rights limited?', 'Roles, a module × role matrix, field-level rights and sharing rules; every action is in the audit log.'], ['Can a citizen see their request?', 'Yes, through the customer portal; the knowledge base answers frequent questions.'], ['Is there two-factor login?', 'Yes, 2FA via app or SMS, API keys and the audit log in the Security section.']] },
    },
  },
  {
    slug: 'crm-for-media', domainId: 'marketing', industryId: 'media', moduleIds: ['campaigns', 'social-findings', 'invoices'],
    copy: {
      az: { title: 'Media və nəşrlər üçün CRM — abunəçilər, kontent, reklam kampaniyaları | LeadDrive', description: 'Media buludu: abunəçilər və planlar, kontent kitabxanası, reklam kampaniyaları büdcə və müddətlərlə; sosial monitorinq, kampaniyalar və fakturalar bir CRM-də.', keywords: ['media CRM', 'abunəçi idarəetməsi', 'reklam kampaniyaları', 'nəşriyyat CRM', 'sosial monitorinq'], h1: 'Media üçün CRM:', h2: 'abunəçi, kontent və reklamçı bir yerdə.', intro: 'Abunəçilər planlar və statuslarla, kontent inventarı və reklam kampaniyaları sahə bölməsində; reklamçılarla satış pipeline-ı, fakturalar və müqavilələr; brend qeydləri sosial monitorinqdə.', pains: ['Abunəçi bazası bir yerdə, reklamçılar başqa yerdə.', 'Reklam kampaniyasının büdcəsi və nəticəsi izlənmir.', 'Oxucu rəyi və qeydlər sosial şəbəkədə itir.'], faq: [['Abunəçi planları var?', 'Bəli, abunəçi reyestri plan, status və ömürlük gəlirlə aparılır.'], ['Reklamçılar üçün nə var?', 'Satış pipeline-ı, kommersiya təklifləri, müqavilələr və fakturalar — ümumi CRM modulları.'], ['Sosial şəbəkəni izləmək olar?', 'Sosial monitorinq mənbələri, açar sözləri və AI cavab qaralamalarını dəstəkləyir; PDF hesabatlar müştərilər üçün hazırlanır.']] },
      ru: { title: 'CRM для медиа и изданий — подписчики, контент, рекламные кампании | LeadDrive', description: 'Медиа-облако: подписчики и планы, библиотека контента, рекламные кампании с бюджетами и сроками; социальный мониторинг, кампании и счета в одной CRM.', keywords: ['CRM для медиа', 'управление подписчиками', 'рекламные кампании', 'CRM издательство', 'социальный мониторинг'], h1: 'CRM для медиа:', h2: 'подписчик, контент и рекламодатель вместе.', intro: 'Подписчики с планами и статусами, инвентарь контента и рекламные кампании в отраслевом разделе; воронка продаж с рекламодателями, счета и договоры; упоминания бренда в социальном мониторинге.', pains: ['База подписчиков в одном месте, рекламодатели в другом.', 'Бюджет и результат рекламной кампании не отслеживаются.', 'Отзывы читателей и упоминания теряются в соцсетях.'], faq: [['Есть планы подписки?', 'Да, реестр подписчиков ведётся с планом, статусом и пожизненной выручкой.'], ['Что есть для рекламодателей?', 'Воронка продаж, коммерческие предложения, договоры и счета — общие модули CRM.'], ['Можно ли следить за соцсетями?', 'Социальный мониторинг поддерживает источники, ключевые слова и AI-черновики ответов; PDF-отчёты готовятся для клиентов.']] },
      en: { title: 'CRM for media and publishers — subscribers, content, ad campaigns | LeadDrive', description: 'Media cloud: subscribers and plans, content library, ad campaigns with budgets and dates; social monitoring, campaigns and invoices in one CRM.', keywords: ['media CRM', 'subscriber management', 'ad campaigns', 'publisher CRM', 'social monitoring'], h1: 'CRM for media:', h2: 'subscriber, content and advertiser together.', intro: 'Subscribers with plans and statuses, a content inventory and ad campaigns in the industry section; a sales pipeline with advertisers, invoices and contracts; brand mentions in social monitoring.', pains: ['The subscriber base is in one place, advertisers in another.', 'Ad campaign budgets and results are not tracked.', 'Reader feedback and mentions get lost on social media.'], faq: [['Are there subscription plans?', 'Yes, the subscriber registry keeps plan, status and lifetime revenue.'], ['What is there for advertisers?', 'A sales pipeline, quotes, contracts and invoices — the shared CRM modules.'], ['Can we monitor social media?', 'Social monitoring supports sources, keywords and AI reply drafts; PDF reports are prepared for clients.']] },
    },
  },
  {
    slug: 'crm-for-utilities', domainId: 'field', industryId: 'energy', moduleIds: ['service-desk', 'field-routes', 'invoices'],
    copy: {
      az: { title: 'Enerji və kommunal xidmətlər üçün CRM — abonentlər, sayğaclar, xidmət çağırışları | LeadDrive', description: 'Enerji buludu: abonentlər, uçot nöqtələri, qəzalar və xidmət çağırışları; dispetçer tiketləri SLA ilə, sahə briqadalarının marşrutları və fakturalar bir CRM-də.', keywords: ['kommunal xidmət CRM', 'abonent idarəetməsi', 'xidmət çağırışları', 'dispetçer sistemi', 'CRM Azərbaycan'], h1: 'Enerji və kommunal:', h2: 'çağırışdan briqadaya qədər.', intro: 'Abonentlər, sayğac nöqtələri, qəzalar və xidmət çağırışları sahə bölməsində. Çağırışlar SLA ilə tiketlərə çevrilir, sahə briqadaları marşrut və GPS vizitlərlə işləyir, fakturalar və xatırlatmalar abonent kartına bağlıdır.', pains: ['Çağırışlar telefonla gəlir və qeydə alınmır.', 'Briqadanın harada olduğu və nə etdiyi görünmür.', 'Borclu abonentlərə xatırlatma sistemli deyil.'], faq: [['Qəzalar necə qeydə alınır?', 'Qəza reyestrində səbəb, ciddilik, təsirlənən sayğaclar və başlama vaxtı saxlanılır.'], ['Briqadalar üçün mobil iş var?', 'Marşrutlar, GPS vizitlər, fotohesabatlar və tapşırıqlar sahə modulunda.'], ['Fakturalar və ödənişlər?', 'Statuslu fakturalar, təkrarlanan fakturalar və xatırlatma zənciri maliyyə modulunda.']] },
      ru: { title: 'CRM для энергетики и ЖКХ — абоненты, счётчики, сервисные вызовы | LeadDrive', description: 'Энергетическое облако: абоненты, точки учёта, аварии и сервисные вызовы; диспетчерские тикеты с SLA, маршруты полевых бригад и счета в одной CRM.', keywords: ['CRM для ЖКХ', 'управление абонентами', 'сервисные вызовы', 'диспетчерская система', 'CRM Азербайджан'], h1: 'Энергетика и ЖКХ:', h2: 'от вызова до бригады.', intro: 'Абоненты, точки учёта, аварии и сервисные вызовы в отраслевом разделе. Вызовы становятся тикетами с SLA, полевые бригады работают по маршрутам с GPS-визитами, счета и напоминания привязаны к карточке абонента.', pains: ['Вызовы приходят по телефону и не фиксируются.', 'Не видно, где бригада и что она сделала.', 'Напоминания должникам несистемные.'], faq: [['Как фиксируются аварии?', 'В реестре аварий хранятся причина, критичность, затронутые счётчики и время начала.'], ['Есть мобильная работа для бригад?', 'Маршруты, GPS-визиты, фотоотчёты и задачи в полевом модуле.'], ['Счета и оплаты?', 'Счета со статусами, повторяющиеся счета и цепочка напоминаний в финансовом модуле.']] },
      en: { title: 'CRM for energy and utilities — customers, meters, service calls | LeadDrive', description: 'Energy cloud: customers, metering points, outages and service calls; dispatch tickets with SLA, field crew routes and invoices in one CRM.', keywords: ['utilities CRM', 'customer management', 'service calls', 'dispatch system', 'CRM Azerbaijan'], h1: 'Energy and utilities:', h2: 'from the call to the crew.', intro: 'Customers, metering points, outages and service calls in the industry section. Calls become tickets with SLA, field crews work on routes with GPS visits, invoices and reminders are linked to the customer card.', pains: ['Calls come by phone and are not recorded.', 'Nobody sees where the crew is or what it did.', 'Reminders to debtors are unsystematic.'], faq: [['How are outages recorded?', 'The outage registry keeps cause, severity, affected meters and start time.'], ['Is there mobile work for crews?', 'Routes, GPS visits, photo reports and tasks in the field module.'], ['Invoices and payments?', 'Invoices with statuses, recurring invoices and a reminder chain in the finance module.']] },
    },
  },
];

export const solutionBySlug = (slug: string) => SOLUTIONS.find((s) => s.slug === slug);
export const solutionPath = (lang: Lang, slug: string) => (lang === 'az' ? '' : `/${lang}`) + `/solutions/${slug}`;
